// Johto Pokedex order, compacted from National order by enabled species.
// Define JOHTO_DEX(name) before including this file.
#if P_FAMILY_BULBASAUR
    JOHTO_DEX(BULBASAUR)
    JOHTO_DEX(IVYSAUR)
    JOHTO_DEX(VENUSAUR)
#endif
#if P_FAMILY_CHARMANDER
    JOHTO_DEX(CHARMANDER)
    JOHTO_DEX(CHARMELEON)
    JOHTO_DEX(CHARIZARD)
#endif
#if P_FAMILY_SQUIRTLE
    JOHTO_DEX(SQUIRTLE)
    JOHTO_DEX(WARTORTLE)
    JOHTO_DEX(BLASTOISE)
#endif
#if P_FAMILY_CATERPIE
    JOHTO_DEX(CATERPIE)
    JOHTO_DEX(METAPOD)
    JOHTO_DEX(BUTTERFREE)
#endif
#if P_FAMILY_WEEDLE
    JOHTO_DEX(WEEDLE)
    JOHTO_DEX(KAKUNA)
    JOHTO_DEX(BEEDRILL)
#endif
#if P_FAMILY_PIDGEY
    JOHTO_DEX(PIDGEY)
    JOHTO_DEX(PIDGEOTTO)
    JOHTO_DEX(PIDGEOT)
#endif
#if P_FAMILY_RATTATA
    JOHTO_DEX(RATTATA)
    JOHTO_DEX(RATICATE)
#endif
#if P_FAMILY_SPEAROW
    JOHTO_DEX(SPEAROW)
    JOHTO_DEX(FEAROW)
#endif
#if P_FAMILY_EKANS
    JOHTO_DEX(EKANS)
    JOHTO_DEX(ARBOK)
#endif
#if P_FAMILY_PIKACHU
    JOHTO_DEX(PIKACHU)
    JOHTO_DEX(RAICHU)
#endif
#if P_FAMILY_SANDSHREW
    JOHTO_DEX(SANDSHREW)
    JOHTO_DEX(SANDSLASH)
#endif
#if P_FAMILY_NIDORAN
    JOHTO_DEX(NIDORAN_F)
    JOHTO_DEX(NIDORINA)
    JOHTO_DEX(NIDOQUEEN)
    JOHTO_DEX(NIDORAN_M)
    JOHTO_DEX(NIDORINO)
    JOHTO_DEX(NIDOKING)
#endif
#if P_FAMILY_CLEFAIRY
    JOHTO_DEX(CLEFAIRY)
    JOHTO_DEX(CLEFABLE)
#endif
#if P_FAMILY_VULPIX
    JOHTO_DEX(VULPIX)
    JOHTO_DEX(NINETALES)
#endif
#if P_FAMILY_JIGGLYPUFF
    JOHTO_DEX(JIGGLYPUFF)
    JOHTO_DEX(WIGGLYTUFF)
#endif
#if P_FAMILY_ZUBAT
    JOHTO_DEX(ZUBAT)
    JOHTO_DEX(GOLBAT)
#endif
#if P_FAMILY_ODDISH
    JOHTO_DEX(ODDISH)
    JOHTO_DEX(GLOOM)
    JOHTO_DEX(VILEPLUME)
#endif
#if P_FAMILY_PARAS
    JOHTO_DEX(PARAS)
    JOHTO_DEX(PARASECT)
#endif
#if P_FAMILY_VENONAT
    JOHTO_DEX(VENONAT)
    JOHTO_DEX(VENOMOTH)
#endif
#if P_FAMILY_DIGLETT
    JOHTO_DEX(DIGLETT)
    JOHTO_DEX(DUGTRIO)
#endif
#if P_FAMILY_MEOWTH
    JOHTO_DEX(MEOWTH)
    JOHTO_DEX(PERSIAN)
#endif
#if P_FAMILY_PSYDUCK
    JOHTO_DEX(PSYDUCK)
    JOHTO_DEX(GOLDUCK)
#endif
#if P_FAMILY_MANKEY
    JOHTO_DEX(MANKEY)
    JOHTO_DEX(PRIMEAPE)
#endif
#if P_FAMILY_GROWLITHE
    JOHTO_DEX(GROWLITHE)
    JOHTO_DEX(ARCANINE)
#endif
#if P_FAMILY_POLIWAG
    JOHTO_DEX(POLIWAG)
    JOHTO_DEX(POLIWHIRL)
    JOHTO_DEX(POLIWRATH)
#endif
#if P_FAMILY_ABRA
    JOHTO_DEX(ABRA)
    JOHTO_DEX(KADABRA)
    JOHTO_DEX(ALAKAZAM)
#endif
#if P_FAMILY_MACHOP
    JOHTO_DEX(MACHOP)
    JOHTO_DEX(MACHOKE)
    JOHTO_DEX(MACHAMP)
#endif
#if P_FAMILY_BELLSPROUT
    JOHTO_DEX(BELLSPROUT)
    JOHTO_DEX(WEEPINBELL)
    JOHTO_DEX(VICTREEBEL)
#endif
#if P_FAMILY_TENTACOOL
    JOHTO_DEX(TENTACOOL)
    JOHTO_DEX(TENTACRUEL)
#endif
#if P_FAMILY_GEODUDE
    JOHTO_DEX(GEODUDE)
    JOHTO_DEX(GRAVELER)
    JOHTO_DEX(GOLEM)
#endif
#if P_FAMILY_PONYTA
    JOHTO_DEX(PONYTA)
    JOHTO_DEX(RAPIDASH)
#endif
#if P_FAMILY_SLOWPOKE
    JOHTO_DEX(SLOWPOKE)
    JOHTO_DEX(SLOWBRO)
#endif
#if P_FAMILY_MAGNEMITE
    JOHTO_DEX(MAGNEMITE)
    JOHTO_DEX(MAGNETON)
#endif
#if P_FAMILY_FARFETCHD
    JOHTO_DEX(FARFETCHD)
#endif
#if P_FAMILY_DODUO
    JOHTO_DEX(DODUO)
    JOHTO_DEX(DODRIO)
#endif
#if P_FAMILY_SEEL
    JOHTO_DEX(SEEL)
    JOHTO_DEX(DEWGONG)
#endif
#if P_FAMILY_GRIMER
    JOHTO_DEX(GRIMER)
    JOHTO_DEX(MUK)
#endif
#if P_FAMILY_SHELLDER
    JOHTO_DEX(SHELLDER)
    JOHTO_DEX(CLOYSTER)
#endif
#if P_FAMILY_GASTLY
    JOHTO_DEX(GASTLY)
    JOHTO_DEX(HAUNTER)
    JOHTO_DEX(GENGAR)
#endif
#if P_FAMILY_ONIX
    JOHTO_DEX(ONIX)
#endif
#if P_FAMILY_DROWZEE
    JOHTO_DEX(DROWZEE)
    JOHTO_DEX(HYPNO)
#endif
#if P_FAMILY_KRABBY
    JOHTO_DEX(KRABBY)
    JOHTO_DEX(KINGLER)
#endif
#if P_FAMILY_VOLTORB
    JOHTO_DEX(VOLTORB)
    JOHTO_DEX(ELECTRODE)
#endif
#if P_FAMILY_EXEGGCUTE
    JOHTO_DEX(EXEGGCUTE)
    JOHTO_DEX(EXEGGUTOR)
#endif
#if P_FAMILY_CUBONE
    JOHTO_DEX(CUBONE)
    JOHTO_DEX(MAROWAK)
#endif
#if P_FAMILY_HITMONS
    JOHTO_DEX(HITMONLEE)
    JOHTO_DEX(HITMONCHAN)
#endif
#if P_FAMILY_LICKITUNG
    JOHTO_DEX(LICKITUNG)
#endif
#if P_FAMILY_KOFFING
    JOHTO_DEX(KOFFING)
    JOHTO_DEX(WEEZING)
#endif
#if P_FAMILY_RHYHORN
    JOHTO_DEX(RHYHORN)
    JOHTO_DEX(RHYDON)
#endif
#if P_FAMILY_CHANSEY
    JOHTO_DEX(CHANSEY)
#endif
#if P_FAMILY_TANGELA
    JOHTO_DEX(TANGELA)
#endif
#if P_FAMILY_KANGASKHAN
    JOHTO_DEX(KANGASKHAN)
#endif
#if P_FAMILY_HORSEA
    JOHTO_DEX(HORSEA)
    JOHTO_DEX(SEADRA)
#endif
#if P_FAMILY_GOLDEEN
    JOHTO_DEX(GOLDEEN)
    JOHTO_DEX(SEAKING)
#endif
#if P_FAMILY_STARYU
    JOHTO_DEX(STARYU)
    JOHTO_DEX(STARMIE)
#endif
#if P_FAMILY_MR_MIME
    JOHTO_DEX(MR_MIME)
#endif
#if P_FAMILY_SCYTHER
    JOHTO_DEX(SCYTHER)
#endif
#if P_FAMILY_JYNX
    JOHTO_DEX(JYNX)
#endif
#if P_FAMILY_ELECTABUZZ
    JOHTO_DEX(ELECTABUZZ)
#endif
#if P_FAMILY_MAGMAR
    JOHTO_DEX(MAGMAR)
#endif
#if P_FAMILY_PINSIR
    JOHTO_DEX(PINSIR)
#endif
#if P_FAMILY_TAUROS
    JOHTO_DEX(TAUROS)
#endif
#if P_FAMILY_MAGIKARP
    JOHTO_DEX(MAGIKARP)
    JOHTO_DEX(GYARADOS)
#endif
#if P_FAMILY_LAPRAS
    JOHTO_DEX(LAPRAS)
#endif
#if P_FAMILY_DITTO
    JOHTO_DEX(DITTO)
#endif
#if P_FAMILY_EEVEE
    JOHTO_DEX(EEVEE)
    JOHTO_DEX(VAPOREON)
    JOHTO_DEX(JOLTEON)
    JOHTO_DEX(FLAREON)
#endif
#if P_FAMILY_PORYGON
    JOHTO_DEX(PORYGON)
#endif
#if P_FAMILY_OMANYTE
    JOHTO_DEX(OMANYTE)
    JOHTO_DEX(OMASTAR)
#endif
#if P_FAMILY_KABUTO
    JOHTO_DEX(KABUTO)
    JOHTO_DEX(KABUTOPS)
#endif
#if P_FAMILY_AERODACTYL
    JOHTO_DEX(AERODACTYL)
#endif
#if P_FAMILY_SNORLAX
    JOHTO_DEX(SNORLAX)
#endif
#if P_FAMILY_ARTICUNO
    JOHTO_DEX(ARTICUNO)
#endif
#if P_FAMILY_ZAPDOS
    JOHTO_DEX(ZAPDOS)
#endif
#if P_FAMILY_MOLTRES
    JOHTO_DEX(MOLTRES)
#endif
#if P_FAMILY_DRATINI
    JOHTO_DEX(DRATINI)
    JOHTO_DEX(DRAGONAIR)
    JOHTO_DEX(DRAGONITE)
#endif
#if P_FAMILY_MEWTWO
    JOHTO_DEX(MEWTWO)
#endif
#if P_FAMILY_MEW
    JOHTO_DEX(MEW)
#endif
#if P_FAMILY_CHIKORITA
    JOHTO_DEX(CHIKORITA)
    JOHTO_DEX(BAYLEEF)
    JOHTO_DEX(MEGANIUM)
#endif
#if P_FAMILY_CYNDAQUIL
    JOHTO_DEX(CYNDAQUIL)
    JOHTO_DEX(QUILAVA)
    JOHTO_DEX(TYPHLOSION)
#endif
#if P_FAMILY_TOTODILE
    JOHTO_DEX(TOTODILE)
    JOHTO_DEX(CROCONAW)
    JOHTO_DEX(FERALIGATR)
#endif
#if P_FAMILY_SENTRET
    JOHTO_DEX(SENTRET)
    JOHTO_DEX(FURRET)
#endif
#if P_FAMILY_HOOTHOOT
    JOHTO_DEX(HOOTHOOT)
    JOHTO_DEX(NOCTOWL)
#endif
#if P_FAMILY_LEDYBA
    JOHTO_DEX(LEDYBA)
    JOHTO_DEX(LEDIAN)
#endif
#if P_FAMILY_SPINARAK
    JOHTO_DEX(SPINARAK)
    JOHTO_DEX(ARIADOS)
#endif
#if P_FAMILY_ZUBAT && P_GEN_2_CROSS_EVOS
    JOHTO_DEX(CROBAT)
#endif
#if P_FAMILY_CHINCHOU
    JOHTO_DEX(CHINCHOU)
    JOHTO_DEX(LANTURN)
#endif
#if P_FAMILY_PIKACHU && P_GEN_2_CROSS_EVOS
    JOHTO_DEX(PICHU)
#endif
#if P_FAMILY_CLEFAIRY && P_GEN_2_CROSS_EVOS
    JOHTO_DEX(CLEFFA)
#endif
#if P_FAMILY_JIGGLYPUFF && P_GEN_2_CROSS_EVOS
    JOHTO_DEX(IGGLYBUFF)
#endif
#if P_FAMILY_TOGEPI
    JOHTO_DEX(TOGEPI)
    JOHTO_DEX(TOGETIC)
#endif
#if P_FAMILY_NATU
    JOHTO_DEX(NATU)
    JOHTO_DEX(XATU)
#endif
#if P_FAMILY_MAREEP
    JOHTO_DEX(MAREEP)
    JOHTO_DEX(FLAAFFY)
    JOHTO_DEX(AMPHAROS)
#endif
#if P_FAMILY_ODDISH && P_GEN_2_CROSS_EVOS
    JOHTO_DEX(BELLOSSOM)
#endif
#if P_FAMILY_MARILL
    JOHTO_DEX(MARILL)
    JOHTO_DEX(AZUMARILL)
#endif
#if P_FAMILY_SUDOWOODO
    JOHTO_DEX(SUDOWOODO)
#endif
#if P_FAMILY_POLIWAG && P_GEN_2_CROSS_EVOS
    JOHTO_DEX(POLITOED)
#endif
#if P_FAMILY_HOPPIP
    JOHTO_DEX(HOPPIP)
    JOHTO_DEX(SKIPLOOM)
    JOHTO_DEX(JUMPLUFF)
#endif
#if P_FAMILY_AIPOM
    JOHTO_DEX(AIPOM)
#endif
#if P_FAMILY_SUNKERN
    JOHTO_DEX(SUNKERN)
    JOHTO_DEX(SUNFLORA)
#endif
#if P_FAMILY_YANMA
    JOHTO_DEX(YANMA)
#endif
#if P_FAMILY_WOOPER
    JOHTO_DEX(WOOPER)
    JOHTO_DEX(QUAGSIRE)
#endif
#if P_FAMILY_EEVEE && P_GEN_2_CROSS_EVOS
    JOHTO_DEX(ESPEON)
    JOHTO_DEX(UMBREON)
#endif
#if P_FAMILY_MURKROW
    JOHTO_DEX(MURKROW)
#endif
#if P_FAMILY_SLOWPOKE && P_GEN_2_CROSS_EVOS
    JOHTO_DEX(SLOWKING)
#endif
#if P_FAMILY_MISDREAVUS
    JOHTO_DEX(MISDREAVUS)
#endif
#if P_FAMILY_UNOWN
    JOHTO_DEX(UNOWN)
#endif
#if P_FAMILY_WOBBUFFET
    JOHTO_DEX(WOBBUFFET)
#endif
#if P_FAMILY_GIRAFARIG
    JOHTO_DEX(GIRAFARIG)
#endif
#if P_FAMILY_PINECO
    JOHTO_DEX(PINECO)
    JOHTO_DEX(FORRETRESS)
#endif
#if P_FAMILY_DUNSPARCE
    JOHTO_DEX(DUNSPARCE)
#endif
#if P_FAMILY_GLIGAR
    JOHTO_DEX(GLIGAR)
#endif
#if P_FAMILY_ONIX && P_GEN_2_CROSS_EVOS
    JOHTO_DEX(STEELIX)
#endif
#if P_FAMILY_SNUBBULL
    JOHTO_DEX(SNUBBULL)
    JOHTO_DEX(GRANBULL)
#endif
#if P_FAMILY_QWILFISH
    JOHTO_DEX(QWILFISH)
#endif
#if P_FAMILY_SCYTHER && P_GEN_2_CROSS_EVOS
    JOHTO_DEX(SCIZOR)
#endif
#if P_FAMILY_SHUCKLE
    JOHTO_DEX(SHUCKLE)
#endif
#if P_FAMILY_HERACROSS
    JOHTO_DEX(HERACROSS)
#endif
#if P_FAMILY_SNEASEL
    JOHTO_DEX(SNEASEL)
#endif
#if P_FAMILY_TEDDIURSA
    JOHTO_DEX(TEDDIURSA)
    JOHTO_DEX(URSARING)
#endif
#if P_FAMILY_SLUGMA
    JOHTO_DEX(SLUGMA)
    JOHTO_DEX(MAGCARGO)
#endif
#if P_FAMILY_SWINUB
    JOHTO_DEX(SWINUB)
    JOHTO_DEX(PILOSWINE)
#endif
#if P_FAMILY_CORSOLA
    JOHTO_DEX(CORSOLA)
#endif
#if P_FAMILY_REMORAID
    JOHTO_DEX(REMORAID)
    JOHTO_DEX(OCTILLERY)
#endif
#if P_FAMILY_DELIBIRD
    JOHTO_DEX(DELIBIRD)
#endif
#if P_FAMILY_MANTINE
    JOHTO_DEX(MANTINE)
#endif
#if P_FAMILY_SKARMORY
    JOHTO_DEX(SKARMORY)
#endif
#if P_FAMILY_HOUNDOUR
    JOHTO_DEX(HOUNDOUR)
    JOHTO_DEX(HOUNDOOM)
#endif
#if P_FAMILY_HORSEA && P_GEN_2_CROSS_EVOS
    JOHTO_DEX(KINGDRA)
#endif
#if P_FAMILY_PHANPY
    JOHTO_DEX(PHANPY)
    JOHTO_DEX(DONPHAN)
#endif
#if P_FAMILY_PORYGON && P_GEN_2_CROSS_EVOS
    JOHTO_DEX(PORYGON2)
#endif
#if P_FAMILY_STANTLER
    JOHTO_DEX(STANTLER)
#endif
#if P_FAMILY_SMEARGLE
    JOHTO_DEX(SMEARGLE)
#endif
#if P_FAMILY_HITMONS && P_GEN_2_CROSS_EVOS
    JOHTO_DEX(TYROGUE)
    JOHTO_DEX(HITMONTOP)
#endif
#if P_FAMILY_JYNX && P_GEN_2_CROSS_EVOS
    JOHTO_DEX(SMOOCHUM)
#endif
#if P_FAMILY_ELECTABUZZ && P_GEN_2_CROSS_EVOS
    JOHTO_DEX(ELEKID)
#endif
#if P_FAMILY_MAGMAR && P_GEN_2_CROSS_EVOS
    JOHTO_DEX(MAGBY)
#endif
#if P_FAMILY_MILTANK
    JOHTO_DEX(MILTANK)
#endif
#if P_FAMILY_CHANSEY && P_GEN_2_CROSS_EVOS
    JOHTO_DEX(BLISSEY)
#endif
#if P_FAMILY_RAIKOU
    JOHTO_DEX(RAIKOU)
#endif
#if P_FAMILY_ENTEI
    JOHTO_DEX(ENTEI)
#endif
#if P_FAMILY_SUICUNE
    JOHTO_DEX(SUICUNE)
#endif
#if P_FAMILY_LARVITAR
    JOHTO_DEX(LARVITAR)
    JOHTO_DEX(PUPITAR)
    JOHTO_DEX(TYRANITAR)
#endif
#if P_FAMILY_LUGIA
    JOHTO_DEX(LUGIA)
#endif
#if P_FAMILY_HO_OH
    JOHTO_DEX(HO_OH)
#endif
#if P_FAMILY_CELEBI
    JOHTO_DEX(CELEBI)
#endif
#if P_FAMILY_TREECKO
    JOHTO_DEX(TREECKO)
    JOHTO_DEX(GROVYLE)
    JOHTO_DEX(SCEPTILE)
#endif
#if P_FAMILY_TORCHIC
    JOHTO_DEX(TORCHIC)
    JOHTO_DEX(COMBUSKEN)
    JOHTO_DEX(BLAZIKEN)
#endif
#if P_FAMILY_MUDKIP
    JOHTO_DEX(MUDKIP)
    JOHTO_DEX(MARSHTOMP)
    JOHTO_DEX(SWAMPERT)
#endif
#if P_FAMILY_POOCHYENA
    JOHTO_DEX(POOCHYENA)
    JOHTO_DEX(MIGHTYENA)
#endif
#if P_FAMILY_ZIGZAGOON
    JOHTO_DEX(ZIGZAGOON)
    JOHTO_DEX(LINOONE)
#endif
#if P_FAMILY_WURMPLE
    JOHTO_DEX(WURMPLE)
    JOHTO_DEX(SILCOON)
    JOHTO_DEX(BEAUTIFLY)
    JOHTO_DEX(CASCOON)
    JOHTO_DEX(DUSTOX)
#endif
#if P_FAMILY_LOTAD
    JOHTO_DEX(LOTAD)
    JOHTO_DEX(LOMBRE)
    JOHTO_DEX(LUDICOLO)
#endif
#if P_FAMILY_SEEDOT
    JOHTO_DEX(SEEDOT)
    JOHTO_DEX(NUZLEAF)
    JOHTO_DEX(SHIFTRY)
#endif
#if P_FAMILY_TAILLOW
    JOHTO_DEX(TAILLOW)
    JOHTO_DEX(SWELLOW)
#endif
#if P_FAMILY_WINGULL
    JOHTO_DEX(WINGULL)
    JOHTO_DEX(PELIPPER)
#endif
#if P_FAMILY_RALTS
    JOHTO_DEX(RALTS)
    JOHTO_DEX(KIRLIA)
    JOHTO_DEX(GARDEVOIR)
#endif
#if P_FAMILY_SURSKIT
    JOHTO_DEX(SURSKIT)
    JOHTO_DEX(MASQUERAIN)
#endif
#if P_FAMILY_SHROOMISH
    JOHTO_DEX(SHROOMISH)
    JOHTO_DEX(BRELOOM)
#endif
#if P_FAMILY_SLAKOTH
    JOHTO_DEX(SLAKOTH)
    JOHTO_DEX(VIGOROTH)
    JOHTO_DEX(SLAKING)
#endif
#if P_FAMILY_NINCADA
    JOHTO_DEX(NINCADA)
    JOHTO_DEX(NINJASK)
    JOHTO_DEX(SHEDINJA)
#endif
#if P_FAMILY_WHISMUR
    JOHTO_DEX(WHISMUR)
    JOHTO_DEX(LOUDRED)
    JOHTO_DEX(EXPLOUD)
#endif
#if P_FAMILY_MAKUHITA
    JOHTO_DEX(MAKUHITA)
    JOHTO_DEX(HARIYAMA)
#endif
#if P_FAMILY_MARILL && P_GEN_3_CROSS_EVOS
    JOHTO_DEX(AZURILL)
#endif
#if P_FAMILY_NOSEPASS
    JOHTO_DEX(NOSEPASS)
#endif
#if P_FAMILY_SKITTY
    JOHTO_DEX(SKITTY)
    JOHTO_DEX(DELCATTY)
#endif
#if P_FAMILY_SABLEYE
    JOHTO_DEX(SABLEYE)
#endif
#if P_FAMILY_MAWILE
    JOHTO_DEX(MAWILE)
#endif
#if P_FAMILY_ARON
    JOHTO_DEX(ARON)
    JOHTO_DEX(LAIRON)
    JOHTO_DEX(AGGRON)
#endif
#if P_FAMILY_MEDITITE
    JOHTO_DEX(MEDITITE)
    JOHTO_DEX(MEDICHAM)
#endif
#if P_FAMILY_ELECTRIKE
    JOHTO_DEX(ELECTRIKE)
    JOHTO_DEX(MANECTRIC)
#endif
#if P_FAMILY_PLUSLE
    JOHTO_DEX(PLUSLE)
#endif
#if P_FAMILY_MINUN
    JOHTO_DEX(MINUN)
#endif
#if P_FAMILY_VOLBEAT_ILLUMISE
    JOHTO_DEX(VOLBEAT)
    JOHTO_DEX(ILLUMISE)
#endif
#if P_FAMILY_ROSELIA
    JOHTO_DEX(ROSELIA)
#endif
#if P_FAMILY_GULPIN
    JOHTO_DEX(GULPIN)
    JOHTO_DEX(SWALOT)
#endif
#if P_FAMILY_CARVANHA
    JOHTO_DEX(CARVANHA)
    JOHTO_DEX(SHARPEDO)
#endif
#if P_FAMILY_WAILMER
    JOHTO_DEX(WAILMER)
    JOHTO_DEX(WAILORD)
#endif
#if P_FAMILY_NUMEL
    JOHTO_DEX(NUMEL)
    JOHTO_DEX(CAMERUPT)
#endif
#if P_FAMILY_TORKOAL
    JOHTO_DEX(TORKOAL)
#endif
#if P_FAMILY_SPOINK
    JOHTO_DEX(SPOINK)
    JOHTO_DEX(GRUMPIG)
#endif
#if P_FAMILY_SPINDA
    JOHTO_DEX(SPINDA)
#endif
#if P_FAMILY_TRAPINCH
    JOHTO_DEX(TRAPINCH)
    JOHTO_DEX(VIBRAVA)
    JOHTO_DEX(FLYGON)
#endif
#if P_FAMILY_CACNEA
    JOHTO_DEX(CACNEA)
    JOHTO_DEX(CACTURNE)
#endif
#if P_FAMILY_SWABLU
    JOHTO_DEX(SWABLU)
    JOHTO_DEX(ALTARIA)
#endif
#if P_FAMILY_ZANGOOSE
    JOHTO_DEX(ZANGOOSE)
#endif
#if P_FAMILY_SEVIPER
    JOHTO_DEX(SEVIPER)
#endif
#if P_FAMILY_LUNATONE
    JOHTO_DEX(LUNATONE)
#endif
#if P_FAMILY_SOLROCK
    JOHTO_DEX(SOLROCK)
#endif
#if P_FAMILY_BARBOACH
    JOHTO_DEX(BARBOACH)
    JOHTO_DEX(WHISCASH)
#endif
#if P_FAMILY_CORPHISH
    JOHTO_DEX(CORPHISH)
    JOHTO_DEX(CRAWDAUNT)
#endif
#if P_FAMILY_BALTOY
    JOHTO_DEX(BALTOY)
    JOHTO_DEX(CLAYDOL)
#endif
#if P_FAMILY_LILEEP
    JOHTO_DEX(LILEEP)
    JOHTO_DEX(CRADILY)
#endif
#if P_FAMILY_ANORITH
    JOHTO_DEX(ANORITH)
    JOHTO_DEX(ARMALDO)
#endif
#if P_FAMILY_FEEBAS
    JOHTO_DEX(FEEBAS)
    JOHTO_DEX(MILOTIC)
#endif
#if P_FAMILY_CASTFORM
    JOHTO_DEX(CASTFORM)
#endif
#if P_FAMILY_KECLEON
    JOHTO_DEX(KECLEON)
#endif
#if P_FAMILY_SHUPPET
    JOHTO_DEX(SHUPPET)
    JOHTO_DEX(BANETTE)
#endif
#if P_FAMILY_DUSKULL
    JOHTO_DEX(DUSKULL)
    JOHTO_DEX(DUSCLOPS)
#endif
#if P_FAMILY_TROPIUS
    JOHTO_DEX(TROPIUS)
#endif
#if P_FAMILY_CHIMECHO
    JOHTO_DEX(CHIMECHO)
#endif
#if P_FAMILY_ABSOL
    JOHTO_DEX(ABSOL)
#endif
#if P_FAMILY_WOBBUFFET && P_GEN_3_CROSS_EVOS
    JOHTO_DEX(WYNAUT)
#endif
#if P_FAMILY_SNORUNT
    JOHTO_DEX(SNORUNT)
    JOHTO_DEX(GLALIE)
#endif
#if P_FAMILY_SPHEAL
    JOHTO_DEX(SPHEAL)
    JOHTO_DEX(SEALEO)
    JOHTO_DEX(WALREIN)
#endif
#if P_FAMILY_CLAMPERL
    JOHTO_DEX(CLAMPERL)
    JOHTO_DEX(HUNTAIL)
    JOHTO_DEX(GOREBYSS)
#endif
#if P_FAMILY_RELICANTH
    JOHTO_DEX(RELICANTH)
#endif
#if P_FAMILY_LUVDISC
    JOHTO_DEX(LUVDISC)
#endif
#if P_FAMILY_BAGON
    JOHTO_DEX(BAGON)
    JOHTO_DEX(SHELGON)
    JOHTO_DEX(SALAMENCE)
#endif
#if P_FAMILY_BELDUM
    JOHTO_DEX(BELDUM)
    JOHTO_DEX(METANG)
    JOHTO_DEX(METAGROSS)
#endif
#if P_FAMILY_REGIROCK
    JOHTO_DEX(REGIROCK)
#endif
#if P_FAMILY_REGICE
    JOHTO_DEX(REGICE)
#endif
#if P_FAMILY_REGISTEEL
    JOHTO_DEX(REGISTEEL)
#endif
#if P_FAMILY_LATIAS
    JOHTO_DEX(LATIAS)
#endif
#if P_FAMILY_LATIOS
    JOHTO_DEX(LATIOS)
#endif
#if P_FAMILY_KYOGRE
    JOHTO_DEX(KYOGRE)
#endif
#if P_FAMILY_GROUDON
    JOHTO_DEX(GROUDON)
#endif
#if P_FAMILY_RAYQUAZA
    JOHTO_DEX(RAYQUAZA)
#endif
#if P_FAMILY_JIRACHI
    JOHTO_DEX(JIRACHI)
#endif
#if P_FAMILY_DEOXYS
    JOHTO_DEX(DEOXYS)
#endif
#if P_FAMILY_TURTWIG
    JOHTO_DEX(TURTWIG)
    JOHTO_DEX(GROTLE)
    JOHTO_DEX(TORTERRA)
#endif
#if P_FAMILY_CHIMCHAR
    JOHTO_DEX(CHIMCHAR)
    JOHTO_DEX(MONFERNO)
    JOHTO_DEX(INFERNAPE)
#endif
#if P_FAMILY_PIPLUP
    JOHTO_DEX(PIPLUP)
    JOHTO_DEX(PRINPLUP)
    JOHTO_DEX(EMPOLEON)
#endif
#if P_FAMILY_STARLY
    JOHTO_DEX(STARLY)
    JOHTO_DEX(STARAVIA)
    JOHTO_DEX(STARAPTOR)
#endif
#if P_FAMILY_BIDOOF
    JOHTO_DEX(BIDOOF)
    JOHTO_DEX(BIBAREL)
#endif
#if P_FAMILY_KRICKETOT
    JOHTO_DEX(KRICKETOT)
    JOHTO_DEX(KRICKETUNE)
#endif
#if P_FAMILY_SHINX
    JOHTO_DEX(SHINX)
    JOHTO_DEX(LUXIO)
    JOHTO_DEX(LUXRAY)
#endif
#if P_FAMILY_ROSELIA && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(BUDEW)
    JOHTO_DEX(ROSERADE)
#endif
#if P_FAMILY_CRANIDOS
    JOHTO_DEX(CRANIDOS)
    JOHTO_DEX(RAMPARDOS)
#endif
#if P_FAMILY_SHIELDON
    JOHTO_DEX(SHIELDON)
    JOHTO_DEX(BASTIODON)
#endif
#if P_FAMILY_BURMY
    JOHTO_DEX(BURMY)
    JOHTO_DEX(WORMADAM)
    JOHTO_DEX(MOTHIM)
#endif
#if P_FAMILY_COMBEE
    JOHTO_DEX(COMBEE)
    JOHTO_DEX(VESPIQUEN)
#endif
#if P_FAMILY_PACHIRISU
    JOHTO_DEX(PACHIRISU)
#endif
#if P_FAMILY_BUIZEL
    JOHTO_DEX(BUIZEL)
    JOHTO_DEX(FLOATZEL)
#endif
#if P_FAMILY_CHERUBI
    JOHTO_DEX(CHERUBI)
    JOHTO_DEX(CHERRIM)
#endif
#if P_FAMILY_SHELLOS
    JOHTO_DEX(SHELLOS)
    JOHTO_DEX(GASTRODON)
#endif
#if P_FAMILY_AIPOM && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(AMBIPOM)
#endif
#if P_FAMILY_DRIFLOON
    JOHTO_DEX(DRIFLOON)
    JOHTO_DEX(DRIFBLIM)
#endif
#if P_FAMILY_BUNEARY
    JOHTO_DEX(BUNEARY)
    JOHTO_DEX(LOPUNNY)
#endif
#if P_FAMILY_MISDREAVUS && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(MISMAGIUS)
#endif
#if P_FAMILY_MURKROW && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(HONCHKROW)
#endif
#if P_FAMILY_GLAMEOW
    JOHTO_DEX(GLAMEOW)
    JOHTO_DEX(PURUGLY)
#endif
#if P_FAMILY_CHIMECHO && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(CHINGLING)
#endif
#if P_FAMILY_STUNKY
    JOHTO_DEX(STUNKY)
    JOHTO_DEX(SKUNTANK)
#endif
#if P_FAMILY_BRONZOR
    JOHTO_DEX(BRONZOR)
    JOHTO_DEX(BRONZONG)
#endif
#if P_FAMILY_SUDOWOODO && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(BONSLY)
#endif
#if P_FAMILY_MR_MIME && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(MIME_JR)
#endif
#if P_FAMILY_CHANSEY && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(HAPPINY)
#endif
#if P_FAMILY_CHATOT
    JOHTO_DEX(CHATOT)
#endif
#if P_FAMILY_SPIRITOMB
    JOHTO_DEX(SPIRITOMB)
#endif
#if P_FAMILY_GIBLE
    JOHTO_DEX(GIBLE)
    JOHTO_DEX(GABITE)
    JOHTO_DEX(GARCHOMP)
#endif
#if P_FAMILY_SNORLAX && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(MUNCHLAX)
#endif
#if P_FAMILY_RIOLU
    JOHTO_DEX(RIOLU)
    JOHTO_DEX(LUCARIO)
#endif
#if P_FAMILY_HIPPOPOTAS
    JOHTO_DEX(HIPPOPOTAS)
    JOHTO_DEX(HIPPOWDON)
#endif
#if P_FAMILY_SKORUPI
    JOHTO_DEX(SKORUPI)
    JOHTO_DEX(DRAPION)
#endif
#if P_FAMILY_CROAGUNK
    JOHTO_DEX(CROAGUNK)
    JOHTO_DEX(TOXICROAK)
#endif
#if P_FAMILY_CARNIVINE
    JOHTO_DEX(CARNIVINE)
#endif
#if P_FAMILY_FINNEON
    JOHTO_DEX(FINNEON)
    JOHTO_DEX(LUMINEON)
#endif
#if P_FAMILY_MANTINE && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(MANTYKE)
#endif
#if P_FAMILY_SNOVER
    JOHTO_DEX(SNOVER)
    JOHTO_DEX(ABOMASNOW)
#endif
#if P_FAMILY_SNEASEL && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(WEAVILE)
#endif
#if P_FAMILY_MAGNEMITE && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(MAGNEZONE)
#endif
#if P_FAMILY_LICKITUNG && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(LICKILICKY)
#endif
#if P_FAMILY_RHYHORN && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(RHYPERIOR)
#endif
#if P_FAMILY_TANGELA && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(TANGROWTH)
#endif
#if P_FAMILY_ELECTABUZZ && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(ELECTIVIRE)
#endif
#if P_FAMILY_MAGMAR && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(MAGMORTAR)
#endif
#if P_FAMILY_TOGEPI && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(TOGEKISS)
#endif
#if P_FAMILY_YANMA && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(YANMEGA)
#endif
#if P_FAMILY_EEVEE && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(LEAFEON)
    JOHTO_DEX(GLACEON)
#endif
#if P_FAMILY_GLIGAR && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(GLISCOR)
#endif
#if P_FAMILY_SWINUB && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(MAMOSWINE)
#endif
#if P_FAMILY_PORYGON && P_GEN_2_CROSS_EVOS && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(PORYGON_Z)
#endif
#if P_FAMILY_RALTS && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(GALLADE)
#endif
#if P_FAMILY_NOSEPASS && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(PROBOPASS)
#endif
#if P_FAMILY_DUSKULL && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(DUSKNOIR)
#endif
#if P_FAMILY_SNORUNT && P_GEN_4_CROSS_EVOS
    JOHTO_DEX(FROSLASS)
#endif
#if P_FAMILY_ROTOM
    JOHTO_DEX(ROTOM)
#endif
#if P_FAMILY_UXIE
    JOHTO_DEX(UXIE)
#endif
#if P_FAMILY_MESPRIT
    JOHTO_DEX(MESPRIT)
#endif
#if P_FAMILY_AZELF
    JOHTO_DEX(AZELF)
#endif
#if P_FAMILY_DIALGA
    JOHTO_DEX(DIALGA)
#endif
#if P_FAMILY_PALKIA
    JOHTO_DEX(PALKIA)
#endif
#if P_FAMILY_HEATRAN
    JOHTO_DEX(HEATRAN)
#endif
#if P_FAMILY_REGIGIGAS
    JOHTO_DEX(REGIGIGAS)
#endif
#if P_FAMILY_GIRATINA
    JOHTO_DEX(GIRATINA)
#endif
#if P_FAMILY_CRESSELIA
    JOHTO_DEX(CRESSELIA)
#endif
#if P_FAMILY_MANAPHY
    JOHTO_DEX(PHIONE)
    JOHTO_DEX(MANAPHY)
#endif
#if P_FAMILY_DARKRAI
    JOHTO_DEX(DARKRAI)
#endif
#if P_FAMILY_SHAYMIN
    JOHTO_DEX(SHAYMIN)
#endif
#if P_FAMILY_ARCEUS
    JOHTO_DEX(ARCEUS)
#endif
#if P_FAMILY_VICTINI
    JOHTO_DEX(VICTINI)
#endif
#if P_FAMILY_SNIVY
    JOHTO_DEX(SNIVY)
    JOHTO_DEX(SERVINE)
    JOHTO_DEX(SERPERIOR)
#endif
#if P_FAMILY_TEPIG
    JOHTO_DEX(TEPIG)
    JOHTO_DEX(PIGNITE)
    JOHTO_DEX(EMBOAR)
#endif
#if P_FAMILY_OSHAWOTT
    JOHTO_DEX(OSHAWOTT)
    JOHTO_DEX(DEWOTT)
    JOHTO_DEX(SAMUROTT)
#endif
#if P_FAMILY_PATRAT
    JOHTO_DEX(PATRAT)
    JOHTO_DEX(WATCHOG)
#endif
#if P_FAMILY_LILLIPUP
    JOHTO_DEX(LILLIPUP)
    JOHTO_DEX(HERDIER)
    JOHTO_DEX(STOUTLAND)
#endif
#if P_FAMILY_PURRLOIN
    JOHTO_DEX(PURRLOIN)
    JOHTO_DEX(LIEPARD)
#endif
#if P_FAMILY_PANSAGE
    JOHTO_DEX(PANSAGE)
    JOHTO_DEX(SIMISAGE)
#endif
#if P_FAMILY_PANSEAR
    JOHTO_DEX(PANSEAR)
    JOHTO_DEX(SIMISEAR)
#endif
#if P_FAMILY_PANPOUR
    JOHTO_DEX(PANPOUR)
    JOHTO_DEX(SIMIPOUR)
#endif
#if P_FAMILY_MUNNA
    JOHTO_DEX(MUNNA)
    JOHTO_DEX(MUSHARNA)
#endif
#if P_FAMILY_PIDOVE
    JOHTO_DEX(PIDOVE)
    JOHTO_DEX(TRANQUILL)
    JOHTO_DEX(UNFEZANT)
#endif
#if P_FAMILY_BLITZLE
    JOHTO_DEX(BLITZLE)
    JOHTO_DEX(ZEBSTRIKA)
#endif
#if P_FAMILY_ROGGENROLA
    JOHTO_DEX(ROGGENROLA)
    JOHTO_DEX(BOLDORE)
    JOHTO_DEX(GIGALITH)
#endif
#if P_FAMILY_WOOBAT
    JOHTO_DEX(WOOBAT)
    JOHTO_DEX(SWOOBAT)
#endif
#if P_FAMILY_DRILBUR
    JOHTO_DEX(DRILBUR)
    JOHTO_DEX(EXCADRILL)
#endif
#if P_FAMILY_AUDINO
    JOHTO_DEX(AUDINO)
#endif
#if P_FAMILY_TIMBURR
    JOHTO_DEX(TIMBURR)
    JOHTO_DEX(GURDURR)
    JOHTO_DEX(CONKELDURR)
#endif
#if P_FAMILY_TYMPOLE
    JOHTO_DEX(TYMPOLE)
    JOHTO_DEX(PALPITOAD)
    JOHTO_DEX(SEISMITOAD)
#endif
#if P_FAMILY_THROH
    JOHTO_DEX(THROH)
#endif
#if P_FAMILY_SAWK
    JOHTO_DEX(SAWK)
#endif
#if P_FAMILY_SEWADDLE
    JOHTO_DEX(SEWADDLE)
    JOHTO_DEX(SWADLOON)
    JOHTO_DEX(LEAVANNY)
#endif
#if P_FAMILY_VENIPEDE
    JOHTO_DEX(VENIPEDE)
    JOHTO_DEX(WHIRLIPEDE)
    JOHTO_DEX(SCOLIPEDE)
#endif
#if P_FAMILY_COTTONEE
    JOHTO_DEX(COTTONEE)
    JOHTO_DEX(WHIMSICOTT)
#endif
#if P_FAMILY_PETILIL
    JOHTO_DEX(PETILIL)
    JOHTO_DEX(LILLIGANT)
#endif
#if P_FAMILY_BASCULIN
    JOHTO_DEX(BASCULIN)
#endif
#if P_FAMILY_SANDILE
    JOHTO_DEX(SANDILE)
    JOHTO_DEX(KROKOROK)
    JOHTO_DEX(KROOKODILE)
#endif
#if P_FAMILY_DARUMAKA
    JOHTO_DEX(DARUMAKA)
    JOHTO_DEX(DARMANITAN)
#endif
#if P_FAMILY_MARACTUS
    JOHTO_DEX(MARACTUS)
#endif
#if P_FAMILY_DWEBBLE
    JOHTO_DEX(DWEBBLE)
    JOHTO_DEX(CRUSTLE)
#endif
#if P_FAMILY_SCRAGGY
    JOHTO_DEX(SCRAGGY)
    JOHTO_DEX(SCRAFTY)
#endif
#if P_FAMILY_SIGILYPH
    JOHTO_DEX(SIGILYPH)
#endif
#if P_FAMILY_YAMASK
    JOHTO_DEX(YAMASK)
    JOHTO_DEX(COFAGRIGUS)
#endif
#if P_FAMILY_TIRTOUGA
    JOHTO_DEX(TIRTOUGA)
    JOHTO_DEX(CARRACOSTA)
#endif
#if P_FAMILY_ARCHEN
    JOHTO_DEX(ARCHEN)
    JOHTO_DEX(ARCHEOPS)
#endif
#if P_FAMILY_TRUBBISH
    JOHTO_DEX(TRUBBISH)
    JOHTO_DEX(GARBODOR)
#endif
#if P_FAMILY_ZORUA
    JOHTO_DEX(ZORUA)
    JOHTO_DEX(ZOROARK)
#endif
#if P_FAMILY_MINCCINO
    JOHTO_DEX(MINCCINO)
    JOHTO_DEX(CINCCINO)
#endif
#if P_FAMILY_GOTHITA
    JOHTO_DEX(GOTHITA)
    JOHTO_DEX(GOTHORITA)
    JOHTO_DEX(GOTHITELLE)
#endif
#if P_FAMILY_SOLOSIS
    JOHTO_DEX(SOLOSIS)
    JOHTO_DEX(DUOSION)
    JOHTO_DEX(REUNICLUS)
#endif
#if P_FAMILY_DUCKLETT
    JOHTO_DEX(DUCKLETT)
    JOHTO_DEX(SWANNA)
#endif
#if P_FAMILY_VANILLITE
    JOHTO_DEX(VANILLITE)
    JOHTO_DEX(VANILLISH)
    JOHTO_DEX(VANILLUXE)
#endif
#if P_FAMILY_DEERLING
    JOHTO_DEX(DEERLING)
    JOHTO_DEX(SAWSBUCK)
#endif
#if P_FAMILY_EMOLGA
    JOHTO_DEX(EMOLGA)
#endif
#if P_FAMILY_KARRABLAST
    JOHTO_DEX(KARRABLAST)
    JOHTO_DEX(ESCAVALIER)
#endif
#if P_FAMILY_FOONGUS
    JOHTO_DEX(FOONGUS)
    JOHTO_DEX(AMOONGUSS)
#endif
#if P_FAMILY_FRILLISH
    JOHTO_DEX(FRILLISH)
    JOHTO_DEX(JELLICENT)
#endif
#if P_FAMILY_ALOMOMOLA
    JOHTO_DEX(ALOMOMOLA)
#endif
#if P_FAMILY_JOLTIK
    JOHTO_DEX(JOLTIK)
    JOHTO_DEX(GALVANTULA)
#endif
#if P_FAMILY_FERROSEED
    JOHTO_DEX(FERROSEED)
    JOHTO_DEX(FERROTHORN)
#endif
#if P_FAMILY_KLINK
    JOHTO_DEX(KLINK)
    JOHTO_DEX(KLANG)
    JOHTO_DEX(KLINKLANG)
#endif
#if P_FAMILY_TYNAMO
    JOHTO_DEX(TYNAMO)
    JOHTO_DEX(EELEKTRIK)
    JOHTO_DEX(EELEKTROSS)
#endif
#if P_FAMILY_ELGYEM
    JOHTO_DEX(ELGYEM)
    JOHTO_DEX(BEHEEYEM)
#endif
#if P_FAMILY_LITWICK
    JOHTO_DEX(LITWICK)
    JOHTO_DEX(LAMPENT)
    JOHTO_DEX(CHANDELURE)
#endif
#if P_FAMILY_AXEW
    JOHTO_DEX(AXEW)
    JOHTO_DEX(FRAXURE)
    JOHTO_DEX(HAXORUS)
#endif
#if P_FAMILY_CUBCHOO
    JOHTO_DEX(CUBCHOO)
    JOHTO_DEX(BEARTIC)
#endif
#if P_FAMILY_CRYOGONAL
    JOHTO_DEX(CRYOGONAL)
#endif
#if P_FAMILY_SHELMET
    JOHTO_DEX(SHELMET)
    JOHTO_DEX(ACCELGOR)
#endif
#if P_FAMILY_STUNFISK
    JOHTO_DEX(STUNFISK)
#endif
#if P_FAMILY_MIENFOO
    JOHTO_DEX(MIENFOO)
    JOHTO_DEX(MIENSHAO)
#endif
#if P_FAMILY_DRUDDIGON
    JOHTO_DEX(DRUDDIGON)
#endif
#if P_FAMILY_GOLETT
    JOHTO_DEX(GOLETT)
    JOHTO_DEX(GOLURK)
#endif
#if P_FAMILY_PAWNIARD
    JOHTO_DEX(PAWNIARD)
    JOHTO_DEX(BISHARP)
#endif
#if P_FAMILY_BOUFFALANT
    JOHTO_DEX(BOUFFALANT)
#endif
#if P_FAMILY_RUFFLET
    JOHTO_DEX(RUFFLET)
    JOHTO_DEX(BRAVIARY)
#endif
#if P_FAMILY_VULLABY
    JOHTO_DEX(VULLABY)
    JOHTO_DEX(MANDIBUZZ)
#endif
#if P_FAMILY_HEATMOR
    JOHTO_DEX(HEATMOR)
#endif
#if P_FAMILY_DURANT
    JOHTO_DEX(DURANT)
#endif
#if P_FAMILY_DEINO
    JOHTO_DEX(DEINO)
    JOHTO_DEX(ZWEILOUS)
    JOHTO_DEX(HYDREIGON)
#endif
#if P_FAMILY_LARVESTA
    JOHTO_DEX(LARVESTA)
    JOHTO_DEX(VOLCARONA)
#endif
#if P_FAMILY_COBALION
    JOHTO_DEX(COBALION)
#endif
#if P_FAMILY_TERRAKION
    JOHTO_DEX(TERRAKION)
#endif
#if P_FAMILY_VIRIZION
    JOHTO_DEX(VIRIZION)
#endif
#if P_FAMILY_TORNADUS
    JOHTO_DEX(TORNADUS)
#endif
#if P_FAMILY_THUNDURUS
    JOHTO_DEX(THUNDURUS)
#endif
#if P_FAMILY_RESHIRAM
    JOHTO_DEX(RESHIRAM)
#endif
#if P_FAMILY_ZEKROM
    JOHTO_DEX(ZEKROM)
#endif
#if P_FAMILY_LANDORUS
    JOHTO_DEX(LANDORUS)
#endif
#if P_FAMILY_KYUREM
    JOHTO_DEX(KYUREM)
#endif
#if P_FAMILY_KELDEO
    JOHTO_DEX(KELDEO)
#endif
#if P_FAMILY_MELOETTA
    JOHTO_DEX(MELOETTA)
#endif
#if P_FAMILY_GENESECT
    JOHTO_DEX(GENESECT)
#endif
#if P_FAMILY_CHESPIN
    JOHTO_DEX(CHESPIN)
    JOHTO_DEX(QUILLADIN)
    JOHTO_DEX(CHESNAUGHT)
#endif
#if P_FAMILY_FENNEKIN
    JOHTO_DEX(FENNEKIN)
    JOHTO_DEX(BRAIXEN)
    JOHTO_DEX(DELPHOX)
#endif
#if P_FAMILY_FROAKIE
    JOHTO_DEX(FROAKIE)
    JOHTO_DEX(FROGADIER)
    JOHTO_DEX(GRENINJA)
#endif
#if P_FAMILY_BUNNELBY
    JOHTO_DEX(BUNNELBY)
    JOHTO_DEX(DIGGERSBY)
#endif
#if P_FAMILY_FLETCHLING
    JOHTO_DEX(FLETCHLING)
    JOHTO_DEX(FLETCHINDER)
    JOHTO_DEX(TALONFLAME)
#endif
#if P_FAMILY_SCATTERBUG
    JOHTO_DEX(SCATTERBUG)
    JOHTO_DEX(SPEWPA)
    JOHTO_DEX(VIVILLON)
#endif
#if P_FAMILY_LITLEO
    JOHTO_DEX(LITLEO)
    JOHTO_DEX(PYROAR)
#endif
#if P_FAMILY_FLABEBE
    JOHTO_DEX(FLABEBE)
    JOHTO_DEX(FLOETTE)
    JOHTO_DEX(FLORGES)
#endif
#if P_FAMILY_SKIDDO
    JOHTO_DEX(SKIDDO)
    JOHTO_DEX(GOGOAT)
#endif
#if P_FAMILY_PANCHAM
    JOHTO_DEX(PANCHAM)
    JOHTO_DEX(PANGORO)
#endif
#if P_FAMILY_FURFROU
    JOHTO_DEX(FURFROU)
#endif
#if P_FAMILY_ESPURR
    JOHTO_DEX(ESPURR)
    JOHTO_DEX(MEOWSTIC)
#endif
#if P_FAMILY_HONEDGE
    JOHTO_DEX(HONEDGE)
    JOHTO_DEX(DOUBLADE)
    JOHTO_DEX(AEGISLASH)
#endif
#if P_FAMILY_SPRITZEE
    JOHTO_DEX(SPRITZEE)
    JOHTO_DEX(AROMATISSE)
#endif
#if P_FAMILY_SWIRLIX
    JOHTO_DEX(SWIRLIX)
    JOHTO_DEX(SLURPUFF)
#endif
#if P_FAMILY_INKAY
    JOHTO_DEX(INKAY)
    JOHTO_DEX(MALAMAR)
#endif
#if P_FAMILY_BINACLE
    JOHTO_DEX(BINACLE)
    JOHTO_DEX(BARBARACLE)
#endif
#if P_FAMILY_SKRELP
    JOHTO_DEX(SKRELP)
    JOHTO_DEX(DRAGALGE)
#endif
#if P_FAMILY_CLAUNCHER
    JOHTO_DEX(CLAUNCHER)
    JOHTO_DEX(CLAWITZER)
#endif
#if P_FAMILY_HELIOPTILE
    JOHTO_DEX(HELIOPTILE)
    JOHTO_DEX(HELIOLISK)
#endif
#if P_FAMILY_TYRUNT
    JOHTO_DEX(TYRUNT)
    JOHTO_DEX(TYRANTRUM)
#endif
#if P_FAMILY_AMAURA
    JOHTO_DEX(AMAURA)
    JOHTO_DEX(AURORUS)
#endif
#if P_FAMILY_EEVEE && P_GEN_6_CROSS_EVOS
    JOHTO_DEX(SYLVEON)
#endif
#if P_FAMILY_HAWLUCHA
    JOHTO_DEX(HAWLUCHA)
#endif
#if P_FAMILY_DEDENNE
    JOHTO_DEX(DEDENNE)
#endif
#if P_FAMILY_CARBINK
    JOHTO_DEX(CARBINK)
#endif
#if P_FAMILY_GOOMY
    JOHTO_DEX(GOOMY)
    JOHTO_DEX(SLIGGOO)
    JOHTO_DEX(GOODRA)
#endif
#if P_FAMILY_KLEFKI
    JOHTO_DEX(KLEFKI)
#endif
#if P_FAMILY_PHANTUMP
    JOHTO_DEX(PHANTUMP)
    JOHTO_DEX(TREVENANT)
#endif
#if P_FAMILY_PUMPKABOO
    JOHTO_DEX(PUMPKABOO)
    JOHTO_DEX(GOURGEIST)
#endif
#if P_FAMILY_BERGMITE
    JOHTO_DEX(BERGMITE)
    JOHTO_DEX(AVALUGG)
#endif
#if P_FAMILY_NOIBAT
    JOHTO_DEX(NOIBAT)
    JOHTO_DEX(NOIVERN)
#endif
#if P_FAMILY_XERNEAS
    JOHTO_DEX(XERNEAS)
#endif
#if P_FAMILY_YVELTAL
    JOHTO_DEX(YVELTAL)
#endif
#if P_FAMILY_ZYGARDE
    JOHTO_DEX(ZYGARDE)
#endif
#if P_FAMILY_DIANCIE
    JOHTO_DEX(DIANCIE)
#endif
#if P_FAMILY_HOOPA
    JOHTO_DEX(HOOPA)
#endif
#if P_FAMILY_VOLCANION
    JOHTO_DEX(VOLCANION)
#endif
#if P_FAMILY_ROWLET
    JOHTO_DEX(ROWLET)
    JOHTO_DEX(DARTRIX)
    JOHTO_DEX(DECIDUEYE)
#endif
#if P_FAMILY_LITTEN
    JOHTO_DEX(LITTEN)
    JOHTO_DEX(TORRACAT)
    JOHTO_DEX(INCINEROAR)
#endif
#if P_FAMILY_POPPLIO
    JOHTO_DEX(POPPLIO)
    JOHTO_DEX(BRIONNE)
    JOHTO_DEX(PRIMARINA)
#endif
#if P_FAMILY_PIKIPEK
    JOHTO_DEX(PIKIPEK)
    JOHTO_DEX(TRUMBEAK)
    JOHTO_DEX(TOUCANNON)
#endif
#if P_FAMILY_YUNGOOS
    JOHTO_DEX(YUNGOOS)
    JOHTO_DEX(GUMSHOOS)
#endif
#if P_FAMILY_GRUBBIN
    JOHTO_DEX(GRUBBIN)
    JOHTO_DEX(CHARJABUG)
    JOHTO_DEX(VIKAVOLT)
#endif
#if P_FAMILY_CRABRAWLER
    JOHTO_DEX(CRABRAWLER)
    JOHTO_DEX(CRABOMINABLE)
#endif
#if P_FAMILY_ORICORIO
    JOHTO_DEX(ORICORIO)
#endif
#if P_FAMILY_CUTIEFLY
    JOHTO_DEX(CUTIEFLY)
    JOHTO_DEX(RIBOMBEE)
#endif
#if P_FAMILY_ROCKRUFF
    JOHTO_DEX(ROCKRUFF)
    JOHTO_DEX(LYCANROC)
#endif
#if P_FAMILY_WISHIWASHI
    JOHTO_DEX(WISHIWASHI)
#endif
#if P_FAMILY_MAREANIE
    JOHTO_DEX(MAREANIE)
    JOHTO_DEX(TOXAPEX)
#endif
#if P_FAMILY_MUDBRAY
    JOHTO_DEX(MUDBRAY)
    JOHTO_DEX(MUDSDALE)
#endif
#if P_FAMILY_DEWPIDER
    JOHTO_DEX(DEWPIDER)
    JOHTO_DEX(ARAQUANID)
#endif
#if P_FAMILY_FOMANTIS
    JOHTO_DEX(FOMANTIS)
    JOHTO_DEX(LURANTIS)
#endif
#if P_FAMILY_MORELULL
    JOHTO_DEX(MORELULL)
    JOHTO_DEX(SHIINOTIC)
#endif
#if P_FAMILY_SALANDIT
    JOHTO_DEX(SALANDIT)
    JOHTO_DEX(SALAZZLE)
#endif
#if P_FAMILY_STUFFUL
    JOHTO_DEX(STUFFUL)
    JOHTO_DEX(BEWEAR)
#endif
#if P_FAMILY_BOUNSWEET
    JOHTO_DEX(BOUNSWEET)
    JOHTO_DEX(STEENEE)
    JOHTO_DEX(TSAREENA)
#endif
#if P_FAMILY_COMFEY
    JOHTO_DEX(COMFEY)
#endif
#if P_FAMILY_ORANGURU
    JOHTO_DEX(ORANGURU)
#endif
#if P_FAMILY_PASSIMIAN
    JOHTO_DEX(PASSIMIAN)
#endif
#if P_FAMILY_WIMPOD
    JOHTO_DEX(WIMPOD)
    JOHTO_DEX(GOLISOPOD)
#endif
#if P_FAMILY_SANDYGAST
    JOHTO_DEX(SANDYGAST)
    JOHTO_DEX(PALOSSAND)
#endif
#if P_FAMILY_PYUKUMUKU
    JOHTO_DEX(PYUKUMUKU)
#endif
#if P_FAMILY_TYPE_NULL
    JOHTO_DEX(TYPE_NULL)
    JOHTO_DEX(SILVALLY)
#endif
#if P_FAMILY_MINIOR
    JOHTO_DEX(MINIOR)
#endif
#if P_FAMILY_KOMALA
    JOHTO_DEX(KOMALA)
#endif
#if P_FAMILY_TURTONATOR
    JOHTO_DEX(TURTONATOR)
#endif
#if P_FAMILY_TOGEDEMARU
    JOHTO_DEX(TOGEDEMARU)
#endif
#if P_FAMILY_MIMIKYU
    JOHTO_DEX(MIMIKYU)
#endif
#if P_FAMILY_BRUXISH
    JOHTO_DEX(BRUXISH)
#endif
#if P_FAMILY_DRAMPA
    JOHTO_DEX(DRAMPA)
#endif
#if P_FAMILY_DHELMISE
    JOHTO_DEX(DHELMISE)
#endif
#if P_FAMILY_JANGMO_O
    JOHTO_DEX(JANGMO_O)
    JOHTO_DEX(HAKAMO_O)
    JOHTO_DEX(KOMMO_O)
#endif
#if P_FAMILY_TAPU_KOKO
    JOHTO_DEX(TAPU_KOKO)
#endif
#if P_FAMILY_TAPU_LELE
    JOHTO_DEX(TAPU_LELE)
#endif
#if P_FAMILY_TAPU_BULU
    JOHTO_DEX(TAPU_BULU)
#endif
#if P_FAMILY_TAPU_FINI
    JOHTO_DEX(TAPU_FINI)
#endif
#if P_FAMILY_COSMOG
    JOHTO_DEX(COSMOG)
    JOHTO_DEX(COSMOEM)
    JOHTO_DEX(SOLGALEO)
    JOHTO_DEX(LUNALA)
#endif
#if P_FAMILY_NIHILEGO
    JOHTO_DEX(NIHILEGO)
#endif
#if P_FAMILY_BUZZWOLE
    JOHTO_DEX(BUZZWOLE)
#endif
#if P_FAMILY_PHEROMOSA
    JOHTO_DEX(PHEROMOSA)
#endif
#if P_FAMILY_XURKITREE
    JOHTO_DEX(XURKITREE)
#endif
#if P_FAMILY_CELESTEELA
    JOHTO_DEX(CELESTEELA)
#endif
#if P_FAMILY_KARTANA
    JOHTO_DEX(KARTANA)
#endif
#if P_FAMILY_GUZZLORD
    JOHTO_DEX(GUZZLORD)
#endif
#if P_FAMILY_NECROZMA
    JOHTO_DEX(NECROZMA)
#endif
#if P_FAMILY_MAGEARNA
    JOHTO_DEX(MAGEARNA)
#endif
#if P_FAMILY_MARSHADOW
    JOHTO_DEX(MARSHADOW)
#endif
#if P_FAMILY_POIPOLE
    JOHTO_DEX(POIPOLE)
    JOHTO_DEX(NAGANADEL)
#endif
#if P_FAMILY_STAKATAKA
    JOHTO_DEX(STAKATAKA)
#endif
#if P_FAMILY_BLACEPHALON
    JOHTO_DEX(BLACEPHALON)
#endif
#if P_FAMILY_ZERAORA
    JOHTO_DEX(ZERAORA)
#endif
#if P_FAMILY_MELTAN
    JOHTO_DEX(MELTAN)
    JOHTO_DEX(MELMETAL)
#endif
#if P_FAMILY_GROOKEY
    JOHTO_DEX(GROOKEY)
    JOHTO_DEX(THWACKEY)
    JOHTO_DEX(RILLABOOM)
#endif
#if P_FAMILY_SCORBUNNY
    JOHTO_DEX(SCORBUNNY)
    JOHTO_DEX(RABOOT)
    JOHTO_DEX(CINDERACE)
#endif
#if P_FAMILY_SOBBLE
    JOHTO_DEX(SOBBLE)
    JOHTO_DEX(DRIZZILE)
    JOHTO_DEX(INTELEON)
#endif
#if P_FAMILY_SKWOVET
    JOHTO_DEX(SKWOVET)
    JOHTO_DEX(GREEDENT)
#endif
#if P_FAMILY_ROOKIDEE
    JOHTO_DEX(ROOKIDEE)
    JOHTO_DEX(CORVISQUIRE)
    JOHTO_DEX(CORVIKNIGHT)
#endif
#if P_FAMILY_BLIPBUG
    JOHTO_DEX(BLIPBUG)
    JOHTO_DEX(DOTTLER)
    JOHTO_DEX(ORBEETLE)
#endif
#if P_FAMILY_NICKIT
    JOHTO_DEX(NICKIT)
    JOHTO_DEX(THIEVUL)
#endif
#if P_FAMILY_GOSSIFLEUR
    JOHTO_DEX(GOSSIFLEUR)
    JOHTO_DEX(ELDEGOSS)
#endif
#if P_FAMILY_WOOLOO
    JOHTO_DEX(WOOLOO)
    JOHTO_DEX(DUBWOOL)
#endif
#if P_FAMILY_CHEWTLE
    JOHTO_DEX(CHEWTLE)
    JOHTO_DEX(DREDNAW)
#endif
#if P_FAMILY_YAMPER
    JOHTO_DEX(YAMPER)
    JOHTO_DEX(BOLTUND)
#endif
#if P_FAMILY_ROLYCOLY
    JOHTO_DEX(ROLYCOLY)
    JOHTO_DEX(CARKOL)
    JOHTO_DEX(COALOSSAL)
#endif
#if P_FAMILY_APPLIN
    JOHTO_DEX(APPLIN)
    JOHTO_DEX(FLAPPLE)
    JOHTO_DEX(APPLETUN)
#endif
#if P_FAMILY_SILICOBRA
    JOHTO_DEX(SILICOBRA)
    JOHTO_DEX(SANDACONDA)
#endif
#if P_FAMILY_CRAMORANT
    JOHTO_DEX(CRAMORANT)
#endif
#if P_FAMILY_ARROKUDA
    JOHTO_DEX(ARROKUDA)
    JOHTO_DEX(BARRASKEWDA)
#endif
#if P_FAMILY_TOXEL
    JOHTO_DEX(TOXEL)
    JOHTO_DEX(TOXTRICITY)
#endif
#if P_FAMILY_SIZZLIPEDE
    JOHTO_DEX(SIZZLIPEDE)
    JOHTO_DEX(CENTISKORCH)
#endif
#if P_FAMILY_CLOBBOPUS
    JOHTO_DEX(CLOBBOPUS)
    JOHTO_DEX(GRAPPLOCT)
#endif
#if P_FAMILY_SINISTEA
    JOHTO_DEX(SINISTEA)
    JOHTO_DEX(POLTEAGEIST)
#endif
#if P_FAMILY_HATENNA
    JOHTO_DEX(HATENNA)
    JOHTO_DEX(HATTREM)
    JOHTO_DEX(HATTERENE)
#endif
#if P_FAMILY_IMPIDIMP
    JOHTO_DEX(IMPIDIMP)
    JOHTO_DEX(MORGREM)
    JOHTO_DEX(GRIMMSNARL)
#endif
#if P_FAMILY_ZIGZAGOON && P_GALARIAN_FORMS
    JOHTO_DEX(OBSTAGOON)
#endif
#if P_FAMILY_MEOWTH && P_GALARIAN_FORMS
    JOHTO_DEX(PERRSERKER)
#endif
#if P_FAMILY_CORSOLA && P_GALARIAN_FORMS
    JOHTO_DEX(CURSOLA)
#endif
#if P_FAMILY_FARFETCHD && P_GALARIAN_FORMS
    JOHTO_DEX(SIRFETCHD)
#endif
#if P_FAMILY_MR_MIME && P_GALARIAN_FORMS
    JOHTO_DEX(MR_RIME)
#endif
#if P_FAMILY_YAMASK && P_GALARIAN_FORMS
    JOHTO_DEX(RUNERIGUS)
#endif
#if P_FAMILY_MILCERY
    JOHTO_DEX(MILCERY)
    JOHTO_DEX(ALCREMIE)
#endif
#if P_FAMILY_FALINKS
    JOHTO_DEX(FALINKS)
#endif
#if P_FAMILY_PINCURCHIN
    JOHTO_DEX(PINCURCHIN)
#endif
#if P_FAMILY_SNOM
    JOHTO_DEX(SNOM)
    JOHTO_DEX(FROSMOTH)
#endif
#if P_FAMILY_STONJOURNER
    JOHTO_DEX(STONJOURNER)
#endif
#if P_FAMILY_EISCUE
    JOHTO_DEX(EISCUE)
#endif
#if P_FAMILY_INDEEDEE
    JOHTO_DEX(INDEEDEE)
#endif
#if P_FAMILY_MORPEKO
    JOHTO_DEX(MORPEKO)
#endif
#if P_FAMILY_CUFANT
    JOHTO_DEX(CUFANT)
    JOHTO_DEX(COPPERAJAH)
#endif
#if P_FAMILY_DRACOZOLT
    JOHTO_DEX(DRACOZOLT)
#endif
#if P_FAMILY_ARCTOZOLT
    JOHTO_DEX(ARCTOZOLT)
#endif
#if P_FAMILY_DRACOVISH
    JOHTO_DEX(DRACOVISH)
#endif
#if P_FAMILY_ARCTOVISH
    JOHTO_DEX(ARCTOVISH)
#endif
#if P_FAMILY_DURALUDON
    JOHTO_DEX(DURALUDON)
#endif
#if P_FAMILY_DREEPY
    JOHTO_DEX(DREEPY)
    JOHTO_DEX(DRAKLOAK)
    JOHTO_DEX(DRAGAPULT)
#endif
#if P_FAMILY_ZACIAN
    JOHTO_DEX(ZACIAN)
#endif
#if P_FAMILY_ZAMAZENTA
    JOHTO_DEX(ZAMAZENTA)
#endif
#if P_FAMILY_ETERNATUS
    JOHTO_DEX(ETERNATUS)
#endif
#if P_FAMILY_KUBFU
    JOHTO_DEX(KUBFU)
    JOHTO_DEX(URSHIFU)
#endif
#if P_FAMILY_ZARUDE
    JOHTO_DEX(ZARUDE)
#endif
#if P_FAMILY_REGIELEKI
    JOHTO_DEX(REGIELEKI)
#endif
#if P_FAMILY_REGIDRAGO
    JOHTO_DEX(REGIDRAGO)
#endif
#if P_FAMILY_GLASTRIER
    JOHTO_DEX(GLASTRIER)
#endif
#if P_FAMILY_SPECTRIER
    JOHTO_DEX(SPECTRIER)
#endif
#if P_FAMILY_CALYREX
    JOHTO_DEX(CALYREX)
#endif
#if P_FAMILY_STANTLER && P_GEN_8_CROSS_EVOS
    JOHTO_DEX(WYRDEER)
#endif
#if P_FAMILY_SCYTHER && P_GEN_8_CROSS_EVOS
    JOHTO_DEX(KLEAVOR)
#endif
#if P_FAMILY_TEDDIURSA && P_GEN_8_CROSS_EVOS
    JOHTO_DEX(URSALUNA)
#endif
#if P_FAMILY_BASCULIN && P_HISUIAN_FORMS
    JOHTO_DEX(BASCULEGION)
#endif
#if P_FAMILY_SNEASEL && P_HISUIAN_FORMS
    JOHTO_DEX(SNEASLER)
#endif
#if P_FAMILY_QWILFISH && P_HISUIAN_FORMS
    JOHTO_DEX(OVERQWIL)
#endif
#if P_FAMILY_ENAMORUS
    JOHTO_DEX(ENAMORUS)
#endif
#if P_FAMILY_SPRIGATITO
    JOHTO_DEX(SPRIGATITO)
    JOHTO_DEX(FLORAGATO)
    JOHTO_DEX(MEOWSCARADA)
#endif
#if P_FAMILY_FUECOCO
    JOHTO_DEX(FUECOCO)
    JOHTO_DEX(CROCALOR)
    JOHTO_DEX(SKELEDIRGE)
#endif
#if P_FAMILY_QUAXLY
    JOHTO_DEX(QUAXLY)
    JOHTO_DEX(QUAXWELL)
    JOHTO_DEX(QUAQUAVAL)
#endif
#if P_FAMILY_LECHONK
    JOHTO_DEX(LECHONK)
    JOHTO_DEX(OINKOLOGNE)
#endif
#if P_FAMILY_TAROUNTULA
    JOHTO_DEX(TAROUNTULA)
    JOHTO_DEX(SPIDOPS)
#endif
#if P_FAMILY_NYMBLE
    JOHTO_DEX(NYMBLE)
    JOHTO_DEX(LOKIX)
#endif
#if P_FAMILY_PAWMI
    JOHTO_DEX(PAWMI)
    JOHTO_DEX(PAWMO)
    JOHTO_DEX(PAWMOT)
#endif
#if P_FAMILY_TANDEMAUS
    JOHTO_DEX(TANDEMAUS)
    JOHTO_DEX(MAUSHOLD)
#endif
#if P_FAMILY_FIDOUGH
    JOHTO_DEX(FIDOUGH)
    JOHTO_DEX(DACHSBUN)
#endif
#if P_FAMILY_SMOLIV
    JOHTO_DEX(SMOLIV)
    JOHTO_DEX(DOLLIV)
    JOHTO_DEX(ARBOLIVA)
#endif
#if P_FAMILY_SQUAWKABILLY
    JOHTO_DEX(SQUAWKABILLY)
#endif
#if P_FAMILY_NACLI
    JOHTO_DEX(NACLI)
    JOHTO_DEX(NACLSTACK)
    JOHTO_DEX(GARGANACL)
#endif
#if P_FAMILY_CHARCADET
    JOHTO_DEX(CHARCADET)
    JOHTO_DEX(ARMAROUGE)
    JOHTO_DEX(CERULEDGE)
#endif
#if P_FAMILY_TADBULB
    JOHTO_DEX(TADBULB)
    JOHTO_DEX(BELLIBOLT)
#endif
#if P_FAMILY_WATTREL
    JOHTO_DEX(WATTREL)
    JOHTO_DEX(KILOWATTREL)
#endif
#if P_FAMILY_MASCHIFF
    JOHTO_DEX(MASCHIFF)
    JOHTO_DEX(MABOSSTIFF)
#endif
#if P_FAMILY_SHROODLE
    JOHTO_DEX(SHROODLE)
    JOHTO_DEX(GRAFAIAI)
#endif
#if P_FAMILY_BRAMBLIN
    JOHTO_DEX(BRAMBLIN)
    JOHTO_DEX(BRAMBLEGHAST)
#endif
#if P_FAMILY_TOEDSCOOL
    JOHTO_DEX(TOEDSCOOL)
    JOHTO_DEX(TOEDSCRUEL)
#endif
#if P_FAMILY_KLAWF
    JOHTO_DEX(KLAWF)
#endif
#if P_FAMILY_CAPSAKID
    JOHTO_DEX(CAPSAKID)
    JOHTO_DEX(SCOVILLAIN)
#endif
#if P_FAMILY_RELLOR
    JOHTO_DEX(RELLOR)
    JOHTO_DEX(RABSCA)
#endif
#if P_FAMILY_FLITTLE
    JOHTO_DEX(FLITTLE)
    JOHTO_DEX(ESPATHRA)
#endif
#if P_FAMILY_TINKATINK
    JOHTO_DEX(TINKATINK)
    JOHTO_DEX(TINKATUFF)
    JOHTO_DEX(TINKATON)
#endif
#if P_FAMILY_WIGLETT
    JOHTO_DEX(WIGLETT)
    JOHTO_DEX(WUGTRIO)
#endif
#if P_FAMILY_BOMBIRDIER
    JOHTO_DEX(BOMBIRDIER)
#endif
#if P_FAMILY_FINIZEN
    JOHTO_DEX(FINIZEN)
    JOHTO_DEX(PALAFIN)
#endif
#if P_FAMILY_VAROOM
    JOHTO_DEX(VAROOM)
    JOHTO_DEX(REVAVROOM)
#endif
#if P_FAMILY_CYCLIZAR
    JOHTO_DEX(CYCLIZAR)
#endif
#if P_FAMILY_ORTHWORM
    JOHTO_DEX(ORTHWORM)
#endif
#if P_FAMILY_GLIMMET
    JOHTO_DEX(GLIMMET)
    JOHTO_DEX(GLIMMORA)
#endif
#if P_FAMILY_GREAVARD
    JOHTO_DEX(GREAVARD)
    JOHTO_DEX(HOUNDSTONE)
#endif
#if P_FAMILY_FLAMIGO
    JOHTO_DEX(FLAMIGO)
#endif
#if P_FAMILY_CETODDLE
    JOHTO_DEX(CETODDLE)
    JOHTO_DEX(CETITAN)
#endif
#if P_FAMILY_VELUZA
    JOHTO_DEX(VELUZA)
#endif
#if P_FAMILY_DONDOZO
    JOHTO_DEX(DONDOZO)
#endif
#if P_FAMILY_TATSUGIRI
    JOHTO_DEX(TATSUGIRI)
#endif
#if P_FAMILY_MANKEY && P_GEN_9_CROSS_EVOS
    JOHTO_DEX(ANNIHILAPE)
#endif
#if P_FAMILY_WOOPER && P_PALDEAN_FORMS
    JOHTO_DEX(CLODSIRE)
#endif
#if P_FAMILY_GIRAFARIG && P_GEN_9_CROSS_EVOS
    JOHTO_DEX(FARIGIRAF)
#endif
#if P_FAMILY_DUNSPARCE && P_GEN_9_CROSS_EVOS
    JOHTO_DEX(DUDUNSPARCE)
#endif
#if P_FAMILY_PAWNIARD && P_GEN_9_CROSS_EVOS
    JOHTO_DEX(KINGAMBIT)
#endif
#if P_FAMILY_GREAT_TUSK
    JOHTO_DEX(GREAT_TUSK)
#endif
#if P_FAMILY_SCREAM_TAIL
    JOHTO_DEX(SCREAM_TAIL)
#endif
#if P_FAMILY_BRUTE_BONNET
    JOHTO_DEX(BRUTE_BONNET)
#endif
#if P_FAMILY_FLUTTER_MANE
    JOHTO_DEX(FLUTTER_MANE)
#endif
#if P_FAMILY_SLITHER_WING
    JOHTO_DEX(SLITHER_WING)
#endif
#if P_FAMILY_SANDY_SHOCKS
    JOHTO_DEX(SANDY_SHOCKS)
#endif
#if P_FAMILY_IRON_TREADS
    JOHTO_DEX(IRON_TREADS)
#endif
#if P_FAMILY_IRON_BUNDLE
    JOHTO_DEX(IRON_BUNDLE)
#endif
#if P_FAMILY_IRON_HANDS
    JOHTO_DEX(IRON_HANDS)
#endif
#if P_FAMILY_IRON_JUGULIS
    JOHTO_DEX(IRON_JUGULIS)
#endif
#if P_FAMILY_IRON_MOTH
    JOHTO_DEX(IRON_MOTH)
#endif
#if P_FAMILY_IRON_THORNS
    JOHTO_DEX(IRON_THORNS)
#endif
#if P_FAMILY_FRIGIBAX
    JOHTO_DEX(FRIGIBAX)
    JOHTO_DEX(ARCTIBAX)
    JOHTO_DEX(BAXCALIBUR)
#endif
#if P_FAMILY_GIMMIGHOUL
    JOHTO_DEX(GIMMIGHOUL)
    JOHTO_DEX(GHOLDENGO)
#endif
#if P_FAMILY_WO_CHIEN
    JOHTO_DEX(WO_CHIEN)
#endif
#if P_FAMILY_CHIEN_PAO
    JOHTO_DEX(CHIEN_PAO)
#endif
#if P_FAMILY_TING_LU
    JOHTO_DEX(TING_LU)
#endif
#if P_FAMILY_CHI_YU
    JOHTO_DEX(CHI_YU)
#endif
#if P_FAMILY_ROARING_MOON
    JOHTO_DEX(ROARING_MOON)
#endif
#if P_FAMILY_IRON_VALIANT
    JOHTO_DEX(IRON_VALIANT)
#endif
#if P_FAMILY_KORAIDON
    JOHTO_DEX(KORAIDON)
#endif
#if P_FAMILY_MIRAIDON
    JOHTO_DEX(MIRAIDON)
#endif
#if P_FAMILY_WALKING_WAKE
    JOHTO_DEX(WALKING_WAKE)
#endif
#if P_FAMILY_IRON_LEAVES
    JOHTO_DEX(IRON_LEAVES)
#endif
#if P_FAMILY_APPLIN && P_GEN_9_CROSS_EVOS
    JOHTO_DEX(DIPPLIN)
#endif
#if P_FAMILY_POLTCHAGEIST
    JOHTO_DEX(POLTCHAGEIST)
    JOHTO_DEX(SINISTCHA)
#endif
#if P_FAMILY_OKIDOGI
    JOHTO_DEX(OKIDOGI)
#endif
#if P_FAMILY_MUNKIDORI
    JOHTO_DEX(MUNKIDORI)
#endif
#if P_FAMILY_FEZANDIPITI
    JOHTO_DEX(FEZANDIPITI)
#endif
#if P_FAMILY_OGERPON
    JOHTO_DEX(OGERPON)
#endif
#if P_FAMILY_DURALUDON && P_GEN_9_CROSS_EVOS
    JOHTO_DEX(ARCHALUDON)
#endif
#if P_FAMILY_APPLIN && P_GEN_9_CROSS_EVOS
    JOHTO_DEX(HYDRAPPLE)
#endif
#if P_FAMILY_GOUGING_FIRE
    JOHTO_DEX(GOUGING_FIRE)
#endif
#if P_FAMILY_RAGING_BOLT
    JOHTO_DEX(RAGING_BOLT)
#endif
#if P_FAMILY_IRON_BOULDER
    JOHTO_DEX(IRON_BOULDER)
#endif
#if P_FAMILY_IRON_CROWN
    JOHTO_DEX(IRON_CROWN)
#endif
#if P_FAMILY_TERAPAGOS
    JOHTO_DEX(TERAPAGOS)
#endif
#if P_FAMILY_PECHARUNT
    JOHTO_DEX(PECHARUNT)
#endif
#if P_FAMILY_RIKO
    JOHTO_DEX(RIKO)
#endif
#if P_FAMILY_BIJUU
    JOHTO_DEX(BIJUU)
#endif
