#ifndef GUARD_CONSTANTS_POKEDEX_H
#define GUARD_CONSTANTS_POKEDEX_H

// National Pokédex order
// These constants are NOT disabled by P_GEN_X_POKEMON to keep pokedex_orders.h clean.
enum NationalDexOrder
{
    NATIONAL_DEX_NONE,
    // Kanto
    NATIONAL_DEX_BULBASAUR,
    NATIONAL_DEX_IVYSAUR,
    NATIONAL_DEX_VENUSAUR,
    NATIONAL_DEX_CHARMANDER,
    NATIONAL_DEX_CHARMELEON,
    NATIONAL_DEX_CHARIZARD,
    NATIONAL_DEX_SQUIRTLE,
    NATIONAL_DEX_WARTORTLE,
    NATIONAL_DEX_BLASTOISE,
    NATIONAL_DEX_CATERPIE,
    NATIONAL_DEX_METAPOD,
    NATIONAL_DEX_BUTTERFREE,
    NATIONAL_DEX_WEEDLE,
    NATIONAL_DEX_KAKUNA,
    NATIONAL_DEX_BEEDRILL,
    NATIONAL_DEX_PIDGEY,
    NATIONAL_DEX_PIDGEOTTO,
    NATIONAL_DEX_PIDGEOT,
    NATIONAL_DEX_RATTATA,
    NATIONAL_DEX_RATICATE,
    NATIONAL_DEX_SPEAROW,
    NATIONAL_DEX_FEAROW,
    NATIONAL_DEX_EKANS,
    NATIONAL_DEX_ARBOK,
    NATIONAL_DEX_PIKACHU,
    NATIONAL_DEX_RAICHU,
    NATIONAL_DEX_SANDSHREW,
    NATIONAL_DEX_SANDSLASH,
    NATIONAL_DEX_NIDORAN_F,
    NATIONAL_DEX_NIDORINA,
    NATIONAL_DEX_NIDOQUEEN,
    NATIONAL_DEX_NIDORAN_M,
    NATIONAL_DEX_NIDORINO,
    NATIONAL_DEX_NIDOKING,
    NATIONAL_DEX_CLEFAIRY,
    NATIONAL_DEX_CLEFABLE,
    NATIONAL_DEX_VULPIX,
    NATIONAL_DEX_NINETALES,
    NATIONAL_DEX_JIGGLYPUFF,
    NATIONAL_DEX_WIGGLYTUFF,
    NATIONAL_DEX_ZUBAT,
    NATIONAL_DEX_GOLBAT,
    NATIONAL_DEX_ODDISH,
    NATIONAL_DEX_GLOOM,
    NATIONAL_DEX_VILEPLUME,
    NATIONAL_DEX_PARAS,
    NATIONAL_DEX_PARASECT,
    NATIONAL_DEX_VENONAT,
    NATIONAL_DEX_VENOMOTH,
    NATIONAL_DEX_DIGLETT,
    NATIONAL_DEX_DUGTRIO,
    NATIONAL_DEX_MEOWTH,
    NATIONAL_DEX_PERSIAN,
    NATIONAL_DEX_PSYDUCK,
    NATIONAL_DEX_GOLDUCK,
    NATIONAL_DEX_MANKEY,
    NATIONAL_DEX_PRIMEAPE,
    NATIONAL_DEX_GROWLITHE,
    NATIONAL_DEX_ARCANINE,
    NATIONAL_DEX_POLIWAG,
    NATIONAL_DEX_POLIWHIRL,
    NATIONAL_DEX_POLIWRATH,
    NATIONAL_DEX_ABRA,
    NATIONAL_DEX_KADABRA,
    NATIONAL_DEX_ALAKAZAM,
    NATIONAL_DEX_MACHOP,
    NATIONAL_DEX_MACHOKE,
    NATIONAL_DEX_MACHAMP,
    NATIONAL_DEX_BELLSPROUT,
    NATIONAL_DEX_WEEPINBELL,
    NATIONAL_DEX_VICTREEBEL,
    NATIONAL_DEX_TENTACOOL,
    NATIONAL_DEX_TENTACRUEL,
    NATIONAL_DEX_GEODUDE,
    NATIONAL_DEX_GRAVELER,
    NATIONAL_DEX_GOLEM,
    NATIONAL_DEX_PONYTA,
    NATIONAL_DEX_RAPIDASH,
    NATIONAL_DEX_SLOWPOKE,
    NATIONAL_DEX_SLOWBRO,
    NATIONAL_DEX_MAGNEMITE,
    NATIONAL_DEX_MAGNETON,
    NATIONAL_DEX_FARFETCHD,
    NATIONAL_DEX_DODUO,
    NATIONAL_DEX_DODRIO,
    NATIONAL_DEX_SEEL,
    NATIONAL_DEX_DEWGONG,
    NATIONAL_DEX_GRIMER,
    NATIONAL_DEX_MUK,
    NATIONAL_DEX_SHELLDER,
    NATIONAL_DEX_CLOYSTER,
    NATIONAL_DEX_GASTLY,
    NATIONAL_DEX_HAUNTER,
    NATIONAL_DEX_GENGAR,
    NATIONAL_DEX_ONIX,
    NATIONAL_DEX_DROWZEE,
    NATIONAL_DEX_HYPNO,
    NATIONAL_DEX_KRABBY,
    NATIONAL_DEX_KINGLER,
    NATIONAL_DEX_VOLTORB,
    NATIONAL_DEX_ELECTRODE,
    NATIONAL_DEX_EXEGGCUTE,
    NATIONAL_DEX_EXEGGUTOR,
    NATIONAL_DEX_CUBONE,
    NATIONAL_DEX_MAROWAK,
    NATIONAL_DEX_HITMONLEE,
    NATIONAL_DEX_HITMONCHAN,
    NATIONAL_DEX_LICKITUNG,
    NATIONAL_DEX_KOFFING,
    NATIONAL_DEX_WEEZING,
    NATIONAL_DEX_RHYHORN,
    NATIONAL_DEX_RHYDON,
    NATIONAL_DEX_CHANSEY,
    NATIONAL_DEX_TANGELA,
    NATIONAL_DEX_KANGASKHAN,
    NATIONAL_DEX_HORSEA,
    NATIONAL_DEX_SEADRA,
    NATIONAL_DEX_GOLDEEN,
    NATIONAL_DEX_SEAKING,
    NATIONAL_DEX_STARYU,
    NATIONAL_DEX_STARMIE,
    NATIONAL_DEX_MR_MIME,
    NATIONAL_DEX_SCYTHER,
    NATIONAL_DEX_JYNX,
    NATIONAL_DEX_ELECTABUZZ,
    NATIONAL_DEX_MAGMAR,
    NATIONAL_DEX_PINSIR,
    NATIONAL_DEX_TAUROS,
    NATIONAL_DEX_MAGIKARP,
    NATIONAL_DEX_GYARADOS,
    NATIONAL_DEX_LAPRAS,
    NATIONAL_DEX_DITTO,
    NATIONAL_DEX_EEVEE,
    NATIONAL_DEX_VAPOREON,
    NATIONAL_DEX_JOLTEON,
    NATIONAL_DEX_FLAREON,
    NATIONAL_DEX_PORYGON,
    NATIONAL_DEX_OMANYTE,
    NATIONAL_DEX_OMASTAR,
    NATIONAL_DEX_KABUTO,
    NATIONAL_DEX_KABUTOPS,
    NATIONAL_DEX_AERODACTYL,
    NATIONAL_DEX_SNORLAX,
    NATIONAL_DEX_ARTICUNO,
    NATIONAL_DEX_ZAPDOS,
    NATIONAL_DEX_MOLTRES,
    NATIONAL_DEX_DRATINI,
    NATIONAL_DEX_DRAGONAIR,
    NATIONAL_DEX_DRAGONITE,
    NATIONAL_DEX_MEWTWO,
    NATIONAL_DEX_MEW,
    // Johto
    NATIONAL_DEX_CHIKORITA,
    NATIONAL_DEX_BAYLEEF,
    NATIONAL_DEX_MEGANIUM,
    NATIONAL_DEX_CYNDAQUIL,
    NATIONAL_DEX_QUILAVA,
    NATIONAL_DEX_TYPHLOSION,
    NATIONAL_DEX_TOTODILE,
    NATIONAL_DEX_CROCONAW,
    NATIONAL_DEX_FERALIGATR,
    NATIONAL_DEX_SENTRET,
    NATIONAL_DEX_FURRET,
    NATIONAL_DEX_HOOTHOOT,
    NATIONAL_DEX_NOCTOWL,
    NATIONAL_DEX_LEDYBA,
    NATIONAL_DEX_LEDIAN,
    NATIONAL_DEX_SPINARAK,
    NATIONAL_DEX_ARIADOS,
    NATIONAL_DEX_CROBAT,
    NATIONAL_DEX_CHINCHOU,
    NATIONAL_DEX_LANTURN,
    NATIONAL_DEX_PICHU,
    NATIONAL_DEX_CLEFFA,
    NATIONAL_DEX_IGGLYBUFF,
    NATIONAL_DEX_TOGEPI,
    NATIONAL_DEX_TOGETIC,
    NATIONAL_DEX_NATU,
    NATIONAL_DEX_XATU,
    NATIONAL_DEX_MAREEP,
    NATIONAL_DEX_FLAAFFY,
    NATIONAL_DEX_AMPHAROS,
    NATIONAL_DEX_BELLOSSOM,
    NATIONAL_DEX_MARILL,
    NATIONAL_DEX_AZUMARILL,
    NATIONAL_DEX_SUDOWOODO,
    NATIONAL_DEX_POLITOED,
    NATIONAL_DEX_HOPPIP,
    NATIONAL_DEX_SKIPLOOM,
    NATIONAL_DEX_JUMPLUFF,
    NATIONAL_DEX_AIPOM,
    NATIONAL_DEX_SUNKERN,
    NATIONAL_DEX_SUNFLORA,
    NATIONAL_DEX_YANMA,
    NATIONAL_DEX_WOOPER,
    NATIONAL_DEX_QUAGSIRE,
    NATIONAL_DEX_ESPEON,
    NATIONAL_DEX_UMBREON,
    NATIONAL_DEX_MURKROW,
    NATIONAL_DEX_SLOWKING,
    NATIONAL_DEX_MISDREAVUS,
    NATIONAL_DEX_UNOWN,
    NATIONAL_DEX_WOBBUFFET,
    NATIONAL_DEX_GIRAFARIG,
    NATIONAL_DEX_PINECO,
    NATIONAL_DEX_FORRETRESS,
    NATIONAL_DEX_DUNSPARCE,
    NATIONAL_DEX_GLIGAR,
    NATIONAL_DEX_STEELIX,
    NATIONAL_DEX_SNUBBULL,
    NATIONAL_DEX_GRANBULL,
    NATIONAL_DEX_QWILFISH,
    NATIONAL_DEX_SCIZOR,
    NATIONAL_DEX_SHUCKLE,
    NATIONAL_DEX_HERACROSS,
    NATIONAL_DEX_SNEASEL,
    NATIONAL_DEX_TEDDIURSA,
    NATIONAL_DEX_URSARING,
    NATIONAL_DEX_SLUGMA,
    NATIONAL_DEX_MAGCARGO,
    NATIONAL_DEX_SWINUB,
    NATIONAL_DEX_PILOSWINE,
    NATIONAL_DEX_CORSOLA,
    NATIONAL_DEX_REMORAID,
    NATIONAL_DEX_OCTILLERY,
    NATIONAL_DEX_DELIBIRD,
    NATIONAL_DEX_MANTINE,
    NATIONAL_DEX_SKARMORY,
    NATIONAL_DEX_HOUNDOUR,
    NATIONAL_DEX_HOUNDOOM,
    NATIONAL_DEX_KINGDRA,
    NATIONAL_DEX_PHANPY,
    NATIONAL_DEX_DONPHAN,
    NATIONAL_DEX_PORYGON2,
    NATIONAL_DEX_STANTLER,
    NATIONAL_DEX_SMEARGLE,
    NATIONAL_DEX_TYROGUE,
    NATIONAL_DEX_HITMONTOP,
    NATIONAL_DEX_SMOOCHUM,
    NATIONAL_DEX_ELEKID,
    NATIONAL_DEX_MAGBY,
    NATIONAL_DEX_MILTANK,
    NATIONAL_DEX_BLISSEY,
    NATIONAL_DEX_RAIKOU,
    NATIONAL_DEX_ENTEI,
    NATIONAL_DEX_SUICUNE,
    NATIONAL_DEX_LARVITAR,
    NATIONAL_DEX_PUPITAR,
    NATIONAL_DEX_TYRANITAR,
    NATIONAL_DEX_LUGIA,
    NATIONAL_DEX_HO_OH,
    NATIONAL_DEX_CELEBI,
    // Hoenn
    NATIONAL_DEX_TREECKO,
    NATIONAL_DEX_GROVYLE,
    NATIONAL_DEX_SCEPTILE,
    NATIONAL_DEX_TORCHIC,
    NATIONAL_DEX_COMBUSKEN,
    NATIONAL_DEX_BLAZIKEN,
    NATIONAL_DEX_MUDKIP,
    NATIONAL_DEX_MARSHTOMP,
    NATIONAL_DEX_SWAMPERT,
    NATIONAL_DEX_POOCHYENA,
    NATIONAL_DEX_MIGHTYENA,
    NATIONAL_DEX_ZIGZAGOON,
    NATIONAL_DEX_LINOONE,
    NATIONAL_DEX_WURMPLE,
    NATIONAL_DEX_SILCOON,
    NATIONAL_DEX_BEAUTIFLY,
    NATIONAL_DEX_CASCOON,
    NATIONAL_DEX_DUSTOX,
    NATIONAL_DEX_LOTAD,
    NATIONAL_DEX_LOMBRE,
    NATIONAL_DEX_LUDICOLO,
    NATIONAL_DEX_SEEDOT,
    NATIONAL_DEX_NUZLEAF,
    NATIONAL_DEX_SHIFTRY,
    NATIONAL_DEX_TAILLOW,
    NATIONAL_DEX_SWELLOW,
    NATIONAL_DEX_WINGULL,
    NATIONAL_DEX_PELIPPER,
    NATIONAL_DEX_RALTS,
    NATIONAL_DEX_KIRLIA,
    NATIONAL_DEX_GARDEVOIR,
    NATIONAL_DEX_SURSKIT,
    NATIONAL_DEX_MASQUERAIN,
    NATIONAL_DEX_SHROOMISH,
    NATIONAL_DEX_BRELOOM,
    NATIONAL_DEX_SLAKOTH,
    NATIONAL_DEX_VIGOROTH,
    NATIONAL_DEX_SLAKING,
    NATIONAL_DEX_NINCADA,
    NATIONAL_DEX_NINJASK,
    NATIONAL_DEX_SHEDINJA,
    NATIONAL_DEX_WHISMUR,
    NATIONAL_DEX_LOUDRED,
    NATIONAL_DEX_EXPLOUD,
    NATIONAL_DEX_MAKUHITA,
    NATIONAL_DEX_HARIYAMA,
    NATIONAL_DEX_AZURILL,
    NATIONAL_DEX_NOSEPASS,
    NATIONAL_DEX_SKITTY,
    NATIONAL_DEX_DELCATTY,
    NATIONAL_DEX_SABLEYE,
    NATIONAL_DEX_MAWILE,
    NATIONAL_DEX_ARON,
    NATIONAL_DEX_LAIRON,
    NATIONAL_DEX_AGGRON,
    NATIONAL_DEX_MEDITITE,
    NATIONAL_DEX_MEDICHAM,
    NATIONAL_DEX_ELECTRIKE,
    NATIONAL_DEX_MANECTRIC,
    NATIONAL_DEX_PLUSLE,
    NATIONAL_DEX_MINUN,
    NATIONAL_DEX_VOLBEAT,
    NATIONAL_DEX_ILLUMISE,
    NATIONAL_DEX_ROSELIA,
    NATIONAL_DEX_GULPIN,
    NATIONAL_DEX_SWALOT,
    NATIONAL_DEX_CARVANHA,
    NATIONAL_DEX_SHARPEDO,
    NATIONAL_DEX_WAILMER,
    NATIONAL_DEX_WAILORD,
    NATIONAL_DEX_NUMEL,
    NATIONAL_DEX_CAMERUPT,
    NATIONAL_DEX_TORKOAL,
    NATIONAL_DEX_SPOINK,
    NATIONAL_DEX_GRUMPIG,
    NATIONAL_DEX_SPINDA,
    NATIONAL_DEX_TRAPINCH,
    NATIONAL_DEX_VIBRAVA,
    NATIONAL_DEX_FLYGON,
    NATIONAL_DEX_CACNEA,
    NATIONAL_DEX_CACTURNE,
    NATIONAL_DEX_SWABLU,
    NATIONAL_DEX_ALTARIA,
    NATIONAL_DEX_ZANGOOSE,
    NATIONAL_DEX_SEVIPER,
    NATIONAL_DEX_LUNATONE,
    NATIONAL_DEX_SOLROCK,
    NATIONAL_DEX_BARBOACH,
    NATIONAL_DEX_WHISCASH,
    NATIONAL_DEX_CORPHISH,
    NATIONAL_DEX_CRAWDAUNT,
    NATIONAL_DEX_BALTOY,
    NATIONAL_DEX_CLAYDOL,
    NATIONAL_DEX_LILEEP,
    NATIONAL_DEX_CRADILY,
    NATIONAL_DEX_ANORITH,
    NATIONAL_DEX_ARMALDO,
    NATIONAL_DEX_FEEBAS,
    NATIONAL_DEX_MILOTIC,
    NATIONAL_DEX_CASTFORM,
    NATIONAL_DEX_KECLEON,
    NATIONAL_DEX_SHUPPET,
    NATIONAL_DEX_BANETTE,
    NATIONAL_DEX_DUSKULL,
    NATIONAL_DEX_DUSCLOPS,
    NATIONAL_DEX_TROPIUS,
    NATIONAL_DEX_CHIMECHO,
    NATIONAL_DEX_ABSOL,
    NATIONAL_DEX_WYNAUT,
    NATIONAL_DEX_SNORUNT,
    NATIONAL_DEX_GLALIE,
    NATIONAL_DEX_SPHEAL,
    NATIONAL_DEX_SEALEO,
    NATIONAL_DEX_WALREIN,
    NATIONAL_DEX_CLAMPERL,
    NATIONAL_DEX_HUNTAIL,
    NATIONAL_DEX_GOREBYSS,
    NATIONAL_DEX_RELICANTH,
    NATIONAL_DEX_LUVDISC,
    NATIONAL_DEX_BAGON,
    NATIONAL_DEX_SHELGON,
    NATIONAL_DEX_SALAMENCE,
    NATIONAL_DEX_BELDUM,
    NATIONAL_DEX_METANG,
    NATIONAL_DEX_METAGROSS,
    NATIONAL_DEX_REGIROCK,
    NATIONAL_DEX_REGICE,
    NATIONAL_DEX_REGISTEEL,
    NATIONAL_DEX_LATIAS,
    NATIONAL_DEX_LATIOS,
    NATIONAL_DEX_KYOGRE,
    NATIONAL_DEX_GROUDON,
    NATIONAL_DEX_RAYQUAZA,
    NATIONAL_DEX_JIRACHI,
    NATIONAL_DEX_DEOXYS,
    // Sinnoh
    NATIONAL_DEX_TURTWIG,
    NATIONAL_DEX_GROTLE,
    NATIONAL_DEX_TORTERRA,
    NATIONAL_DEX_CHIMCHAR,
    NATIONAL_DEX_MONFERNO,
    NATIONAL_DEX_INFERNAPE,
    NATIONAL_DEX_PIPLUP,
    NATIONAL_DEX_PRINPLUP,
    NATIONAL_DEX_EMPOLEON,
    NATIONAL_DEX_STARLY,
    NATIONAL_DEX_STARAVIA,
    NATIONAL_DEX_STARAPTOR,
    NATIONAL_DEX_BIDOOF,
    NATIONAL_DEX_BIBAREL,
    NATIONAL_DEX_KRICKETOT,
    NATIONAL_DEX_KRICKETUNE,
    NATIONAL_DEX_SHINX,
    NATIONAL_DEX_LUXIO,
    NATIONAL_DEX_LUXRAY,
    NATIONAL_DEX_BUDEW,
    NATIONAL_DEX_ROSERADE,
    NATIONAL_DEX_CRANIDOS,
    NATIONAL_DEX_RAMPARDOS,
    NATIONAL_DEX_SHIELDON,
    NATIONAL_DEX_BASTIODON,
    NATIONAL_DEX_BURMY,
    NATIONAL_DEX_WORMADAM,
    NATIONAL_DEX_MOTHIM,
    NATIONAL_DEX_COMBEE,
    NATIONAL_DEX_VESPIQUEN,
    NATIONAL_DEX_PACHIRISU,
    NATIONAL_DEX_BUIZEL,
    NATIONAL_DEX_FLOATZEL,
    NATIONAL_DEX_CHERUBI,
    NATIONAL_DEX_CHERRIM,
    NATIONAL_DEX_SHELLOS,
    NATIONAL_DEX_GASTRODON,
    NATIONAL_DEX_AMBIPOM,
    NATIONAL_DEX_DRIFLOON,
    NATIONAL_DEX_DRIFBLIM,
    NATIONAL_DEX_BUNEARY,
    NATIONAL_DEX_LOPUNNY,
    NATIONAL_DEX_MISMAGIUS,
    NATIONAL_DEX_HONCHKROW,
    NATIONAL_DEX_GLAMEOW,
    NATIONAL_DEX_PURUGLY,
    NATIONAL_DEX_CHINGLING,
    NATIONAL_DEX_STUNKY,
    NATIONAL_DEX_SKUNTANK,
    NATIONAL_DEX_BRONZOR,
    NATIONAL_DEX_BRONZONG,
    NATIONAL_DEX_BONSLY,
    NATIONAL_DEX_MIME_JR,
    NATIONAL_DEX_HAPPINY,
    NATIONAL_DEX_CHATOT,
    NATIONAL_DEX_SPIRITOMB,
    NATIONAL_DEX_GIBLE,
    NATIONAL_DEX_GABITE,
    NATIONAL_DEX_GARCHOMP,
    NATIONAL_DEX_MUNCHLAX,
    NATIONAL_DEX_RIOLU,
    NATIONAL_DEX_LUCARIO,
    NATIONAL_DEX_HIPPOPOTAS,
    NATIONAL_DEX_HIPPOWDON,
    NATIONAL_DEX_SKORUPI,
    NATIONAL_DEX_DRAPION,
    NATIONAL_DEX_CROAGUNK,
    NATIONAL_DEX_TOXICROAK,
    NATIONAL_DEX_CARNIVINE,
    NATIONAL_DEX_FINNEON,
    NATIONAL_DEX_LUMINEON,
    NATIONAL_DEX_MANTYKE,
    NATIONAL_DEX_SNOVER,
    NATIONAL_DEX_ABOMASNOW,
    NATIONAL_DEX_WEAVILE,
    NATIONAL_DEX_MAGNEZONE,
    NATIONAL_DEX_LICKILICKY,
    NATIONAL_DEX_RHYPERIOR,
    NATIONAL_DEX_TANGROWTH,
    NATIONAL_DEX_ELECTIVIRE,
    NATIONAL_DEX_MAGMORTAR,
    NATIONAL_DEX_TOGEKISS,
    NATIONAL_DEX_YANMEGA,
    NATIONAL_DEX_LEAFEON,
    NATIONAL_DEX_GLACEON,
    NATIONAL_DEX_GLISCOR,
    NATIONAL_DEX_MAMOSWINE,
    NATIONAL_DEX_PORYGON_Z,
    NATIONAL_DEX_GALLADE,
    NATIONAL_DEX_PROBOPASS,
    NATIONAL_DEX_DUSKNOIR,
    NATIONAL_DEX_FROSLASS,
    NATIONAL_DEX_ROTOM,
    NATIONAL_DEX_UXIE,
    NATIONAL_DEX_MESPRIT,
    NATIONAL_DEX_AZELF,
    NATIONAL_DEX_DIALGA,
    NATIONAL_DEX_PALKIA,
    NATIONAL_DEX_HEATRAN,
    NATIONAL_DEX_REGIGIGAS,
    NATIONAL_DEX_GIRATINA,
    NATIONAL_DEX_CRESSELIA,
    NATIONAL_DEX_PHIONE,
    NATIONAL_DEX_MANAPHY,
    NATIONAL_DEX_DARKRAI,
    NATIONAL_DEX_SHAYMIN,
    NATIONAL_DEX_ARCEUS,
    // Unova
    NATIONAL_DEX_VICTINI,
    NATIONAL_DEX_SNIVY,
    NATIONAL_DEX_SERVINE,
    NATIONAL_DEX_SERPERIOR,
    NATIONAL_DEX_TEPIG,
    NATIONAL_DEX_PIGNITE,
    NATIONAL_DEX_EMBOAR,
    NATIONAL_DEX_OSHAWOTT,
    NATIONAL_DEX_DEWOTT,
    NATIONAL_DEX_SAMUROTT,
    NATIONAL_DEX_PATRAT,
    NATIONAL_DEX_WATCHOG,
    NATIONAL_DEX_LILLIPUP,
    NATIONAL_DEX_HERDIER,
    NATIONAL_DEX_STOUTLAND,
    NATIONAL_DEX_PURRLOIN,
    NATIONAL_DEX_LIEPARD,
    NATIONAL_DEX_PANSAGE,
    NATIONAL_DEX_SIMISAGE,
    NATIONAL_DEX_PANSEAR,
    NATIONAL_DEX_SIMISEAR,
    NATIONAL_DEX_PANPOUR,
    NATIONAL_DEX_SIMIPOUR,
    NATIONAL_DEX_MUNNA,
    NATIONAL_DEX_MUSHARNA,
    NATIONAL_DEX_PIDOVE,
    NATIONAL_DEX_TRANQUILL,
    NATIONAL_DEX_UNFEZANT,
    NATIONAL_DEX_BLITZLE,
    NATIONAL_DEX_ZEBSTRIKA,
    NATIONAL_DEX_ROGGENROLA,
    NATIONAL_DEX_BOLDORE,
    NATIONAL_DEX_GIGALITH,
    NATIONAL_DEX_WOOBAT,
    NATIONAL_DEX_SWOOBAT,
    NATIONAL_DEX_DRILBUR,
    NATIONAL_DEX_EXCADRILL,
    NATIONAL_DEX_AUDINO,
    NATIONAL_DEX_TIMBURR,
    NATIONAL_DEX_GURDURR,
    NATIONAL_DEX_CONKELDURR,
    NATIONAL_DEX_TYMPOLE,
    NATIONAL_DEX_PALPITOAD,
    NATIONAL_DEX_SEISMITOAD,
    NATIONAL_DEX_THROH,
    NATIONAL_DEX_SAWK,
    NATIONAL_DEX_SEWADDLE,
    NATIONAL_DEX_SWADLOON,
    NATIONAL_DEX_LEAVANNY,
    NATIONAL_DEX_VENIPEDE,
    NATIONAL_DEX_WHIRLIPEDE,
    NATIONAL_DEX_SCOLIPEDE,
    NATIONAL_DEX_COTTONEE,
    NATIONAL_DEX_WHIMSICOTT,
    NATIONAL_DEX_PETILIL,
    NATIONAL_DEX_LILLIGANT,
    NATIONAL_DEX_BASCULIN,
    NATIONAL_DEX_SANDILE,
    NATIONAL_DEX_KROKOROK,
    NATIONAL_DEX_KROOKODILE,
    NATIONAL_DEX_DARUMAKA,
    NATIONAL_DEX_DARMANITAN,
    NATIONAL_DEX_MARACTUS,
    NATIONAL_DEX_DWEBBLE,
    NATIONAL_DEX_CRUSTLE,
    NATIONAL_DEX_SCRAGGY,
    NATIONAL_DEX_SCRAFTY,
    NATIONAL_DEX_SIGILYPH,
    NATIONAL_DEX_YAMASK,
    NATIONAL_DEX_COFAGRIGUS,
    NATIONAL_DEX_TIRTOUGA,
    NATIONAL_DEX_CARRACOSTA,
    NATIONAL_DEX_ARCHEN,
    NATIONAL_DEX_ARCHEOPS,
    NATIONAL_DEX_TRUBBISH,
    NATIONAL_DEX_GARBODOR,
    NATIONAL_DEX_ZORUA,
    NATIONAL_DEX_ZOROARK,
    NATIONAL_DEX_MINCCINO,
    NATIONAL_DEX_CINCCINO,
    NATIONAL_DEX_GOTHITA,
    NATIONAL_DEX_GOTHORITA,
    NATIONAL_DEX_GOTHITELLE,
    NATIONAL_DEX_SOLOSIS,
    NATIONAL_DEX_DUOSION,
    NATIONAL_DEX_REUNICLUS,
    NATIONAL_DEX_DUCKLETT,
    NATIONAL_DEX_SWANNA,
    NATIONAL_DEX_VANILLITE,
    NATIONAL_DEX_VANILLISH,
    NATIONAL_DEX_VANILLUXE,
    NATIONAL_DEX_DEERLING,
    NATIONAL_DEX_SAWSBUCK,
    NATIONAL_DEX_EMOLGA,
    NATIONAL_DEX_KARRABLAST,
    NATIONAL_DEX_ESCAVALIER,
    NATIONAL_DEX_FOONGUS,
    NATIONAL_DEX_AMOONGUSS,
    NATIONAL_DEX_FRILLISH,
    NATIONAL_DEX_JELLICENT,
    NATIONAL_DEX_ALOMOMOLA,
    NATIONAL_DEX_JOLTIK,
    NATIONAL_DEX_GALVANTULA,
    NATIONAL_DEX_FERROSEED,
    NATIONAL_DEX_FERROTHORN,
    NATIONAL_DEX_KLINK,
    NATIONAL_DEX_KLANG,
    NATIONAL_DEX_KLINKLANG,
    NATIONAL_DEX_TYNAMO,
    NATIONAL_DEX_EELEKTRIK,
    NATIONAL_DEX_EELEKTROSS,
    NATIONAL_DEX_ELGYEM,
    NATIONAL_DEX_BEHEEYEM,
    NATIONAL_DEX_LITWICK,
    NATIONAL_DEX_LAMPENT,
    NATIONAL_DEX_CHANDELURE,
    NATIONAL_DEX_AXEW,
    NATIONAL_DEX_FRAXURE,
    NATIONAL_DEX_HAXORUS,
    NATIONAL_DEX_CUBCHOO,
    NATIONAL_DEX_BEARTIC,
    NATIONAL_DEX_CRYOGONAL,
    NATIONAL_DEX_SHELMET,
    NATIONAL_DEX_ACCELGOR,
    NATIONAL_DEX_STUNFISK,
    NATIONAL_DEX_MIENFOO,
    NATIONAL_DEX_MIENSHAO,
    NATIONAL_DEX_DRUDDIGON,
    NATIONAL_DEX_GOLETT,
    NATIONAL_DEX_GOLURK,
    NATIONAL_DEX_PAWNIARD,
    NATIONAL_DEX_BISHARP,
    NATIONAL_DEX_BOUFFALANT,
    NATIONAL_DEX_RUFFLET,
    NATIONAL_DEX_BRAVIARY,
    NATIONAL_DEX_VULLABY,
    NATIONAL_DEX_MANDIBUZZ,
    NATIONAL_DEX_HEATMOR,
    NATIONAL_DEX_DURANT,
    NATIONAL_DEX_DEINO,
    NATIONAL_DEX_ZWEILOUS,
    NATIONAL_DEX_HYDREIGON,
    NATIONAL_DEX_LARVESTA,
    NATIONAL_DEX_VOLCARONA,
    NATIONAL_DEX_COBALION,
    NATIONAL_DEX_TERRAKION,
    NATIONAL_DEX_VIRIZION,
    NATIONAL_DEX_TORNADUS,
    NATIONAL_DEX_THUNDURUS,
    NATIONAL_DEX_RESHIRAM,
    NATIONAL_DEX_ZEKROM,
    NATIONAL_DEX_LANDORUS,
    NATIONAL_DEX_KYUREM,
    NATIONAL_DEX_KELDEO,
    NATIONAL_DEX_MELOETTA,
    NATIONAL_DEX_GENESECT,
    // Kalos
    NATIONAL_DEX_CHESPIN,
    NATIONAL_DEX_QUILLADIN,
    NATIONAL_DEX_CHESNAUGHT,
    NATIONAL_DEX_FENNEKIN,
    NATIONAL_DEX_BRAIXEN,
    NATIONAL_DEX_DELPHOX,
    NATIONAL_DEX_FROAKIE,
    NATIONAL_DEX_FROGADIER,
    NATIONAL_DEX_GRENINJA,
    NATIONAL_DEX_BUNNELBY,
    NATIONAL_DEX_DIGGERSBY,
    NATIONAL_DEX_FLETCHLING,
    NATIONAL_DEX_FLETCHINDER,
    NATIONAL_DEX_TALONFLAME,
    NATIONAL_DEX_SCATTERBUG,
    NATIONAL_DEX_SPEWPA,
    NATIONAL_DEX_VIVILLON,
    NATIONAL_DEX_LITLEO,
    NATIONAL_DEX_PYROAR,
    NATIONAL_DEX_FLABEBE,
    NATIONAL_DEX_FLOETTE,
    NATIONAL_DEX_FLORGES,
    NATIONAL_DEX_SKIDDO,
    NATIONAL_DEX_GOGOAT,
    NATIONAL_DEX_PANCHAM,
    NATIONAL_DEX_PANGORO,
    NATIONAL_DEX_FURFROU,
    NATIONAL_DEX_ESPURR,
    NATIONAL_DEX_MEOWSTIC,
    NATIONAL_DEX_HONEDGE,
    NATIONAL_DEX_DOUBLADE,
    NATIONAL_DEX_AEGISLASH,
    NATIONAL_DEX_SPRITZEE,
    NATIONAL_DEX_AROMATISSE,
    NATIONAL_DEX_SWIRLIX,
    NATIONAL_DEX_SLURPUFF,
    NATIONAL_DEX_INKAY,
    NATIONAL_DEX_MALAMAR,
    NATIONAL_DEX_BINACLE,
    NATIONAL_DEX_BARBARACLE,
    NATIONAL_DEX_SKRELP,
    NATIONAL_DEX_DRAGALGE,
    NATIONAL_DEX_CLAUNCHER,
    NATIONAL_DEX_CLAWITZER,
    NATIONAL_DEX_HELIOPTILE,
    NATIONAL_DEX_HELIOLISK,
    NATIONAL_DEX_TYRUNT,
    NATIONAL_DEX_TYRANTRUM,
    NATIONAL_DEX_AMAURA,
    NATIONAL_DEX_AURORUS,
    NATIONAL_DEX_SYLVEON,
    NATIONAL_DEX_HAWLUCHA,
    NATIONAL_DEX_DEDENNE,
    NATIONAL_DEX_CARBINK,
    NATIONAL_DEX_GOOMY,
    NATIONAL_DEX_SLIGGOO,
    NATIONAL_DEX_GOODRA,
    NATIONAL_DEX_KLEFKI,
    NATIONAL_DEX_PHANTUMP,
    NATIONAL_DEX_TREVENANT,
    NATIONAL_DEX_PUMPKABOO,
    NATIONAL_DEX_GOURGEIST,
    NATIONAL_DEX_BERGMITE,
    NATIONAL_DEX_AVALUGG,
    NATIONAL_DEX_NOIBAT,
    NATIONAL_DEX_NOIVERN,
    NATIONAL_DEX_XERNEAS,
    NATIONAL_DEX_YVELTAL,
    NATIONAL_DEX_ZYGARDE,
    NATIONAL_DEX_DIANCIE,
    NATIONAL_DEX_HOOPA,
    NATIONAL_DEX_VOLCANION,
    // Alola
    NATIONAL_DEX_ROWLET,
    NATIONAL_DEX_DARTRIX,
    NATIONAL_DEX_DECIDUEYE,
    NATIONAL_DEX_LITTEN,
    NATIONAL_DEX_TORRACAT,
    NATIONAL_DEX_INCINEROAR,
    NATIONAL_DEX_POPPLIO,
    NATIONAL_DEX_BRIONNE,
    NATIONAL_DEX_PRIMARINA,
    NATIONAL_DEX_PIKIPEK,
    NATIONAL_DEX_TRUMBEAK,
    NATIONAL_DEX_TOUCANNON,
    NATIONAL_DEX_YUNGOOS,
    NATIONAL_DEX_GUMSHOOS,
    NATIONAL_DEX_GRUBBIN,
    NATIONAL_DEX_CHARJABUG,
    NATIONAL_DEX_VIKAVOLT,
    NATIONAL_DEX_CRABRAWLER,
    NATIONAL_DEX_CRABOMINABLE,
    NATIONAL_DEX_ORICORIO,
    NATIONAL_DEX_CUTIEFLY,
    NATIONAL_DEX_RIBOMBEE,
    NATIONAL_DEX_ROCKRUFF,
    NATIONAL_DEX_LYCANROC,
    NATIONAL_DEX_WISHIWASHI,
    NATIONAL_DEX_MAREANIE,
    NATIONAL_DEX_TOXAPEX,
    NATIONAL_DEX_MUDBRAY,
    NATIONAL_DEX_MUDSDALE,
    NATIONAL_DEX_DEWPIDER,
    NATIONAL_DEX_ARAQUANID,
    NATIONAL_DEX_FOMANTIS,
    NATIONAL_DEX_LURANTIS,
    NATIONAL_DEX_MORELULL,
    NATIONAL_DEX_SHIINOTIC,
    NATIONAL_DEX_SALANDIT,
    NATIONAL_DEX_SALAZZLE,
    NATIONAL_DEX_STUFFUL,
    NATIONAL_DEX_BEWEAR,
    NATIONAL_DEX_BOUNSWEET,
    NATIONAL_DEX_STEENEE,
    NATIONAL_DEX_TSAREENA,
    NATIONAL_DEX_COMFEY,
    NATIONAL_DEX_ORANGURU,
    NATIONAL_DEX_PASSIMIAN,
    NATIONAL_DEX_WIMPOD,
    NATIONAL_DEX_GOLISOPOD,
    NATIONAL_DEX_SANDYGAST,
    NATIONAL_DEX_PALOSSAND,
    NATIONAL_DEX_PYUKUMUKU,
    NATIONAL_DEX_TYPE_NULL,
    NATIONAL_DEX_SILVALLY,
    NATIONAL_DEX_MINIOR,
    NATIONAL_DEX_KOMALA,
    NATIONAL_DEX_TURTONATOR,
    NATIONAL_DEX_TOGEDEMARU,
    NATIONAL_DEX_MIMIKYU,
    NATIONAL_DEX_BRUXISH,
    NATIONAL_DEX_DRAMPA,
    NATIONAL_DEX_DHELMISE,
    NATIONAL_DEX_JANGMO_O,
    NATIONAL_DEX_HAKAMO_O,
    NATIONAL_DEX_KOMMO_O,
    NATIONAL_DEX_TAPU_KOKO,
    NATIONAL_DEX_TAPU_LELE,
    NATIONAL_DEX_TAPU_BULU,
    NATIONAL_DEX_TAPU_FINI,
    NATIONAL_DEX_COSMOG,
    NATIONAL_DEX_COSMOEM,
    NATIONAL_DEX_SOLGALEO,
    NATIONAL_DEX_LUNALA,
    NATIONAL_DEX_NIHILEGO,
    NATIONAL_DEX_BUZZWOLE,
    NATIONAL_DEX_PHEROMOSA,
    NATIONAL_DEX_XURKITREE,
    NATIONAL_DEX_CELESTEELA,
    NATIONAL_DEX_KARTANA,
    NATIONAL_DEX_GUZZLORD,
    NATIONAL_DEX_NECROZMA,
    NATIONAL_DEX_MAGEARNA,
    NATIONAL_DEX_MARSHADOW,
    NATIONAL_DEX_POIPOLE,
    NATIONAL_DEX_NAGANADEL,
    NATIONAL_DEX_STAKATAKA,
    NATIONAL_DEX_BLACEPHALON,
    NATIONAL_DEX_ZERAORA,
    // Unknown
    NATIONAL_DEX_MELTAN,
    NATIONAL_DEX_MELMETAL,
    // Galar
    NATIONAL_DEX_GROOKEY,
    NATIONAL_DEX_THWACKEY,
    NATIONAL_DEX_RILLABOOM,
    NATIONAL_DEX_SCORBUNNY,
    NATIONAL_DEX_RABOOT,
    NATIONAL_DEX_CINDERACE,
    NATIONAL_DEX_SOBBLE,
    NATIONAL_DEX_DRIZZILE,
    NATIONAL_DEX_INTELEON,
    NATIONAL_DEX_SKWOVET,
    NATIONAL_DEX_GREEDENT,
    NATIONAL_DEX_ROOKIDEE,
    NATIONAL_DEX_CORVISQUIRE,
    NATIONAL_DEX_CORVIKNIGHT,
    NATIONAL_DEX_BLIPBUG,
    NATIONAL_DEX_DOTTLER,
    NATIONAL_DEX_ORBEETLE,
    NATIONAL_DEX_NICKIT,
    NATIONAL_DEX_THIEVUL,
    NATIONAL_DEX_GOSSIFLEUR,
    NATIONAL_DEX_ELDEGOSS,
    NATIONAL_DEX_WOOLOO,
    NATIONAL_DEX_DUBWOOL,
    NATIONAL_DEX_CHEWTLE,
    NATIONAL_DEX_DREDNAW,
    NATIONAL_DEX_YAMPER,
    NATIONAL_DEX_BOLTUND,
    NATIONAL_DEX_ROLYCOLY,
    NATIONAL_DEX_CARKOL,
    NATIONAL_DEX_COALOSSAL,
    NATIONAL_DEX_APPLIN,
    NATIONAL_DEX_FLAPPLE,
    NATIONAL_DEX_APPLETUN,
    NATIONAL_DEX_SILICOBRA,
    NATIONAL_DEX_SANDACONDA,
    NATIONAL_DEX_CRAMORANT,
    NATIONAL_DEX_ARROKUDA,
    NATIONAL_DEX_BARRASKEWDA,
    NATIONAL_DEX_TOXEL,
    NATIONAL_DEX_TOXTRICITY,
    NATIONAL_DEX_SIZZLIPEDE,
    NATIONAL_DEX_CENTISKORCH,
    NATIONAL_DEX_CLOBBOPUS,
    NATIONAL_DEX_GRAPPLOCT,
    NATIONAL_DEX_SINISTEA,
    NATIONAL_DEX_POLTEAGEIST,
    NATIONAL_DEX_HATENNA,
    NATIONAL_DEX_HATTREM,
    NATIONAL_DEX_HATTERENE,
    NATIONAL_DEX_IMPIDIMP,
    NATIONAL_DEX_MORGREM,
    NATIONAL_DEX_GRIMMSNARL,
    NATIONAL_DEX_OBSTAGOON,
    NATIONAL_DEX_PERRSERKER,
    NATIONAL_DEX_CURSOLA,
    NATIONAL_DEX_SIRFETCHD,
    NATIONAL_DEX_MR_RIME,
    NATIONAL_DEX_RUNERIGUS,
    NATIONAL_DEX_MILCERY,
    NATIONAL_DEX_ALCREMIE,
    NATIONAL_DEX_FALINKS,
    NATIONAL_DEX_PINCURCHIN,
    NATIONAL_DEX_SNOM,
    NATIONAL_DEX_FROSMOTH,
    NATIONAL_DEX_STONJOURNER,
    NATIONAL_DEX_EISCUE,
    NATIONAL_DEX_INDEEDEE,
    NATIONAL_DEX_MORPEKO,
    NATIONAL_DEX_CUFANT,
    NATIONAL_DEX_COPPERAJAH,
    NATIONAL_DEX_DRACOZOLT,
    NATIONAL_DEX_ARCTOZOLT,
    NATIONAL_DEX_DRACOVISH,
    NATIONAL_DEX_ARCTOVISH,
    NATIONAL_DEX_DURALUDON,
    NATIONAL_DEX_DREEPY,
    NATIONAL_DEX_DRAKLOAK,
    NATIONAL_DEX_DRAGAPULT,
    NATIONAL_DEX_ZACIAN,
    NATIONAL_DEX_ZAMAZENTA,
    NATIONAL_DEX_ETERNATUS,
    NATIONAL_DEX_KUBFU,
    NATIONAL_DEX_URSHIFU,
    NATIONAL_DEX_ZARUDE,
    NATIONAL_DEX_REGIELEKI,
    NATIONAL_DEX_REGIDRAGO,
    NATIONAL_DEX_GLASTRIER,
    NATIONAL_DEX_SPECTRIER,
    NATIONAL_DEX_CALYREX,
    NATIONAL_DEX_WYRDEER,
    NATIONAL_DEX_KLEAVOR,
    NATIONAL_DEX_URSALUNA,
    NATIONAL_DEX_BASCULEGION,
    NATIONAL_DEX_SNEASLER,
    NATIONAL_DEX_OVERQWIL,
    NATIONAL_DEX_ENAMORUS,
    NATIONAL_DEX_SPRIGATITO,
    NATIONAL_DEX_FLORAGATO,
    NATIONAL_DEX_MEOWSCARADA,
    NATIONAL_DEX_FUECOCO,
    NATIONAL_DEX_CROCALOR,
    NATIONAL_DEX_SKELEDIRGE,
    NATIONAL_DEX_QUAXLY,
    NATIONAL_DEX_QUAXWELL,
    NATIONAL_DEX_QUAQUAVAL,
    NATIONAL_DEX_LECHONK,
    NATIONAL_DEX_OINKOLOGNE,
    NATIONAL_DEX_TAROUNTULA,
    NATIONAL_DEX_SPIDOPS,
    NATIONAL_DEX_NYMBLE,
    NATIONAL_DEX_LOKIX,
    NATIONAL_DEX_PAWMI,
    NATIONAL_DEX_PAWMO,
    NATIONAL_DEX_PAWMOT,
    NATIONAL_DEX_TANDEMAUS,
    NATIONAL_DEX_MAUSHOLD,
    NATIONAL_DEX_FIDOUGH,
    NATIONAL_DEX_DACHSBUN,
    NATIONAL_DEX_SMOLIV,
    NATIONAL_DEX_DOLLIV,
    NATIONAL_DEX_ARBOLIVA,
    NATIONAL_DEX_SQUAWKABILLY,
    NATIONAL_DEX_NACLI,
    NATIONAL_DEX_NACLSTACK,
    NATIONAL_DEX_GARGANACL,
    NATIONAL_DEX_CHARCADET,
    NATIONAL_DEX_ARMAROUGE,
    NATIONAL_DEX_CERULEDGE,
    NATIONAL_DEX_TADBULB,
    NATIONAL_DEX_BELLIBOLT,
    NATIONAL_DEX_WATTREL,
    NATIONAL_DEX_KILOWATTREL,
    NATIONAL_DEX_MASCHIFF,
    NATIONAL_DEX_MABOSSTIFF,
    NATIONAL_DEX_SHROODLE,
    NATIONAL_DEX_GRAFAIAI,
    NATIONAL_DEX_BRAMBLIN,
    NATIONAL_DEX_BRAMBLEGHAST,
    NATIONAL_DEX_TOEDSCOOL,
    NATIONAL_DEX_TOEDSCRUEL,
    NATIONAL_DEX_KLAWF,
    NATIONAL_DEX_CAPSAKID,
    NATIONAL_DEX_SCOVILLAIN,
    NATIONAL_DEX_RELLOR,
    NATIONAL_DEX_RABSCA,
    NATIONAL_DEX_FLITTLE,
    NATIONAL_DEX_ESPATHRA,
    NATIONAL_DEX_TINKATINK,
    NATIONAL_DEX_TINKATUFF,
    NATIONAL_DEX_TINKATON,
    NATIONAL_DEX_WIGLETT,
    NATIONAL_DEX_WUGTRIO,
    NATIONAL_DEX_BOMBIRDIER,
    NATIONAL_DEX_FINIZEN,
    NATIONAL_DEX_PALAFIN,
    NATIONAL_DEX_VAROOM,
    NATIONAL_DEX_REVAVROOM,
    NATIONAL_DEX_CYCLIZAR,
    NATIONAL_DEX_ORTHWORM,
    NATIONAL_DEX_GLIMMET,
    NATIONAL_DEX_GLIMMORA,
    NATIONAL_DEX_GREAVARD,
    NATIONAL_DEX_HOUNDSTONE,
    NATIONAL_DEX_FLAMIGO,
    NATIONAL_DEX_CETODDLE,
    NATIONAL_DEX_CETITAN,
    NATIONAL_DEX_VELUZA,
    NATIONAL_DEX_DONDOZO,
    NATIONAL_DEX_TATSUGIRI,
    NATIONAL_DEX_ANNIHILAPE,
    NATIONAL_DEX_CLODSIRE,
    NATIONAL_DEX_FARIGIRAF,
    NATIONAL_DEX_DUDUNSPARCE,
    NATIONAL_DEX_KINGAMBIT,
    NATIONAL_DEX_GREAT_TUSK,
    NATIONAL_DEX_SCREAM_TAIL,
    NATIONAL_DEX_BRUTE_BONNET,
    NATIONAL_DEX_FLUTTER_MANE,
    NATIONAL_DEX_SLITHER_WING,
    NATIONAL_DEX_SANDY_SHOCKS,
    NATIONAL_DEX_IRON_TREADS,
    NATIONAL_DEX_IRON_BUNDLE,
    NATIONAL_DEX_IRON_HANDS,
    NATIONAL_DEX_IRON_JUGULIS,
    NATIONAL_DEX_IRON_MOTH,
    NATIONAL_DEX_IRON_THORNS,
    NATIONAL_DEX_FRIGIBAX,
    NATIONAL_DEX_ARCTIBAX,
    NATIONAL_DEX_BAXCALIBUR,
    NATIONAL_DEX_GIMMIGHOUL,
    NATIONAL_DEX_GHOLDENGO,
    NATIONAL_DEX_WO_CHIEN,
    NATIONAL_DEX_CHIEN_PAO,
    NATIONAL_DEX_TING_LU,
    NATIONAL_DEX_CHI_YU,
    NATIONAL_DEX_ROARING_MOON,
    NATIONAL_DEX_IRON_VALIANT,
    NATIONAL_DEX_KORAIDON,
    NATIONAL_DEX_MIRAIDON,
    NATIONAL_DEX_WALKING_WAKE,
    NATIONAL_DEX_IRON_LEAVES,
    NATIONAL_DEX_DIPPLIN,
    NATIONAL_DEX_POLTCHAGEIST,
    NATIONAL_DEX_SINISTCHA,
    NATIONAL_DEX_OKIDOGI,
    NATIONAL_DEX_MUNKIDORI,
    NATIONAL_DEX_FEZANDIPITI,
    NATIONAL_DEX_OGERPON,
    NATIONAL_DEX_ARCHALUDON,
    NATIONAL_DEX_HYDRAPPLE,
    NATIONAL_DEX_GOUGING_FIRE,
    NATIONAL_DEX_RAGING_BOLT,
    NATIONAL_DEX_IRON_BOULDER,
    NATIONAL_DEX_IRON_CROWN,
    NATIONAL_DEX_TERAPAGOS,
    NATIONAL_DEX_PECHARUNT,
    NATIONAL_DEX_RIKO,
    NATIONAL_DEX_BIJUU,
};

// Johto Pokedex order
enum JohtoDexOrder
{
    JOHTO_DEX_NONE,
#if P_FAMILY_BULBASAUR
    JOHTO_DEX_BULBASAUR,
    JOHTO_DEX_IVYSAUR,
    JOHTO_DEX_VENUSAUR,
#endif
#if P_FAMILY_CHARMANDER
    JOHTO_DEX_CHARMANDER,
    JOHTO_DEX_CHARMELEON,
    JOHTO_DEX_CHARIZARD,
#endif
#if P_FAMILY_SQUIRTLE
    JOHTO_DEX_SQUIRTLE,
    JOHTO_DEX_WARTORTLE,
    JOHTO_DEX_BLASTOISE,
#endif
#if P_FAMILY_CATERPIE
    JOHTO_DEX_CATERPIE,
    JOHTO_DEX_METAPOD,
    JOHTO_DEX_BUTTERFREE,
#endif
#if P_FAMILY_WEEDLE
    JOHTO_DEX_WEEDLE,
    JOHTO_DEX_KAKUNA,
    JOHTO_DEX_BEEDRILL,
#endif
#if P_FAMILY_PIDGEY
    JOHTO_DEX_PIDGEY,
    JOHTO_DEX_PIDGEOTTO,
    JOHTO_DEX_PIDGEOT,
#endif
#if P_FAMILY_RATTATA
    JOHTO_DEX_RATTATA,
    JOHTO_DEX_RATICATE,
#endif
#if P_FAMILY_SPEAROW
    JOHTO_DEX_SPEAROW,
    JOHTO_DEX_FEAROW,
#endif
#if P_FAMILY_EKANS
    JOHTO_DEX_EKANS,
    JOHTO_DEX_ARBOK,
#endif
#if P_FAMILY_PIKACHU
    JOHTO_DEX_PIKACHU,
    JOHTO_DEX_RAICHU,
#endif
#if P_FAMILY_SANDSHREW
    JOHTO_DEX_SANDSHREW,
    JOHTO_DEX_SANDSLASH,
#endif
#if P_FAMILY_NIDORAN
    JOHTO_DEX_NIDORAN_F,
    JOHTO_DEX_NIDORINA,
    JOHTO_DEX_NIDOQUEEN,
    JOHTO_DEX_NIDORAN_M,
    JOHTO_DEX_NIDORINO,
    JOHTO_DEX_NIDOKING,
#endif
#if P_FAMILY_CLEFAIRY
    JOHTO_DEX_CLEFAIRY,
    JOHTO_DEX_CLEFABLE,
#endif
#if P_FAMILY_VULPIX
    JOHTO_DEX_VULPIX,
    JOHTO_DEX_NINETALES,
#endif
#if P_FAMILY_JIGGLYPUFF
    JOHTO_DEX_JIGGLYPUFF,
    JOHTO_DEX_WIGGLYTUFF,
#endif
#if P_FAMILY_ZUBAT
    JOHTO_DEX_ZUBAT,
    JOHTO_DEX_GOLBAT,
#endif
#if P_FAMILY_ODDISH
    JOHTO_DEX_ODDISH,
    JOHTO_DEX_GLOOM,
    JOHTO_DEX_VILEPLUME,
#endif
#if P_FAMILY_PARAS
    JOHTO_DEX_PARAS,
    JOHTO_DEX_PARASECT,
#endif
#if P_FAMILY_VENONAT
    JOHTO_DEX_VENONAT,
    JOHTO_DEX_VENOMOTH,
#endif
#if P_FAMILY_DIGLETT
    JOHTO_DEX_DIGLETT,
    JOHTO_DEX_DUGTRIO,
#endif
#if P_FAMILY_MEOWTH
    JOHTO_DEX_MEOWTH,
    JOHTO_DEX_PERSIAN,
#endif
#if P_FAMILY_PSYDUCK
    JOHTO_DEX_PSYDUCK,
    JOHTO_DEX_GOLDUCK,
#endif
#if P_FAMILY_MANKEY
    JOHTO_DEX_MANKEY,
    JOHTO_DEX_PRIMEAPE,
#endif
#if P_FAMILY_GROWLITHE
    JOHTO_DEX_GROWLITHE,
    JOHTO_DEX_ARCANINE,
#endif
#if P_FAMILY_POLIWAG
    JOHTO_DEX_POLIWAG,
    JOHTO_DEX_POLIWHIRL,
    JOHTO_DEX_POLIWRATH,
#endif
#if P_FAMILY_ABRA
    JOHTO_DEX_ABRA,
    JOHTO_DEX_KADABRA,
    JOHTO_DEX_ALAKAZAM,
#endif
#if P_FAMILY_MACHOP
    JOHTO_DEX_MACHOP,
    JOHTO_DEX_MACHOKE,
    JOHTO_DEX_MACHAMP,
#endif
#if P_FAMILY_BELLSPROUT
    JOHTO_DEX_BELLSPROUT,
    JOHTO_DEX_WEEPINBELL,
    JOHTO_DEX_VICTREEBEL,
#endif
#if P_FAMILY_TENTACOOL
    JOHTO_DEX_TENTACOOL,
    JOHTO_DEX_TENTACRUEL,
#endif
#if P_FAMILY_GEODUDE
    JOHTO_DEX_GEODUDE,
    JOHTO_DEX_GRAVELER,
    JOHTO_DEX_GOLEM,
#endif
#if P_FAMILY_PONYTA
    JOHTO_DEX_PONYTA,
    JOHTO_DEX_RAPIDASH,
#endif
#if P_FAMILY_SLOWPOKE
    JOHTO_DEX_SLOWPOKE,
    JOHTO_DEX_SLOWBRO,
#endif
#if P_FAMILY_MAGNEMITE
    JOHTO_DEX_MAGNEMITE,
    JOHTO_DEX_MAGNETON,
#endif
#if P_FAMILY_FARFETCHD
    JOHTO_DEX_FARFETCHD,
#endif
#if P_FAMILY_DODUO
    JOHTO_DEX_DODUO,
    JOHTO_DEX_DODRIO,
#endif
#if P_FAMILY_SEEL
    JOHTO_DEX_SEEL,
    JOHTO_DEX_DEWGONG,
#endif
#if P_FAMILY_GRIMER
    JOHTO_DEX_GRIMER,
    JOHTO_DEX_MUK,
#endif
#if P_FAMILY_SHELLDER
    JOHTO_DEX_SHELLDER,
    JOHTO_DEX_CLOYSTER,
#endif
#if P_FAMILY_GASTLY
    JOHTO_DEX_GASTLY,
    JOHTO_DEX_HAUNTER,
    JOHTO_DEX_GENGAR,
#endif
#if P_FAMILY_ONIX
    JOHTO_DEX_ONIX,
#endif
#if P_FAMILY_DROWZEE
    JOHTO_DEX_DROWZEE,
    JOHTO_DEX_HYPNO,
#endif
#if P_FAMILY_KRABBY
    JOHTO_DEX_KRABBY,
    JOHTO_DEX_KINGLER,
#endif
#if P_FAMILY_VOLTORB
    JOHTO_DEX_VOLTORB,
    JOHTO_DEX_ELECTRODE,
#endif
#if P_FAMILY_EXEGGCUTE
    JOHTO_DEX_EXEGGCUTE,
    JOHTO_DEX_EXEGGUTOR,
#endif
#if P_FAMILY_CUBONE
    JOHTO_DEX_CUBONE,
    JOHTO_DEX_MAROWAK,
#endif
#if P_FAMILY_HITMONS
    JOHTO_DEX_HITMONLEE,
    JOHTO_DEX_HITMONCHAN,
#endif
#if P_FAMILY_LICKITUNG
    JOHTO_DEX_LICKITUNG,
#endif
#if P_FAMILY_KOFFING
    JOHTO_DEX_KOFFING,
    JOHTO_DEX_WEEZING,
#endif
#if P_FAMILY_RHYHORN
    JOHTO_DEX_RHYHORN,
    JOHTO_DEX_RHYDON,
#endif
#if P_FAMILY_CHANSEY
    JOHTO_DEX_CHANSEY,
#endif
#if P_FAMILY_TANGELA
    JOHTO_DEX_TANGELA,
#endif
#if P_FAMILY_KANGASKHAN
    JOHTO_DEX_KANGASKHAN,
#endif
#if P_FAMILY_HORSEA
    JOHTO_DEX_HORSEA,
    JOHTO_DEX_SEADRA,
#endif
#if P_FAMILY_GOLDEEN
    JOHTO_DEX_GOLDEEN,
    JOHTO_DEX_SEAKING,
#endif
#if P_FAMILY_STARYU
    JOHTO_DEX_STARYU,
    JOHTO_DEX_STARMIE,
#endif
#if P_FAMILY_MR_MIME
    JOHTO_DEX_MR_MIME,
#endif
#if P_FAMILY_SCYTHER
    JOHTO_DEX_SCYTHER,
#endif
#if P_FAMILY_JYNX
    JOHTO_DEX_JYNX,
#endif
#if P_FAMILY_ELECTABUZZ
    JOHTO_DEX_ELECTABUZZ,
#endif
#if P_FAMILY_MAGMAR
    JOHTO_DEX_MAGMAR,
#endif
#if P_FAMILY_PINSIR
    JOHTO_DEX_PINSIR,
#endif
#if P_FAMILY_TAUROS
    JOHTO_DEX_TAUROS,
#endif
#if P_FAMILY_MAGIKARP
    JOHTO_DEX_MAGIKARP,
    JOHTO_DEX_GYARADOS,
#endif
#if P_FAMILY_LAPRAS
    JOHTO_DEX_LAPRAS,
#endif
#if P_FAMILY_DITTO
    JOHTO_DEX_DITTO,
#endif
#if P_FAMILY_EEVEE
    JOHTO_DEX_EEVEE,
    JOHTO_DEX_VAPOREON,
    JOHTO_DEX_JOLTEON,
    JOHTO_DEX_FLAREON,
#endif
#if P_FAMILY_PORYGON
    JOHTO_DEX_PORYGON,
#endif
#if P_FAMILY_OMANYTE
    JOHTO_DEX_OMANYTE,
    JOHTO_DEX_OMASTAR,
#endif
#if P_FAMILY_KABUTO
    JOHTO_DEX_KABUTO,
    JOHTO_DEX_KABUTOPS,
#endif
#if P_FAMILY_AERODACTYL
    JOHTO_DEX_AERODACTYL,
#endif
#if P_FAMILY_SNORLAX
    JOHTO_DEX_SNORLAX,
#endif
#if P_FAMILY_ARTICUNO
    JOHTO_DEX_ARTICUNO,
#endif
#if P_FAMILY_ZAPDOS
    JOHTO_DEX_ZAPDOS,
#endif
#if P_FAMILY_MOLTRES
    JOHTO_DEX_MOLTRES,
#endif
#if P_FAMILY_DRATINI
    JOHTO_DEX_DRATINI,
    JOHTO_DEX_DRAGONAIR,
    JOHTO_DEX_DRAGONITE,
#endif
#if P_FAMILY_MEWTWO
    JOHTO_DEX_MEWTWO,
#endif
#if P_FAMILY_MEW
    JOHTO_DEX_MEW,
#endif
#if P_FAMILY_CHIKORITA
    JOHTO_DEX_CHIKORITA,
    JOHTO_DEX_BAYLEEF,
    JOHTO_DEX_MEGANIUM,
#endif
#if P_FAMILY_CYNDAQUIL
    JOHTO_DEX_CYNDAQUIL,
    JOHTO_DEX_QUILAVA,
    JOHTO_DEX_TYPHLOSION,
#endif
#if P_FAMILY_TOTODILE
    JOHTO_DEX_TOTODILE,
    JOHTO_DEX_CROCONAW,
    JOHTO_DEX_FERALIGATR,
#endif
#if P_FAMILY_SENTRET
    JOHTO_DEX_SENTRET,
    JOHTO_DEX_FURRET,
#endif
#if P_FAMILY_HOOTHOOT
    JOHTO_DEX_HOOTHOOT,
    JOHTO_DEX_NOCTOWL,
#endif
#if P_FAMILY_LEDYBA
    JOHTO_DEX_LEDYBA,
    JOHTO_DEX_LEDIAN,
#endif
#if P_FAMILY_SPINARAK
    JOHTO_DEX_SPINARAK,
    JOHTO_DEX_ARIADOS,
#endif
#if P_FAMILY_ZUBAT && P_GEN_2_CROSS_EVOS
    JOHTO_DEX_CROBAT,
#endif
#if P_FAMILY_CHINCHOU
    JOHTO_DEX_CHINCHOU,
    JOHTO_DEX_LANTURN,
#endif
#if P_FAMILY_PIKACHU && P_GEN_2_CROSS_EVOS
    JOHTO_DEX_PICHU,
#endif
#if P_FAMILY_CLEFAIRY && P_GEN_2_CROSS_EVOS
    JOHTO_DEX_CLEFFA,
#endif
#if P_FAMILY_JIGGLYPUFF && P_GEN_2_CROSS_EVOS
    JOHTO_DEX_IGGLYBUFF,
#endif
#if P_FAMILY_TOGEPI
    JOHTO_DEX_TOGEPI,
    JOHTO_DEX_TOGETIC,
#endif
#if P_FAMILY_NATU
    JOHTO_DEX_NATU,
    JOHTO_DEX_XATU,
#endif
#if P_FAMILY_MAREEP
    JOHTO_DEX_MAREEP,
    JOHTO_DEX_FLAAFFY,
    JOHTO_DEX_AMPHAROS,
#endif
#if P_FAMILY_ODDISH && P_GEN_2_CROSS_EVOS
    JOHTO_DEX_BELLOSSOM,
#endif
#if P_FAMILY_MARILL
    JOHTO_DEX_MARILL,
    JOHTO_DEX_AZUMARILL,
#endif
#if P_FAMILY_SUDOWOODO
    JOHTO_DEX_SUDOWOODO,
#endif
#if P_FAMILY_POLIWAG && P_GEN_2_CROSS_EVOS
    JOHTO_DEX_POLITOED,
#endif
#if P_FAMILY_HOPPIP
    JOHTO_DEX_HOPPIP,
    JOHTO_DEX_SKIPLOOM,
    JOHTO_DEX_JUMPLUFF,
#endif
#if P_FAMILY_AIPOM
    JOHTO_DEX_AIPOM,
#endif
#if P_FAMILY_SUNKERN
    JOHTO_DEX_SUNKERN,
    JOHTO_DEX_SUNFLORA,
#endif
#if P_FAMILY_YANMA
    JOHTO_DEX_YANMA,
#endif
#if P_FAMILY_WOOPER
    JOHTO_DEX_WOOPER,
    JOHTO_DEX_QUAGSIRE,
#endif
#if P_FAMILY_EEVEE && P_GEN_2_CROSS_EVOS
    JOHTO_DEX_ESPEON,
    JOHTO_DEX_UMBREON,
#endif
#if P_FAMILY_MURKROW
    JOHTO_DEX_MURKROW,
#endif
#if P_FAMILY_SLOWPOKE && P_GEN_2_CROSS_EVOS
    JOHTO_DEX_SLOWKING,
#endif
#if P_FAMILY_MISDREAVUS
    JOHTO_DEX_MISDREAVUS,
#endif
#if P_FAMILY_UNOWN
    JOHTO_DEX_UNOWN,
#endif
#if P_FAMILY_WOBBUFFET
    JOHTO_DEX_WOBBUFFET,
#endif
#if P_FAMILY_GIRAFARIG
    JOHTO_DEX_GIRAFARIG,
#endif
#if P_FAMILY_PINECO
    JOHTO_DEX_PINECO,
    JOHTO_DEX_FORRETRESS,
#endif
#if P_FAMILY_DUNSPARCE
    JOHTO_DEX_DUNSPARCE,
#endif
#if P_FAMILY_GLIGAR
    JOHTO_DEX_GLIGAR,
#endif
#if P_FAMILY_ONIX && P_GEN_2_CROSS_EVOS
    JOHTO_DEX_STEELIX,
#endif
#if P_FAMILY_SNUBBULL
    JOHTO_DEX_SNUBBULL,
    JOHTO_DEX_GRANBULL,
#endif
#if P_FAMILY_QWILFISH
    JOHTO_DEX_QWILFISH,
#endif
#if P_FAMILY_SCYTHER && P_GEN_2_CROSS_EVOS
    JOHTO_DEX_SCIZOR,
#endif
#if P_FAMILY_SHUCKLE
    JOHTO_DEX_SHUCKLE,
#endif
#if P_FAMILY_HERACROSS
    JOHTO_DEX_HERACROSS,
#endif
#if P_FAMILY_SNEASEL
    JOHTO_DEX_SNEASEL,
#endif
#if P_FAMILY_TEDDIURSA
    JOHTO_DEX_TEDDIURSA,
    JOHTO_DEX_URSARING,
#endif
#if P_FAMILY_SLUGMA
    JOHTO_DEX_SLUGMA,
    JOHTO_DEX_MAGCARGO,
#endif
#if P_FAMILY_SWINUB
    JOHTO_DEX_SWINUB,
    JOHTO_DEX_PILOSWINE,
#endif
#if P_FAMILY_CORSOLA
    JOHTO_DEX_CORSOLA,
#endif
#if P_FAMILY_REMORAID
    JOHTO_DEX_REMORAID,
    JOHTO_DEX_OCTILLERY,
#endif
#if P_FAMILY_DELIBIRD
    JOHTO_DEX_DELIBIRD,
#endif
#if P_FAMILY_MANTINE
    JOHTO_DEX_MANTINE,
#endif
#if P_FAMILY_SKARMORY
    JOHTO_DEX_SKARMORY,
#endif
#if P_FAMILY_HOUNDOUR
    JOHTO_DEX_HOUNDOUR,
    JOHTO_DEX_HOUNDOOM,
#endif
#if P_FAMILY_HORSEA && P_GEN_2_CROSS_EVOS
    JOHTO_DEX_KINGDRA,
#endif
#if P_FAMILY_PHANPY
    JOHTO_DEX_PHANPY,
    JOHTO_DEX_DONPHAN,
#endif
#if P_FAMILY_PORYGON && P_GEN_2_CROSS_EVOS
    JOHTO_DEX_PORYGON2,
#endif
#if P_FAMILY_STANTLER
    JOHTO_DEX_STANTLER,
#endif
#if P_FAMILY_SMEARGLE
    JOHTO_DEX_SMEARGLE,
#endif
#if P_FAMILY_HITMONS && P_GEN_2_CROSS_EVOS
    JOHTO_DEX_TYROGUE,
    JOHTO_DEX_HITMONTOP,
#endif
#if P_FAMILY_JYNX && P_GEN_2_CROSS_EVOS
    JOHTO_DEX_SMOOCHUM,
#endif
#if P_FAMILY_ELECTABUZZ && P_GEN_2_CROSS_EVOS
    JOHTO_DEX_ELEKID,
#endif
#if P_FAMILY_MAGMAR && P_GEN_2_CROSS_EVOS
    JOHTO_DEX_MAGBY,
#endif
#if P_FAMILY_MILTANK
    JOHTO_DEX_MILTANK,
#endif
#if P_FAMILY_CHANSEY && P_GEN_2_CROSS_EVOS
    JOHTO_DEX_BLISSEY,
#endif
#if P_FAMILY_RAIKOU
    JOHTO_DEX_RAIKOU,
#endif
#if P_FAMILY_ENTEI
    JOHTO_DEX_ENTEI,
#endif
#if P_FAMILY_SUICUNE
    JOHTO_DEX_SUICUNE,
#endif
#if P_FAMILY_LARVITAR
    JOHTO_DEX_LARVITAR,
    JOHTO_DEX_PUPITAR,
    JOHTO_DEX_TYRANITAR,
#endif
#if P_FAMILY_LUGIA
    JOHTO_DEX_LUGIA,
#endif
#if P_FAMILY_HO_OH
    JOHTO_DEX_HO_OH,
#endif
#if P_FAMILY_CELEBI
    JOHTO_DEX_CELEBI,
#endif
#if P_FAMILY_TREECKO
    JOHTO_DEX_TREECKO,
    JOHTO_DEX_GROVYLE,
    JOHTO_DEX_SCEPTILE,
#endif
#if P_FAMILY_TORCHIC
    JOHTO_DEX_TORCHIC,
    JOHTO_DEX_COMBUSKEN,
    JOHTO_DEX_BLAZIKEN,
#endif
#if P_FAMILY_MUDKIP
    JOHTO_DEX_MUDKIP,
    JOHTO_DEX_MARSHTOMP,
    JOHTO_DEX_SWAMPERT,
#endif
#if P_FAMILY_POOCHYENA
    JOHTO_DEX_POOCHYENA,
    JOHTO_DEX_MIGHTYENA,
#endif
#if P_FAMILY_ZIGZAGOON
    JOHTO_DEX_ZIGZAGOON,
    JOHTO_DEX_LINOONE,
#endif
#if P_FAMILY_WURMPLE
    JOHTO_DEX_WURMPLE,
    JOHTO_DEX_SILCOON,
    JOHTO_DEX_BEAUTIFLY,
    JOHTO_DEX_CASCOON,
    JOHTO_DEX_DUSTOX,
#endif
#if P_FAMILY_LOTAD
    JOHTO_DEX_LOTAD,
    JOHTO_DEX_LOMBRE,
    JOHTO_DEX_LUDICOLO,
#endif
#if P_FAMILY_SEEDOT
    JOHTO_DEX_SEEDOT,
    JOHTO_DEX_NUZLEAF,
    JOHTO_DEX_SHIFTRY,
#endif
#if P_FAMILY_TAILLOW
    JOHTO_DEX_TAILLOW,
    JOHTO_DEX_SWELLOW,
#endif
#if P_FAMILY_WINGULL
    JOHTO_DEX_WINGULL,
    JOHTO_DEX_PELIPPER,
#endif
#if P_FAMILY_RALTS
    JOHTO_DEX_RALTS,
    JOHTO_DEX_KIRLIA,
    JOHTO_DEX_GARDEVOIR,
#endif
#if P_FAMILY_SURSKIT
    JOHTO_DEX_SURSKIT,
    JOHTO_DEX_MASQUERAIN,
#endif
#if P_FAMILY_SHROOMISH
    JOHTO_DEX_SHROOMISH,
    JOHTO_DEX_BRELOOM,
#endif
#if P_FAMILY_SLAKOTH
    JOHTO_DEX_SLAKOTH,
    JOHTO_DEX_VIGOROTH,
    JOHTO_DEX_SLAKING,
#endif
#if P_FAMILY_NINCADA
    JOHTO_DEX_NINCADA,
    JOHTO_DEX_NINJASK,
    JOHTO_DEX_SHEDINJA,
#endif
#if P_FAMILY_WHISMUR
    JOHTO_DEX_WHISMUR,
    JOHTO_DEX_LOUDRED,
    JOHTO_DEX_EXPLOUD,
#endif
#if P_FAMILY_MAKUHITA
    JOHTO_DEX_MAKUHITA,
    JOHTO_DEX_HARIYAMA,
#endif
#if P_FAMILY_MARILL && P_GEN_3_CROSS_EVOS
    JOHTO_DEX_AZURILL,
#endif
#if P_FAMILY_NOSEPASS
    JOHTO_DEX_NOSEPASS,
#endif
#if P_FAMILY_SKITTY
    JOHTO_DEX_SKITTY,
    JOHTO_DEX_DELCATTY,
#endif
#if P_FAMILY_SABLEYE
    JOHTO_DEX_SABLEYE,
#endif
#if P_FAMILY_MAWILE
    JOHTO_DEX_MAWILE,
#endif
#if P_FAMILY_ARON
    JOHTO_DEX_ARON,
    JOHTO_DEX_LAIRON,
    JOHTO_DEX_AGGRON,
#endif
#if P_FAMILY_MEDITITE
    JOHTO_DEX_MEDITITE,
    JOHTO_DEX_MEDICHAM,
#endif
#if P_FAMILY_ELECTRIKE
    JOHTO_DEX_ELECTRIKE,
    JOHTO_DEX_MANECTRIC,
#endif
#if P_FAMILY_PLUSLE
    JOHTO_DEX_PLUSLE,
#endif
#if P_FAMILY_MINUN
    JOHTO_DEX_MINUN,
#endif
#if P_FAMILY_VOLBEAT_ILLUMISE
    JOHTO_DEX_VOLBEAT,
    JOHTO_DEX_ILLUMISE,
#endif
#if P_FAMILY_ROSELIA
    JOHTO_DEX_ROSELIA,
#endif
#if P_FAMILY_GULPIN
    JOHTO_DEX_GULPIN,
    JOHTO_DEX_SWALOT,
#endif
#if P_FAMILY_CARVANHA
    JOHTO_DEX_CARVANHA,
    JOHTO_DEX_SHARPEDO,
#endif
#if P_FAMILY_WAILMER
    JOHTO_DEX_WAILMER,
    JOHTO_DEX_WAILORD,
#endif
#if P_FAMILY_NUMEL
    JOHTO_DEX_NUMEL,
    JOHTO_DEX_CAMERUPT,
#endif
#if P_FAMILY_TORKOAL
    JOHTO_DEX_TORKOAL,
#endif
#if P_FAMILY_SPOINK
    JOHTO_DEX_SPOINK,
    JOHTO_DEX_GRUMPIG,
#endif
#if P_FAMILY_SPINDA
    JOHTO_DEX_SPINDA,
#endif
#if P_FAMILY_TRAPINCH
    JOHTO_DEX_TRAPINCH,
    JOHTO_DEX_VIBRAVA,
    JOHTO_DEX_FLYGON,
#endif
#if P_FAMILY_CACNEA
    JOHTO_DEX_CACNEA,
    JOHTO_DEX_CACTURNE,
#endif
#if P_FAMILY_SWABLU
    JOHTO_DEX_SWABLU,
    JOHTO_DEX_ALTARIA,
#endif
#if P_FAMILY_ZANGOOSE
    JOHTO_DEX_ZANGOOSE,
#endif
#if P_FAMILY_SEVIPER
    JOHTO_DEX_SEVIPER,
#endif
#if P_FAMILY_LUNATONE
    JOHTO_DEX_LUNATONE,
#endif
#if P_FAMILY_SOLROCK
    JOHTO_DEX_SOLROCK,
#endif
#if P_FAMILY_BARBOACH
    JOHTO_DEX_BARBOACH,
    JOHTO_DEX_WHISCASH,
#endif
#if P_FAMILY_CORPHISH
    JOHTO_DEX_CORPHISH,
    JOHTO_DEX_CRAWDAUNT,
#endif
#if P_FAMILY_BALTOY
    JOHTO_DEX_BALTOY,
    JOHTO_DEX_CLAYDOL,
#endif
#if P_FAMILY_LILEEP
    JOHTO_DEX_LILEEP,
    JOHTO_DEX_CRADILY,
#endif
#if P_FAMILY_ANORITH
    JOHTO_DEX_ANORITH,
    JOHTO_DEX_ARMALDO,
#endif
#if P_FAMILY_FEEBAS
    JOHTO_DEX_FEEBAS,
    JOHTO_DEX_MILOTIC,
#endif
#if P_FAMILY_CASTFORM
    JOHTO_DEX_CASTFORM,
#endif
#if P_FAMILY_KECLEON
    JOHTO_DEX_KECLEON,
#endif
#if P_FAMILY_SHUPPET
    JOHTO_DEX_SHUPPET,
    JOHTO_DEX_BANETTE,
#endif
#if P_FAMILY_DUSKULL
    JOHTO_DEX_DUSKULL,
    JOHTO_DEX_DUSCLOPS,
#endif
#if P_FAMILY_TROPIUS
    JOHTO_DEX_TROPIUS,
#endif
#if P_FAMILY_CHIMECHO
    JOHTO_DEX_CHIMECHO,
#endif
#if P_FAMILY_ABSOL
    JOHTO_DEX_ABSOL,
#endif
#if P_FAMILY_WOBBUFFET && P_GEN_3_CROSS_EVOS
    JOHTO_DEX_WYNAUT,
#endif
#if P_FAMILY_SNORUNT
    JOHTO_DEX_SNORUNT,
    JOHTO_DEX_GLALIE,
#endif
#if P_FAMILY_SPHEAL
    JOHTO_DEX_SPHEAL,
    JOHTO_DEX_SEALEO,
    JOHTO_DEX_WALREIN,
#endif
#if P_FAMILY_CLAMPERL
    JOHTO_DEX_CLAMPERL,
    JOHTO_DEX_HUNTAIL,
    JOHTO_DEX_GOREBYSS,
#endif
#if P_FAMILY_RELICANTH
    JOHTO_DEX_RELICANTH,
#endif
#if P_FAMILY_LUVDISC
    JOHTO_DEX_LUVDISC,
#endif
#if P_FAMILY_BAGON
    JOHTO_DEX_BAGON,
    JOHTO_DEX_SHELGON,
    JOHTO_DEX_SALAMENCE,
#endif
#if P_FAMILY_BELDUM
    JOHTO_DEX_BELDUM,
    JOHTO_DEX_METANG,
    JOHTO_DEX_METAGROSS,
#endif
#if P_FAMILY_REGIROCK
    JOHTO_DEX_REGIROCK,
#endif
#if P_FAMILY_REGICE
    JOHTO_DEX_REGICE,
#endif
#if P_FAMILY_REGISTEEL
    JOHTO_DEX_REGISTEEL,
#endif
#if P_FAMILY_LATIAS
    JOHTO_DEX_LATIAS,
#endif
#if P_FAMILY_LATIOS
    JOHTO_DEX_LATIOS,
#endif
#if P_FAMILY_KYOGRE
    JOHTO_DEX_KYOGRE,
#endif
#if P_FAMILY_GROUDON
    JOHTO_DEX_GROUDON,
#endif
#if P_FAMILY_RAYQUAZA
    JOHTO_DEX_RAYQUAZA,
#endif
#if P_FAMILY_JIRACHI
    JOHTO_DEX_JIRACHI,
#endif
#if P_FAMILY_DEOXYS
    JOHTO_DEX_DEOXYS,
#endif
#if P_FAMILY_TURTWIG
    JOHTO_DEX_TURTWIG,
    JOHTO_DEX_GROTLE,
    JOHTO_DEX_TORTERRA,
#endif
#if P_FAMILY_CHIMCHAR
    JOHTO_DEX_CHIMCHAR,
    JOHTO_DEX_MONFERNO,
    JOHTO_DEX_INFERNAPE,
#endif
#if P_FAMILY_PIPLUP
    JOHTO_DEX_PIPLUP,
    JOHTO_DEX_PRINPLUP,
    JOHTO_DEX_EMPOLEON,
#endif
#if P_FAMILY_STARLY
    JOHTO_DEX_STARLY,
    JOHTO_DEX_STARAVIA,
    JOHTO_DEX_STARAPTOR,
#endif
#if P_FAMILY_BIDOOF
    JOHTO_DEX_BIDOOF,
    JOHTO_DEX_BIBAREL,
#endif
#if P_FAMILY_KRICKETOT
    JOHTO_DEX_KRICKETOT,
    JOHTO_DEX_KRICKETUNE,
#endif
#if P_FAMILY_SHINX
    JOHTO_DEX_SHINX,
    JOHTO_DEX_LUXIO,
    JOHTO_DEX_LUXRAY,
#endif
#if P_FAMILY_ROSELIA && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_BUDEW,
    JOHTO_DEX_ROSERADE,
#endif
#if P_FAMILY_CRANIDOS
    JOHTO_DEX_CRANIDOS,
    JOHTO_DEX_RAMPARDOS,
#endif
#if P_FAMILY_SHIELDON
    JOHTO_DEX_SHIELDON,
    JOHTO_DEX_BASTIODON,
#endif
#if P_FAMILY_BURMY
    JOHTO_DEX_BURMY,
    JOHTO_DEX_WORMADAM,
    JOHTO_DEX_MOTHIM,
#endif
#if P_FAMILY_COMBEE
    JOHTO_DEX_COMBEE,
    JOHTO_DEX_VESPIQUEN,
#endif
#if P_FAMILY_PACHIRISU
    JOHTO_DEX_PACHIRISU,
#endif
#if P_FAMILY_BUIZEL
    JOHTO_DEX_BUIZEL,
    JOHTO_DEX_FLOATZEL,
#endif
#if P_FAMILY_CHERUBI
    JOHTO_DEX_CHERUBI,
    JOHTO_DEX_CHERRIM,
#endif
#if P_FAMILY_SHELLOS
    JOHTO_DEX_SHELLOS,
    JOHTO_DEX_GASTRODON,
#endif
#if P_FAMILY_AIPOM && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_AMBIPOM,
#endif
#if P_FAMILY_DRIFLOON
    JOHTO_DEX_DRIFLOON,
    JOHTO_DEX_DRIFBLIM,
#endif
#if P_FAMILY_BUNEARY
    JOHTO_DEX_BUNEARY,
    JOHTO_DEX_LOPUNNY,
#endif
#if P_FAMILY_MISDREAVUS && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_MISMAGIUS,
#endif
#if P_FAMILY_MURKROW && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_HONCHKROW,
#endif
#if P_FAMILY_GLAMEOW
    JOHTO_DEX_GLAMEOW,
    JOHTO_DEX_PURUGLY,
#endif
#if P_FAMILY_CHIMECHO && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_CHINGLING,
#endif
#if P_FAMILY_STUNKY
    JOHTO_DEX_STUNKY,
    JOHTO_DEX_SKUNTANK,
#endif
#if P_FAMILY_BRONZOR
    JOHTO_DEX_BRONZOR,
    JOHTO_DEX_BRONZONG,
#endif
#if P_FAMILY_SUDOWOODO && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_BONSLY,
#endif
#if P_FAMILY_MR_MIME && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_MIME_JR,
#endif
#if P_FAMILY_CHANSEY && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_HAPPINY,
#endif
#if P_FAMILY_CHATOT
    JOHTO_DEX_CHATOT,
#endif
#if P_FAMILY_SPIRITOMB
    JOHTO_DEX_SPIRITOMB,
#endif
#if P_FAMILY_GIBLE
    JOHTO_DEX_GIBLE,
    JOHTO_DEX_GABITE,
    JOHTO_DEX_GARCHOMP,
#endif
#if P_FAMILY_SNORLAX && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_MUNCHLAX,
#endif
#if P_FAMILY_RIOLU
    JOHTO_DEX_RIOLU,
    JOHTO_DEX_LUCARIO,
#endif
#if P_FAMILY_HIPPOPOTAS
    JOHTO_DEX_HIPPOPOTAS,
    JOHTO_DEX_HIPPOWDON,
#endif
#if P_FAMILY_SKORUPI
    JOHTO_DEX_SKORUPI,
    JOHTO_DEX_DRAPION,
#endif
#if P_FAMILY_CROAGUNK
    JOHTO_DEX_CROAGUNK,
    JOHTO_DEX_TOXICROAK,
#endif
#if P_FAMILY_CARNIVINE
    JOHTO_DEX_CARNIVINE,
#endif
#if P_FAMILY_FINNEON
    JOHTO_DEX_FINNEON,
    JOHTO_DEX_LUMINEON,
#endif
#if P_FAMILY_MANTINE && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_MANTYKE,
#endif
#if P_FAMILY_SNOVER
    JOHTO_DEX_SNOVER,
    JOHTO_DEX_ABOMASNOW,
#endif
#if P_FAMILY_SNEASEL && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_WEAVILE,
#endif
#if P_FAMILY_MAGNEMITE && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_MAGNEZONE,
#endif
#if P_FAMILY_LICKITUNG && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_LICKILICKY,
#endif
#if P_FAMILY_RHYHORN && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_RHYPERIOR,
#endif
#if P_FAMILY_TANGELA && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_TANGROWTH,
#endif
#if P_FAMILY_ELECTABUZZ && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_ELECTIVIRE,
#endif
#if P_FAMILY_MAGMAR && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_MAGMORTAR,
#endif
#if P_FAMILY_TOGEPI && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_TOGEKISS,
#endif
#if P_FAMILY_YANMA && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_YANMEGA,
#endif
#if P_FAMILY_EEVEE && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_LEAFEON,
    JOHTO_DEX_GLACEON,
#endif
#if P_FAMILY_GLIGAR && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_GLISCOR,
#endif
#if P_FAMILY_SWINUB && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_MAMOSWINE,
#endif
#if P_FAMILY_PORYGON && P_GEN_2_CROSS_EVOS && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_PORYGON_Z,
#endif
#if P_FAMILY_RALTS && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_GALLADE,
#endif
#if P_FAMILY_NOSEPASS && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_PROBOPASS,
#endif
#if P_FAMILY_DUSKULL && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_DUSKNOIR,
#endif
#if P_FAMILY_SNORUNT && P_GEN_4_CROSS_EVOS
    JOHTO_DEX_FROSLASS,
#endif
#if P_FAMILY_ROTOM
    JOHTO_DEX_ROTOM,
#endif
#if P_FAMILY_UXIE
    JOHTO_DEX_UXIE,
#endif
#if P_FAMILY_MESPRIT
    JOHTO_DEX_MESPRIT,
#endif
#if P_FAMILY_AZELF
    JOHTO_DEX_AZELF,
#endif
#if P_FAMILY_DIALGA
    JOHTO_DEX_DIALGA,
#endif
#if P_FAMILY_PALKIA
    JOHTO_DEX_PALKIA,
#endif
#if P_FAMILY_HEATRAN
    JOHTO_DEX_HEATRAN,
#endif
#if P_FAMILY_REGIGIGAS
    JOHTO_DEX_REGIGIGAS,
#endif
#if P_FAMILY_GIRATINA
    JOHTO_DEX_GIRATINA,
#endif
#if P_FAMILY_CRESSELIA
    JOHTO_DEX_CRESSELIA,
#endif
#if P_FAMILY_MANAPHY
    JOHTO_DEX_PHIONE,
    JOHTO_DEX_MANAPHY,
#endif
#if P_FAMILY_DARKRAI
    JOHTO_DEX_DARKRAI,
#endif
#if P_FAMILY_SHAYMIN
    JOHTO_DEX_SHAYMIN,
#endif
#if P_FAMILY_ARCEUS
    JOHTO_DEX_ARCEUS,
#endif
#if P_FAMILY_VICTINI
    JOHTO_DEX_VICTINI,
#endif
#if P_FAMILY_SNIVY
    JOHTO_DEX_SNIVY,
    JOHTO_DEX_SERVINE,
    JOHTO_DEX_SERPERIOR,
#endif
#if P_FAMILY_TEPIG
    JOHTO_DEX_TEPIG,
    JOHTO_DEX_PIGNITE,
    JOHTO_DEX_EMBOAR,
#endif
#if P_FAMILY_OSHAWOTT
    JOHTO_DEX_OSHAWOTT,
    JOHTO_DEX_DEWOTT,
    JOHTO_DEX_SAMUROTT,
#endif
#if P_FAMILY_PATRAT
    JOHTO_DEX_PATRAT,
    JOHTO_DEX_WATCHOG,
#endif
#if P_FAMILY_LILLIPUP
    JOHTO_DEX_LILLIPUP,
    JOHTO_DEX_HERDIER,
    JOHTO_DEX_STOUTLAND,
#endif
#if P_FAMILY_PURRLOIN
    JOHTO_DEX_PURRLOIN,
    JOHTO_DEX_LIEPARD,
#endif
#if P_FAMILY_PANSAGE
    JOHTO_DEX_PANSAGE,
    JOHTO_DEX_SIMISAGE,
#endif
#if P_FAMILY_PANSEAR
    JOHTO_DEX_PANSEAR,
    JOHTO_DEX_SIMISEAR,
#endif
#if P_FAMILY_PANPOUR
    JOHTO_DEX_PANPOUR,
    JOHTO_DEX_SIMIPOUR,
#endif
#if P_FAMILY_MUNNA
    JOHTO_DEX_MUNNA,
    JOHTO_DEX_MUSHARNA,
#endif
#if P_FAMILY_PIDOVE
    JOHTO_DEX_PIDOVE,
    JOHTO_DEX_TRANQUILL,
    JOHTO_DEX_UNFEZANT,
#endif
#if P_FAMILY_BLITZLE
    JOHTO_DEX_BLITZLE,
    JOHTO_DEX_ZEBSTRIKA,
#endif
#if P_FAMILY_ROGGENROLA
    JOHTO_DEX_ROGGENROLA,
    JOHTO_DEX_BOLDORE,
    JOHTO_DEX_GIGALITH,
#endif
#if P_FAMILY_WOOBAT
    JOHTO_DEX_WOOBAT,
    JOHTO_DEX_SWOOBAT,
#endif
#if P_FAMILY_DRILBUR
    JOHTO_DEX_DRILBUR,
    JOHTO_DEX_EXCADRILL,
#endif
#if P_FAMILY_AUDINO
    JOHTO_DEX_AUDINO,
#endif
#if P_FAMILY_TIMBURR
    JOHTO_DEX_TIMBURR,
    JOHTO_DEX_GURDURR,
    JOHTO_DEX_CONKELDURR,
#endif
#if P_FAMILY_TYMPOLE
    JOHTO_DEX_TYMPOLE,
    JOHTO_DEX_PALPITOAD,
    JOHTO_DEX_SEISMITOAD,
#endif
#if P_FAMILY_THROH
    JOHTO_DEX_THROH,
#endif
#if P_FAMILY_SAWK
    JOHTO_DEX_SAWK,
#endif
#if P_FAMILY_SEWADDLE
    JOHTO_DEX_SEWADDLE,
    JOHTO_DEX_SWADLOON,
    JOHTO_DEX_LEAVANNY,
#endif
#if P_FAMILY_VENIPEDE
    JOHTO_DEX_VENIPEDE,
    JOHTO_DEX_WHIRLIPEDE,
    JOHTO_DEX_SCOLIPEDE,
#endif
#if P_FAMILY_COTTONEE
    JOHTO_DEX_COTTONEE,
    JOHTO_DEX_WHIMSICOTT,
#endif
#if P_FAMILY_PETILIL
    JOHTO_DEX_PETILIL,
    JOHTO_DEX_LILLIGANT,
#endif
#if P_FAMILY_BASCULIN
    JOHTO_DEX_BASCULIN,
#endif
#if P_FAMILY_SANDILE
    JOHTO_DEX_SANDILE,
    JOHTO_DEX_KROKOROK,
    JOHTO_DEX_KROOKODILE,
#endif
#if P_FAMILY_DARUMAKA
    JOHTO_DEX_DARUMAKA,
    JOHTO_DEX_DARMANITAN,
#endif
#if P_FAMILY_MARACTUS
    JOHTO_DEX_MARACTUS,
#endif
#if P_FAMILY_DWEBBLE
    JOHTO_DEX_DWEBBLE,
    JOHTO_DEX_CRUSTLE,
#endif
#if P_FAMILY_SCRAGGY
    JOHTO_DEX_SCRAGGY,
    JOHTO_DEX_SCRAFTY,
#endif
#if P_FAMILY_SIGILYPH
    JOHTO_DEX_SIGILYPH,
#endif
#if P_FAMILY_YAMASK
    JOHTO_DEX_YAMASK,
    JOHTO_DEX_COFAGRIGUS,
#endif
#if P_FAMILY_TIRTOUGA
    JOHTO_DEX_TIRTOUGA,
    JOHTO_DEX_CARRACOSTA,
#endif
#if P_FAMILY_ARCHEN
    JOHTO_DEX_ARCHEN,
    JOHTO_DEX_ARCHEOPS,
#endif
#if P_FAMILY_TRUBBISH
    JOHTO_DEX_TRUBBISH,
    JOHTO_DEX_GARBODOR,
#endif
#if P_FAMILY_ZORUA
    JOHTO_DEX_ZORUA,
    JOHTO_DEX_ZOROARK,
#endif
#if P_FAMILY_MINCCINO
    JOHTO_DEX_MINCCINO,
    JOHTO_DEX_CINCCINO,
#endif
#if P_FAMILY_GOTHITA
    JOHTO_DEX_GOTHITA,
    JOHTO_DEX_GOTHORITA,
    JOHTO_DEX_GOTHITELLE,
#endif
#if P_FAMILY_SOLOSIS
    JOHTO_DEX_SOLOSIS,
    JOHTO_DEX_DUOSION,
    JOHTO_DEX_REUNICLUS,
#endif
#if P_FAMILY_DUCKLETT
    JOHTO_DEX_DUCKLETT,
    JOHTO_DEX_SWANNA,
#endif
#if P_FAMILY_VANILLITE
    JOHTO_DEX_VANILLITE,
    JOHTO_DEX_VANILLISH,
    JOHTO_DEX_VANILLUXE,
#endif
#if P_FAMILY_DEERLING
    JOHTO_DEX_DEERLING,
    JOHTO_DEX_SAWSBUCK,
#endif
#if P_FAMILY_EMOLGA
    JOHTO_DEX_EMOLGA,
#endif
#if P_FAMILY_KARRABLAST
    JOHTO_DEX_KARRABLAST,
    JOHTO_DEX_ESCAVALIER,
#endif
#if P_FAMILY_FOONGUS
    JOHTO_DEX_FOONGUS,
    JOHTO_DEX_AMOONGUSS,
#endif
#if P_FAMILY_FRILLISH
    JOHTO_DEX_FRILLISH,
    JOHTO_DEX_JELLICENT,
#endif
#if P_FAMILY_ALOMOMOLA
    JOHTO_DEX_ALOMOMOLA,
#endif
#if P_FAMILY_JOLTIK
    JOHTO_DEX_JOLTIK,
    JOHTO_DEX_GALVANTULA,
#endif
#if P_FAMILY_FERROSEED
    JOHTO_DEX_FERROSEED,
    JOHTO_DEX_FERROTHORN,
#endif
#if P_FAMILY_KLINK
    JOHTO_DEX_KLINK,
    JOHTO_DEX_KLANG,
    JOHTO_DEX_KLINKLANG,
#endif
#if P_FAMILY_TYNAMO
    JOHTO_DEX_TYNAMO,
    JOHTO_DEX_EELEKTRIK,
    JOHTO_DEX_EELEKTROSS,
#endif
#if P_FAMILY_ELGYEM
    JOHTO_DEX_ELGYEM,
    JOHTO_DEX_BEHEEYEM,
#endif
#if P_FAMILY_LITWICK
    JOHTO_DEX_LITWICK,
    JOHTO_DEX_LAMPENT,
    JOHTO_DEX_CHANDELURE,
#endif
#if P_FAMILY_AXEW
    JOHTO_DEX_AXEW,
    JOHTO_DEX_FRAXURE,
    JOHTO_DEX_HAXORUS,
#endif
#if P_FAMILY_CUBCHOO
    JOHTO_DEX_CUBCHOO,
    JOHTO_DEX_BEARTIC,
#endif
#if P_FAMILY_CRYOGONAL
    JOHTO_DEX_CRYOGONAL,
#endif
#if P_FAMILY_SHELMET
    JOHTO_DEX_SHELMET,
    JOHTO_DEX_ACCELGOR,
#endif
#if P_FAMILY_STUNFISK
    JOHTO_DEX_STUNFISK,
#endif
#if P_FAMILY_MIENFOO
    JOHTO_DEX_MIENFOO,
    JOHTO_DEX_MIENSHAO,
#endif
#if P_FAMILY_DRUDDIGON
    JOHTO_DEX_DRUDDIGON,
#endif
#if P_FAMILY_GOLETT
    JOHTO_DEX_GOLETT,
    JOHTO_DEX_GOLURK,
#endif
#if P_FAMILY_PAWNIARD
    JOHTO_DEX_PAWNIARD,
    JOHTO_DEX_BISHARP,
#endif
#if P_FAMILY_BOUFFALANT
    JOHTO_DEX_BOUFFALANT,
#endif
#if P_FAMILY_RUFFLET
    JOHTO_DEX_RUFFLET,
    JOHTO_DEX_BRAVIARY,
#endif
#if P_FAMILY_VULLABY
    JOHTO_DEX_VULLABY,
    JOHTO_DEX_MANDIBUZZ,
#endif
#if P_FAMILY_HEATMOR
    JOHTO_DEX_HEATMOR,
#endif
#if P_FAMILY_DURANT
    JOHTO_DEX_DURANT,
#endif
#if P_FAMILY_DEINO
    JOHTO_DEX_DEINO,
    JOHTO_DEX_ZWEILOUS,
    JOHTO_DEX_HYDREIGON,
#endif
#if P_FAMILY_LARVESTA
    JOHTO_DEX_LARVESTA,
    JOHTO_DEX_VOLCARONA,
#endif
#if P_FAMILY_COBALION
    JOHTO_DEX_COBALION,
#endif
#if P_FAMILY_TERRAKION
    JOHTO_DEX_TERRAKION,
#endif
#if P_FAMILY_VIRIZION
    JOHTO_DEX_VIRIZION,
#endif
#if P_FAMILY_TORNADUS
    JOHTO_DEX_TORNADUS,
#endif
#if P_FAMILY_THUNDURUS
    JOHTO_DEX_THUNDURUS,
#endif
#if P_FAMILY_RESHIRAM
    JOHTO_DEX_RESHIRAM,
#endif
#if P_FAMILY_ZEKROM
    JOHTO_DEX_ZEKROM,
#endif
#if P_FAMILY_LANDORUS
    JOHTO_DEX_LANDORUS,
#endif
#if P_FAMILY_KYUREM
    JOHTO_DEX_KYUREM,
#endif
#if P_FAMILY_KELDEO
    JOHTO_DEX_KELDEO,
#endif
#if P_FAMILY_MELOETTA
    JOHTO_DEX_MELOETTA,
#endif
#if P_FAMILY_GENESECT
    JOHTO_DEX_GENESECT,
#endif
#if P_FAMILY_CHESPIN
    JOHTO_DEX_CHESPIN,
    JOHTO_DEX_QUILLADIN,
    JOHTO_DEX_CHESNAUGHT,
#endif
#if P_FAMILY_FENNEKIN
    JOHTO_DEX_FENNEKIN,
    JOHTO_DEX_BRAIXEN,
    JOHTO_DEX_DELPHOX,
#endif
#if P_FAMILY_FROAKIE
    JOHTO_DEX_FROAKIE,
    JOHTO_DEX_FROGADIER,
    JOHTO_DEX_GRENINJA,
#endif
#if P_FAMILY_BUNNELBY
    JOHTO_DEX_BUNNELBY,
    JOHTO_DEX_DIGGERSBY,
#endif
#if P_FAMILY_FLETCHLING
    JOHTO_DEX_FLETCHLING,
    JOHTO_DEX_FLETCHINDER,
    JOHTO_DEX_TALONFLAME,
#endif
#if P_FAMILY_SCATTERBUG
    JOHTO_DEX_SCATTERBUG,
    JOHTO_DEX_SPEWPA,
    JOHTO_DEX_VIVILLON,
#endif
#if P_FAMILY_LITLEO
    JOHTO_DEX_LITLEO,
    JOHTO_DEX_PYROAR,
#endif
#if P_FAMILY_FLABEBE
    JOHTO_DEX_FLABEBE,
    JOHTO_DEX_FLOETTE,
    JOHTO_DEX_FLORGES,
#endif
#if P_FAMILY_SKIDDO
    JOHTO_DEX_SKIDDO,
    JOHTO_DEX_GOGOAT,
#endif
#if P_FAMILY_PANCHAM
    JOHTO_DEX_PANCHAM,
    JOHTO_DEX_PANGORO,
#endif
#if P_FAMILY_FURFROU
    JOHTO_DEX_FURFROU,
#endif
#if P_FAMILY_ESPURR
    JOHTO_DEX_ESPURR,
    JOHTO_DEX_MEOWSTIC,
#endif
#if P_FAMILY_HONEDGE
    JOHTO_DEX_HONEDGE,
    JOHTO_DEX_DOUBLADE,
    JOHTO_DEX_AEGISLASH,
#endif
#if P_FAMILY_SPRITZEE
    JOHTO_DEX_SPRITZEE,
    JOHTO_DEX_AROMATISSE,
#endif
#if P_FAMILY_SWIRLIX
    JOHTO_DEX_SWIRLIX,
    JOHTO_DEX_SLURPUFF,
#endif
#if P_FAMILY_INKAY
    JOHTO_DEX_INKAY,
    JOHTO_DEX_MALAMAR,
#endif
#if P_FAMILY_BINACLE
    JOHTO_DEX_BINACLE,
    JOHTO_DEX_BARBARACLE,
#endif
#if P_FAMILY_SKRELP
    JOHTO_DEX_SKRELP,
    JOHTO_DEX_DRAGALGE,
#endif
#if P_FAMILY_CLAUNCHER
    JOHTO_DEX_CLAUNCHER,
    JOHTO_DEX_CLAWITZER,
#endif
#if P_FAMILY_HELIOPTILE
    JOHTO_DEX_HELIOPTILE,
    JOHTO_DEX_HELIOLISK,
#endif
#if P_FAMILY_TYRUNT
    JOHTO_DEX_TYRUNT,
    JOHTO_DEX_TYRANTRUM,
#endif
#if P_FAMILY_AMAURA
    JOHTO_DEX_AMAURA,
    JOHTO_DEX_AURORUS,
#endif
#if P_FAMILY_EEVEE && P_GEN_6_CROSS_EVOS
    JOHTO_DEX_SYLVEON,
#endif
#if P_FAMILY_HAWLUCHA
    JOHTO_DEX_HAWLUCHA,
#endif
#if P_FAMILY_DEDENNE
    JOHTO_DEX_DEDENNE,
#endif
#if P_FAMILY_CARBINK
    JOHTO_DEX_CARBINK,
#endif
#if P_FAMILY_GOOMY
    JOHTO_DEX_GOOMY,
    JOHTO_DEX_SLIGGOO,
    JOHTO_DEX_GOODRA,
#endif
#if P_FAMILY_KLEFKI
    JOHTO_DEX_KLEFKI,
#endif
#if P_FAMILY_PHANTUMP
    JOHTO_DEX_PHANTUMP,
    JOHTO_DEX_TREVENANT,
#endif
#if P_FAMILY_PUMPKABOO
    JOHTO_DEX_PUMPKABOO,
    JOHTO_DEX_GOURGEIST,
#endif
#if P_FAMILY_BERGMITE
    JOHTO_DEX_BERGMITE,
    JOHTO_DEX_AVALUGG,
#endif
#if P_FAMILY_NOIBAT
    JOHTO_DEX_NOIBAT,
    JOHTO_DEX_NOIVERN,
#endif
#if P_FAMILY_XERNEAS
    JOHTO_DEX_XERNEAS,
#endif
#if P_FAMILY_YVELTAL
    JOHTO_DEX_YVELTAL,
#endif
#if P_FAMILY_ZYGARDE
    JOHTO_DEX_ZYGARDE,
#endif
#if P_FAMILY_DIANCIE
    JOHTO_DEX_DIANCIE,
#endif
#if P_FAMILY_HOOPA
    JOHTO_DEX_HOOPA,
#endif
#if P_FAMILY_VOLCANION
    JOHTO_DEX_VOLCANION,
#endif
#if P_FAMILY_ROWLET
    JOHTO_DEX_ROWLET,
    JOHTO_DEX_DARTRIX,
    JOHTO_DEX_DECIDUEYE,
#endif
#if P_FAMILY_LITTEN
    JOHTO_DEX_LITTEN,
    JOHTO_DEX_TORRACAT,
    JOHTO_DEX_INCINEROAR,
#endif
#if P_FAMILY_POPPLIO
    JOHTO_DEX_POPPLIO,
    JOHTO_DEX_BRIONNE,
    JOHTO_DEX_PRIMARINA,
#endif
#if P_FAMILY_PIKIPEK
    JOHTO_DEX_PIKIPEK,
    JOHTO_DEX_TRUMBEAK,
    JOHTO_DEX_TOUCANNON,
#endif
#if P_FAMILY_YUNGOOS
    JOHTO_DEX_YUNGOOS,
    JOHTO_DEX_GUMSHOOS,
#endif
#if P_FAMILY_GRUBBIN
    JOHTO_DEX_GRUBBIN,
    JOHTO_DEX_CHARJABUG,
    JOHTO_DEX_VIKAVOLT,
#endif
#if P_FAMILY_CRABRAWLER
    JOHTO_DEX_CRABRAWLER,
    JOHTO_DEX_CRABOMINABLE,
#endif
#if P_FAMILY_ORICORIO
    JOHTO_DEX_ORICORIO,
#endif
#if P_FAMILY_CUTIEFLY
    JOHTO_DEX_CUTIEFLY,
    JOHTO_DEX_RIBOMBEE,
#endif
#if P_FAMILY_ROCKRUFF
    JOHTO_DEX_ROCKRUFF,
    JOHTO_DEX_LYCANROC,
#endif
#if P_FAMILY_WISHIWASHI
    JOHTO_DEX_WISHIWASHI,
#endif
#if P_FAMILY_MAREANIE
    JOHTO_DEX_MAREANIE,
    JOHTO_DEX_TOXAPEX,
#endif
#if P_FAMILY_MUDBRAY
    JOHTO_DEX_MUDBRAY,
    JOHTO_DEX_MUDSDALE,
#endif
#if P_FAMILY_DEWPIDER
    JOHTO_DEX_DEWPIDER,
    JOHTO_DEX_ARAQUANID,
#endif
#if P_FAMILY_FOMANTIS
    JOHTO_DEX_FOMANTIS,
    JOHTO_DEX_LURANTIS,
#endif
#if P_FAMILY_MORELULL
    JOHTO_DEX_MORELULL,
    JOHTO_DEX_SHIINOTIC,
#endif
#if P_FAMILY_SALANDIT
    JOHTO_DEX_SALANDIT,
    JOHTO_DEX_SALAZZLE,
#endif
#if P_FAMILY_STUFFUL
    JOHTO_DEX_STUFFUL,
    JOHTO_DEX_BEWEAR,
#endif
#if P_FAMILY_BOUNSWEET
    JOHTO_DEX_BOUNSWEET,
    JOHTO_DEX_STEENEE,
    JOHTO_DEX_TSAREENA,
#endif
#if P_FAMILY_COMFEY
    JOHTO_DEX_COMFEY,
#endif
#if P_FAMILY_ORANGURU
    JOHTO_DEX_ORANGURU,
#endif
#if P_FAMILY_PASSIMIAN
    JOHTO_DEX_PASSIMIAN,
#endif
#if P_FAMILY_WIMPOD
    JOHTO_DEX_WIMPOD,
    JOHTO_DEX_GOLISOPOD,
#endif
#if P_FAMILY_SANDYGAST
    JOHTO_DEX_SANDYGAST,
    JOHTO_DEX_PALOSSAND,
#endif
#if P_FAMILY_PYUKUMUKU
    JOHTO_DEX_PYUKUMUKU,
#endif
#if P_FAMILY_TYPE_NULL
    JOHTO_DEX_TYPE_NULL,
    JOHTO_DEX_SILVALLY,
#endif
#if P_FAMILY_MINIOR
    JOHTO_DEX_MINIOR,
#endif
#if P_FAMILY_KOMALA
    JOHTO_DEX_KOMALA,
#endif
#if P_FAMILY_TURTONATOR
    JOHTO_DEX_TURTONATOR,
#endif
#if P_FAMILY_TOGEDEMARU
    JOHTO_DEX_TOGEDEMARU,
#endif
#if P_FAMILY_MIMIKYU
    JOHTO_DEX_MIMIKYU,
#endif
#if P_FAMILY_BRUXISH
    JOHTO_DEX_BRUXISH,
#endif
#if P_FAMILY_DRAMPA
    JOHTO_DEX_DRAMPA,
#endif
#if P_FAMILY_DHELMISE
    JOHTO_DEX_DHELMISE,
#endif
#if P_FAMILY_JANGMO_O
    JOHTO_DEX_JANGMO_O,
    JOHTO_DEX_HAKAMO_O,
    JOHTO_DEX_KOMMO_O,
#endif
#if P_FAMILY_TAPU_KOKO
    JOHTO_DEX_TAPU_KOKO,
#endif
#if P_FAMILY_TAPU_LELE
    JOHTO_DEX_TAPU_LELE,
#endif
#if P_FAMILY_TAPU_BULU
    JOHTO_DEX_TAPU_BULU,
#endif
#if P_FAMILY_TAPU_FINI
    JOHTO_DEX_TAPU_FINI,
#endif
#if P_FAMILY_COSMOG
    JOHTO_DEX_COSMOG,
    JOHTO_DEX_COSMOEM,
    JOHTO_DEX_SOLGALEO,
    JOHTO_DEX_LUNALA,
#endif
#if P_FAMILY_NIHILEGO
    JOHTO_DEX_NIHILEGO,
#endif
#if P_FAMILY_BUZZWOLE
    JOHTO_DEX_BUZZWOLE,
#endif
#if P_FAMILY_PHEROMOSA
    JOHTO_DEX_PHEROMOSA,
#endif
#if P_FAMILY_XURKITREE
    JOHTO_DEX_XURKITREE,
#endif
#if P_FAMILY_CELESTEELA
    JOHTO_DEX_CELESTEELA,
#endif
#if P_FAMILY_KARTANA
    JOHTO_DEX_KARTANA,
#endif
#if P_FAMILY_GUZZLORD
    JOHTO_DEX_GUZZLORD,
#endif
#if P_FAMILY_NECROZMA
    JOHTO_DEX_NECROZMA,
#endif
#if P_FAMILY_MAGEARNA
    JOHTO_DEX_MAGEARNA,
#endif
#if P_FAMILY_MARSHADOW
    JOHTO_DEX_MARSHADOW,
#endif
#if P_FAMILY_POIPOLE
    JOHTO_DEX_POIPOLE,
    JOHTO_DEX_NAGANADEL,
#endif
#if P_FAMILY_STAKATAKA
    JOHTO_DEX_STAKATAKA,
#endif
#if P_FAMILY_BLACEPHALON
    JOHTO_DEX_BLACEPHALON,
#endif
#if P_FAMILY_ZERAORA
    JOHTO_DEX_ZERAORA,
#endif
#if P_FAMILY_MELTAN
    JOHTO_DEX_MELTAN,
    JOHTO_DEX_MELMETAL,
#endif
#if P_FAMILY_GROOKEY
    JOHTO_DEX_GROOKEY,
    JOHTO_DEX_THWACKEY,
    JOHTO_DEX_RILLABOOM,
#endif
#if P_FAMILY_SCORBUNNY
    JOHTO_DEX_SCORBUNNY,
    JOHTO_DEX_RABOOT,
    JOHTO_DEX_CINDERACE,
#endif
#if P_FAMILY_SOBBLE
    JOHTO_DEX_SOBBLE,
    JOHTO_DEX_DRIZZILE,
    JOHTO_DEX_INTELEON,
#endif
#if P_FAMILY_SKWOVET
    JOHTO_DEX_SKWOVET,
    JOHTO_DEX_GREEDENT,
#endif
#if P_FAMILY_ROOKIDEE
    JOHTO_DEX_ROOKIDEE,
    JOHTO_DEX_CORVISQUIRE,
    JOHTO_DEX_CORVIKNIGHT,
#endif
#if P_FAMILY_BLIPBUG
    JOHTO_DEX_BLIPBUG,
    JOHTO_DEX_DOTTLER,
    JOHTO_DEX_ORBEETLE,
#endif
#if P_FAMILY_NICKIT
    JOHTO_DEX_NICKIT,
    JOHTO_DEX_THIEVUL,
#endif
#if P_FAMILY_GOSSIFLEUR
    JOHTO_DEX_GOSSIFLEUR,
    JOHTO_DEX_ELDEGOSS,
#endif
#if P_FAMILY_WOOLOO
    JOHTO_DEX_WOOLOO,
    JOHTO_DEX_DUBWOOL,
#endif
#if P_FAMILY_CHEWTLE
    JOHTO_DEX_CHEWTLE,
    JOHTO_DEX_DREDNAW,
#endif
#if P_FAMILY_YAMPER
    JOHTO_DEX_YAMPER,
    JOHTO_DEX_BOLTUND,
#endif
#if P_FAMILY_ROLYCOLY
    JOHTO_DEX_ROLYCOLY,
    JOHTO_DEX_CARKOL,
    JOHTO_DEX_COALOSSAL,
#endif
#if P_FAMILY_APPLIN
    JOHTO_DEX_APPLIN,
    JOHTO_DEX_FLAPPLE,
    JOHTO_DEX_APPLETUN,
#endif
#if P_FAMILY_SILICOBRA
    JOHTO_DEX_SILICOBRA,
    JOHTO_DEX_SANDACONDA,
#endif
#if P_FAMILY_CRAMORANT
    JOHTO_DEX_CRAMORANT,
#endif
#if P_FAMILY_ARROKUDA
    JOHTO_DEX_ARROKUDA,
    JOHTO_DEX_BARRASKEWDA,
#endif
#if P_FAMILY_TOXEL
    JOHTO_DEX_TOXEL,
    JOHTO_DEX_TOXTRICITY,
#endif
#if P_FAMILY_SIZZLIPEDE
    JOHTO_DEX_SIZZLIPEDE,
    JOHTO_DEX_CENTISKORCH,
#endif
#if P_FAMILY_CLOBBOPUS
    JOHTO_DEX_CLOBBOPUS,
    JOHTO_DEX_GRAPPLOCT,
#endif
#if P_FAMILY_SINISTEA
    JOHTO_DEX_SINISTEA,
    JOHTO_DEX_POLTEAGEIST,
#endif
#if P_FAMILY_HATENNA
    JOHTO_DEX_HATENNA,
    JOHTO_DEX_HATTREM,
    JOHTO_DEX_HATTERENE,
#endif
#if P_FAMILY_IMPIDIMP
    JOHTO_DEX_IMPIDIMP,
    JOHTO_DEX_MORGREM,
    JOHTO_DEX_GRIMMSNARL,
#endif
#if P_FAMILY_ZIGZAGOON && P_GALARIAN_FORMS
    JOHTO_DEX_OBSTAGOON,
#endif
#if P_FAMILY_MEOWTH && P_GALARIAN_FORMS
    JOHTO_DEX_PERRSERKER,
#endif
#if P_FAMILY_CORSOLA && P_GALARIAN_FORMS
    JOHTO_DEX_CURSOLA,
#endif
#if P_FAMILY_FARFETCHD && P_GALARIAN_FORMS
    JOHTO_DEX_SIRFETCHD,
#endif
#if P_FAMILY_MR_MIME && P_GALARIAN_FORMS
    JOHTO_DEX_MR_RIME,
#endif
#if P_FAMILY_YAMASK && P_GALARIAN_FORMS
    JOHTO_DEX_RUNERIGUS,
#endif
#if P_FAMILY_MILCERY
    JOHTO_DEX_MILCERY,
    JOHTO_DEX_ALCREMIE,
#endif
#if P_FAMILY_FALINKS
    JOHTO_DEX_FALINKS,
#endif
#if P_FAMILY_PINCURCHIN
    JOHTO_DEX_PINCURCHIN,
#endif
#if P_FAMILY_SNOM
    JOHTO_DEX_SNOM,
    JOHTO_DEX_FROSMOTH,
#endif
#if P_FAMILY_STONJOURNER
    JOHTO_DEX_STONJOURNER,
#endif
#if P_FAMILY_EISCUE
    JOHTO_DEX_EISCUE,
#endif
#if P_FAMILY_INDEEDEE
    JOHTO_DEX_INDEEDEE,
#endif
#if P_FAMILY_MORPEKO
    JOHTO_DEX_MORPEKO,
#endif
#if P_FAMILY_CUFANT
    JOHTO_DEX_CUFANT,
    JOHTO_DEX_COPPERAJAH,
#endif
#if P_FAMILY_DRACOZOLT
    JOHTO_DEX_DRACOZOLT,
#endif
#if P_FAMILY_ARCTOZOLT
    JOHTO_DEX_ARCTOZOLT,
#endif
#if P_FAMILY_DRACOVISH
    JOHTO_DEX_DRACOVISH,
#endif
#if P_FAMILY_ARCTOVISH
    JOHTO_DEX_ARCTOVISH,
#endif
#if P_FAMILY_DURALUDON
    JOHTO_DEX_DURALUDON,
#endif
#if P_FAMILY_DREEPY
    JOHTO_DEX_DREEPY,
    JOHTO_DEX_DRAKLOAK,
    JOHTO_DEX_DRAGAPULT,
#endif
#if P_FAMILY_ZACIAN
    JOHTO_DEX_ZACIAN,
#endif
#if P_FAMILY_ZAMAZENTA
    JOHTO_DEX_ZAMAZENTA,
#endif
#if P_FAMILY_ETERNATUS
    JOHTO_DEX_ETERNATUS,
#endif
#if P_FAMILY_KUBFU
    JOHTO_DEX_KUBFU,
    JOHTO_DEX_URSHIFU,
#endif
#if P_FAMILY_ZARUDE
    JOHTO_DEX_ZARUDE,
#endif
#if P_FAMILY_REGIELEKI
    JOHTO_DEX_REGIELEKI,
#endif
#if P_FAMILY_REGIDRAGO
    JOHTO_DEX_REGIDRAGO,
#endif
#if P_FAMILY_GLASTRIER
    JOHTO_DEX_GLASTRIER,
#endif
#if P_FAMILY_SPECTRIER
    JOHTO_DEX_SPECTRIER,
#endif
#if P_FAMILY_CALYREX
    JOHTO_DEX_CALYREX,
#endif
#if P_FAMILY_STANTLER && P_GEN_8_CROSS_EVOS
    JOHTO_DEX_WYRDEER,
#endif
#if P_FAMILY_SCYTHER && P_GEN_8_CROSS_EVOS
    JOHTO_DEX_KLEAVOR,
#endif
#if P_FAMILY_TEDDIURSA && P_GEN_8_CROSS_EVOS
    JOHTO_DEX_URSALUNA,
#endif
#if P_FAMILY_BASCULIN && P_HISUIAN_FORMS
    JOHTO_DEX_BASCULEGION,
#endif
#if P_FAMILY_SNEASEL && P_HISUIAN_FORMS
    JOHTO_DEX_SNEASLER,
#endif
#if P_FAMILY_QWILFISH && P_HISUIAN_FORMS
    JOHTO_DEX_OVERQWIL,
#endif
#if P_FAMILY_ENAMORUS
    JOHTO_DEX_ENAMORUS,
#endif
#if P_FAMILY_SPRIGATITO
    JOHTO_DEX_SPRIGATITO,
    JOHTO_DEX_FLORAGATO,
    JOHTO_DEX_MEOWSCARADA,
#endif
#if P_FAMILY_FUECOCO
    JOHTO_DEX_FUECOCO,
    JOHTO_DEX_CROCALOR,
    JOHTO_DEX_SKELEDIRGE,
#endif
#if P_FAMILY_QUAXLY
    JOHTO_DEX_QUAXLY,
    JOHTO_DEX_QUAXWELL,
    JOHTO_DEX_QUAQUAVAL,
#endif
#if P_FAMILY_LECHONK
    JOHTO_DEX_LECHONK,
    JOHTO_DEX_OINKOLOGNE,
#endif
#if P_FAMILY_TAROUNTULA
    JOHTO_DEX_TAROUNTULA,
    JOHTO_DEX_SPIDOPS,
#endif
#if P_FAMILY_NYMBLE
    JOHTO_DEX_NYMBLE,
    JOHTO_DEX_LOKIX,
#endif
#if P_FAMILY_PAWMI
    JOHTO_DEX_PAWMI,
    JOHTO_DEX_PAWMO,
    JOHTO_DEX_PAWMOT,
#endif
#if P_FAMILY_TANDEMAUS
    JOHTO_DEX_TANDEMAUS,
    JOHTO_DEX_MAUSHOLD,
#endif
#if P_FAMILY_FIDOUGH
    JOHTO_DEX_FIDOUGH,
    JOHTO_DEX_DACHSBUN,
#endif
#if P_FAMILY_SMOLIV
    JOHTO_DEX_SMOLIV,
    JOHTO_DEX_DOLLIV,
    JOHTO_DEX_ARBOLIVA,
#endif
#if P_FAMILY_SQUAWKABILLY
    JOHTO_DEX_SQUAWKABILLY,
#endif
#if P_FAMILY_NACLI
    JOHTO_DEX_NACLI,
    JOHTO_DEX_NACLSTACK,
    JOHTO_DEX_GARGANACL,
#endif
#if P_FAMILY_CHARCADET
    JOHTO_DEX_CHARCADET,
    JOHTO_DEX_ARMAROUGE,
    JOHTO_DEX_CERULEDGE,
#endif
#if P_FAMILY_TADBULB
    JOHTO_DEX_TADBULB,
    JOHTO_DEX_BELLIBOLT,
#endif
#if P_FAMILY_WATTREL
    JOHTO_DEX_WATTREL,
    JOHTO_DEX_KILOWATTREL,
#endif
#if P_FAMILY_MASCHIFF
    JOHTO_DEX_MASCHIFF,
    JOHTO_DEX_MABOSSTIFF,
#endif
#if P_FAMILY_SHROODLE
    JOHTO_DEX_SHROODLE,
    JOHTO_DEX_GRAFAIAI,
#endif
#if P_FAMILY_BRAMBLIN
    JOHTO_DEX_BRAMBLIN,
    JOHTO_DEX_BRAMBLEGHAST,
#endif
#if P_FAMILY_TOEDSCOOL
    JOHTO_DEX_TOEDSCOOL,
    JOHTO_DEX_TOEDSCRUEL,
#endif
#if P_FAMILY_KLAWF
    JOHTO_DEX_KLAWF,
#endif
#if P_FAMILY_CAPSAKID
    JOHTO_DEX_CAPSAKID,
    JOHTO_DEX_SCOVILLAIN,
#endif
#if P_FAMILY_RELLOR
    JOHTO_DEX_RELLOR,
    JOHTO_DEX_RABSCA,
#endif
#if P_FAMILY_FLITTLE
    JOHTO_DEX_FLITTLE,
    JOHTO_DEX_ESPATHRA,
#endif
#if P_FAMILY_TINKATINK
    JOHTO_DEX_TINKATINK,
    JOHTO_DEX_TINKATUFF,
    JOHTO_DEX_TINKATON,
#endif
#if P_FAMILY_WIGLETT
    JOHTO_DEX_WIGLETT,
    JOHTO_DEX_WUGTRIO,
#endif
#if P_FAMILY_BOMBIRDIER
    JOHTO_DEX_BOMBIRDIER,
#endif
#if P_FAMILY_FINIZEN
    JOHTO_DEX_FINIZEN,
    JOHTO_DEX_PALAFIN,
#endif
#if P_FAMILY_VAROOM
    JOHTO_DEX_VAROOM,
    JOHTO_DEX_REVAVROOM,
#endif
#if P_FAMILY_CYCLIZAR
    JOHTO_DEX_CYCLIZAR,
#endif
#if P_FAMILY_ORTHWORM
    JOHTO_DEX_ORTHWORM,
#endif
#if P_FAMILY_GLIMMET
    JOHTO_DEX_GLIMMET,
    JOHTO_DEX_GLIMMORA,
#endif
#if P_FAMILY_GREAVARD
    JOHTO_DEX_GREAVARD,
    JOHTO_DEX_HOUNDSTONE,
#endif
#if P_FAMILY_FLAMIGO
    JOHTO_DEX_FLAMIGO,
#endif
#if P_FAMILY_CETODDLE
    JOHTO_DEX_CETODDLE,
    JOHTO_DEX_CETITAN,
#endif
#if P_FAMILY_VELUZA
    JOHTO_DEX_VELUZA,
#endif
#if P_FAMILY_DONDOZO
    JOHTO_DEX_DONDOZO,
#endif
#if P_FAMILY_TATSUGIRI
    JOHTO_DEX_TATSUGIRI,
#endif
#if P_FAMILY_MANKEY && P_GEN_9_CROSS_EVOS
    JOHTO_DEX_ANNIHILAPE,
#endif
#if P_FAMILY_WOOPER && P_PALDEAN_FORMS
    JOHTO_DEX_CLODSIRE,
#endif
#if P_FAMILY_GIRAFARIG && P_GEN_9_CROSS_EVOS
    JOHTO_DEX_FARIGIRAF,
#endif
#if P_FAMILY_DUNSPARCE && P_GEN_9_CROSS_EVOS
    JOHTO_DEX_DUDUNSPARCE,
#endif
#if P_FAMILY_PAWNIARD && P_GEN_9_CROSS_EVOS
    JOHTO_DEX_KINGAMBIT,
#endif
#if P_FAMILY_GREAT_TUSK
    JOHTO_DEX_GREAT_TUSK,
#endif
#if P_FAMILY_SCREAM_TAIL
    JOHTO_DEX_SCREAM_TAIL,
#endif
#if P_FAMILY_BRUTE_BONNET
    JOHTO_DEX_BRUTE_BONNET,
#endif
#if P_FAMILY_FLUTTER_MANE
    JOHTO_DEX_FLUTTER_MANE,
#endif
#if P_FAMILY_SLITHER_WING
    JOHTO_DEX_SLITHER_WING,
#endif
#if P_FAMILY_SANDY_SHOCKS
    JOHTO_DEX_SANDY_SHOCKS,
#endif
#if P_FAMILY_IRON_TREADS
    JOHTO_DEX_IRON_TREADS,
#endif
#if P_FAMILY_IRON_BUNDLE
    JOHTO_DEX_IRON_BUNDLE,
#endif
#if P_FAMILY_IRON_HANDS
    JOHTO_DEX_IRON_HANDS,
#endif
#if P_FAMILY_IRON_JUGULIS
    JOHTO_DEX_IRON_JUGULIS,
#endif
#if P_FAMILY_IRON_MOTH
    JOHTO_DEX_IRON_MOTH,
#endif
#if P_FAMILY_IRON_THORNS
    JOHTO_DEX_IRON_THORNS,
#endif
#if P_FAMILY_FRIGIBAX
    JOHTO_DEX_FRIGIBAX,
    JOHTO_DEX_ARCTIBAX,
    JOHTO_DEX_BAXCALIBUR,
#endif
#if P_FAMILY_GIMMIGHOUL
    JOHTO_DEX_GIMMIGHOUL,
    JOHTO_DEX_GHOLDENGO,
#endif
#if P_FAMILY_WO_CHIEN
    JOHTO_DEX_WO_CHIEN,
#endif
#if P_FAMILY_CHIEN_PAO
    JOHTO_DEX_CHIEN_PAO,
#endif
#if P_FAMILY_TING_LU
    JOHTO_DEX_TING_LU,
#endif
#if P_FAMILY_CHI_YU
    JOHTO_DEX_CHI_YU,
#endif
#if P_FAMILY_ROARING_MOON
    JOHTO_DEX_ROARING_MOON,
#endif
#if P_FAMILY_IRON_VALIANT
    JOHTO_DEX_IRON_VALIANT,
#endif
#if P_FAMILY_KORAIDON
    JOHTO_DEX_KORAIDON,
#endif
#if P_FAMILY_MIRAIDON
    JOHTO_DEX_MIRAIDON,
#endif
#if P_FAMILY_WALKING_WAKE
    JOHTO_DEX_WALKING_WAKE,
#endif
#if P_FAMILY_IRON_LEAVES
    JOHTO_DEX_IRON_LEAVES,
#endif
#if P_FAMILY_APPLIN && P_GEN_9_CROSS_EVOS
    JOHTO_DEX_DIPPLIN,
#endif
#if P_FAMILY_POLTCHAGEIST
    JOHTO_DEX_POLTCHAGEIST,
    JOHTO_DEX_SINISTCHA,
#endif
#if P_FAMILY_OKIDOGI
    JOHTO_DEX_OKIDOGI,
#endif
#if P_FAMILY_MUNKIDORI
    JOHTO_DEX_MUNKIDORI,
#endif
#if P_FAMILY_FEZANDIPITI
    JOHTO_DEX_FEZANDIPITI,
#endif
#if P_FAMILY_OGERPON
    JOHTO_DEX_OGERPON,
#endif
#if P_FAMILY_DURALUDON && P_GEN_9_CROSS_EVOS
    JOHTO_DEX_ARCHALUDON,
#endif
#if P_FAMILY_APPLIN && P_GEN_9_CROSS_EVOS
    JOHTO_DEX_HYDRAPPLE,
#endif
#if P_FAMILY_GOUGING_FIRE
    JOHTO_DEX_GOUGING_FIRE,
#endif
#if P_FAMILY_RAGING_BOLT
    JOHTO_DEX_RAGING_BOLT,
#endif
#if P_FAMILY_IRON_BOULDER
    JOHTO_DEX_IRON_BOULDER,
#endif
#if P_FAMILY_IRON_CROWN
    JOHTO_DEX_IRON_CROWN,
#endif
#if P_FAMILY_TERAPAGOS
    JOHTO_DEX_TERAPAGOS,
#endif
#if P_FAMILY_PECHARUNT
    JOHTO_DEX_PECHARUNT,
#endif
#if P_FAMILY_RIKO
    JOHTO_DEX_RIKO,
#endif
#if P_FAMILY_BIJUU
    JOHTO_DEX_BIJUU,
#endif
    JOHTO_DEX_COUNT,
};

#if P_GEN_9_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_BIJUU
#elif P_GEN_9_CROSS_EVOS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_HYDRAPPLE
#elif P_PALDEAN_FORMS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_CLODSIRE

#elif P_GEN_8_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_ENAMORUS
#elif P_HISUIAN_FORMS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_OVERQWIL
#elif P_GEN_8_CROSS_EVOS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_URSALUNA
#elif P_GALARIAN_FORMS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_RUNERIGUS

#elif P_GEN_7_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_MELMETAL

#elif P_GEN_6_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_VOLCANION
#elif P_GEN_6_CROSS_EVOS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_SYLVEON

#elif P_GEN_5_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_GENESECT

#elif P_GEN_4_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_ARCEUS
#elif P_GEN_4_CROSS_EVOS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_FROSLASS

#else
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_DEOXYS
#endif

#define POKEMON_SLOTS_NUMBER (NATIONAL_DEX_COUNT + 1)

// Hoenn Pokédex order
enum HoennDexOrder
{
    HOENN_DEX_NONE,
    HOENN_DEX_TREECKO,
    HOENN_DEX_GROVYLE,
    HOENN_DEX_SCEPTILE,
    HOENN_DEX_TORCHIC,
    HOENN_DEX_COMBUSKEN,
    HOENN_DEX_BLAZIKEN,
    HOENN_DEX_MUDKIP,
    HOENN_DEX_MARSHTOMP,
    HOENN_DEX_SWAMPERT,
    HOENN_DEX_POOCHYENA,
    HOENN_DEX_MIGHTYENA,
    HOENN_DEX_ZIGZAGOON,
    HOENN_DEX_LINOONE,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GALARIAN_FORMS
    HOENN_DEX_OBSTAGOON,
#endif
    HOENN_DEX_WURMPLE,
    HOENN_DEX_SILCOON,
    HOENN_DEX_BEAUTIFLY,
    HOENN_DEX_CASCOON,
    HOENN_DEX_DUSTOX,
    HOENN_DEX_LOTAD,
    HOENN_DEX_LOMBRE,
    HOENN_DEX_LUDICOLO,
    HOENN_DEX_SEEDOT,
    HOENN_DEX_NUZLEAF,
    HOENN_DEX_SHIFTRY,
    HOENN_DEX_TAILLOW,
    HOENN_DEX_SWELLOW,
    HOENN_DEX_WINGULL,
    HOENN_DEX_PELIPPER,
    HOENN_DEX_RALTS,
    HOENN_DEX_KIRLIA,
    HOENN_DEX_GARDEVOIR,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_4_CROSS_EVOS
    HOENN_DEX_GALLADE,
#endif
    HOENN_DEX_SURSKIT,
    HOENN_DEX_MASQUERAIN,
    HOENN_DEX_SHROOMISH,
    HOENN_DEX_BRELOOM,
    HOENN_DEX_SLAKOTH,
    HOENN_DEX_VIGOROTH,
    HOENN_DEX_SLAKING,
    HOENN_DEX_ABRA,
    HOENN_DEX_KADABRA,
    HOENN_DEX_ALAKAZAM,
    HOENN_DEX_NINCADA,
    HOENN_DEX_NINJASK,
    HOENN_DEX_SHEDINJA,
    HOENN_DEX_WHISMUR,
    HOENN_DEX_LOUDRED,
    HOENN_DEX_EXPLOUD,
    HOENN_DEX_MAKUHITA,
    HOENN_DEX_HARIYAMA,
    HOENN_DEX_GOLDEEN,
    HOENN_DEX_SEAKING,
    HOENN_DEX_MAGIKARP,
    HOENN_DEX_GYARADOS,
    HOENN_DEX_AZURILL,
    HOENN_DEX_MARILL,
    HOENN_DEX_AZUMARILL,
    HOENN_DEX_GEODUDE,
    HOENN_DEX_GRAVELER,
    HOENN_DEX_GOLEM,
    HOENN_DEX_NOSEPASS,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_4_CROSS_EVOS
    HOENN_DEX_PROBOPASS,
#endif
    HOENN_DEX_SKITTY,
    HOENN_DEX_DELCATTY,
    HOENN_DEX_ZUBAT,
    HOENN_DEX_GOLBAT,
    HOENN_DEX_CROBAT,
    HOENN_DEX_TENTACOOL,
    HOENN_DEX_TENTACRUEL,
    HOENN_DEX_SABLEYE,
    HOENN_DEX_MAWILE,
    HOENN_DEX_ARON,
    HOENN_DEX_LAIRON,
    HOENN_DEX_AGGRON,
    HOENN_DEX_MACHOP,
    HOENN_DEX_MACHOKE,
    HOENN_DEX_MACHAMP,
    HOENN_DEX_MEDITITE,
    HOENN_DEX_MEDICHAM,
    HOENN_DEX_ELECTRIKE,
    HOENN_DEX_MANECTRIC,
    HOENN_DEX_PLUSLE,
    HOENN_DEX_MINUN,
    HOENN_DEX_MAGNEMITE,
    HOENN_DEX_MAGNETON,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_4_CROSS_EVOS
    HOENN_DEX_MAGNEZONE,
#endif
    HOENN_DEX_VOLTORB,
    HOENN_DEX_ELECTRODE,
    HOENN_DEX_VOLBEAT,
    HOENN_DEX_ILLUMISE,
    HOENN_DEX_ODDISH,
    HOENN_DEX_GLOOM,
    HOENN_DEX_VILEPLUME,
    HOENN_DEX_BELLOSSOM,
    HOENN_DEX_DODUO,
    HOENN_DEX_DODRIO,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_4_CROSS_EVOS
    HOENN_DEX_BUDEW,
#endif
    HOENN_DEX_ROSELIA,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_4_CROSS_EVOS
    HOENN_DEX_ROSERADE,
#endif
    HOENN_DEX_GULPIN,
    HOENN_DEX_SWALOT,
    HOENN_DEX_CARVANHA,
    HOENN_DEX_SHARPEDO,
    HOENN_DEX_WAILMER,
    HOENN_DEX_WAILORD,
    HOENN_DEX_NUMEL,
    HOENN_DEX_CAMERUPT,
    HOENN_DEX_SLUGMA,
    HOENN_DEX_MAGCARGO,
    HOENN_DEX_TORKOAL,
    HOENN_DEX_GRIMER,
    HOENN_DEX_MUK,
    HOENN_DEX_KOFFING,
    HOENN_DEX_WEEZING,
    HOENN_DEX_SPOINK,
    HOENN_DEX_GRUMPIG,
    HOENN_DEX_SANDSHREW,
    HOENN_DEX_SANDSLASH,
    HOENN_DEX_SPINDA,
    HOENN_DEX_SKARMORY,
    HOENN_DEX_TRAPINCH,
    HOENN_DEX_VIBRAVA,
    HOENN_DEX_FLYGON,
    HOENN_DEX_CACNEA,
    HOENN_DEX_CACTURNE,
    HOENN_DEX_SWABLU,
    HOENN_DEX_ALTARIA,
    HOENN_DEX_ZANGOOSE,
    HOENN_DEX_SEVIPER,
    HOENN_DEX_LUNATONE,
    HOENN_DEX_SOLROCK,
    HOENN_DEX_BARBOACH,
    HOENN_DEX_WHISCASH,
    HOENN_DEX_CORPHISH,
    HOENN_DEX_CRAWDAUNT,
    HOENN_DEX_BALTOY,
    HOENN_DEX_CLAYDOL,
    HOENN_DEX_LILEEP,
    HOENN_DEX_CRADILY,
    HOENN_DEX_ANORITH,
    HOENN_DEX_ARMALDO,
    HOENN_DEX_IGGLYBUFF,
    HOENN_DEX_JIGGLYPUFF,
    HOENN_DEX_WIGGLYTUFF,
    HOENN_DEX_FEEBAS,
    HOENN_DEX_MILOTIC,
    HOENN_DEX_CASTFORM,
    HOENN_DEX_STARYU,
    HOENN_DEX_STARMIE,
    HOENN_DEX_KECLEON,
    HOENN_DEX_SHUPPET,
    HOENN_DEX_BANETTE,
    HOENN_DEX_DUSKULL,
    HOENN_DEX_DUSCLOPS,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_4_CROSS_EVOS
    HOENN_DEX_DUSKNOIR,
#endif
    HOENN_DEX_TROPIUS,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_4_CROSS_EVOS
    HOENN_DEX_CHINGLING,
#endif
    HOENN_DEX_CHIMECHO,
    HOENN_DEX_ABSOL,
    HOENN_DEX_VULPIX,
    HOENN_DEX_NINETALES,
    HOENN_DEX_PICHU,
    HOENN_DEX_PIKACHU,
    HOENN_DEX_RAICHU,
    HOENN_DEX_PSYDUCK,
    HOENN_DEX_GOLDUCK,
    HOENN_DEX_WYNAUT,
    HOENN_DEX_WOBBUFFET,
    HOENN_DEX_NATU,
    HOENN_DEX_XATU,
    HOENN_DEX_GIRAFARIG,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_9_CROSS_EVOS
    HOENN_DEX_FARIGIRAF,
#endif
    HOENN_DEX_PHANPY,
    HOENN_DEX_DONPHAN,
    HOENN_DEX_PINSIR,
    HOENN_DEX_HERACROSS,
    HOENN_DEX_RHYHORN,
    HOENN_DEX_RHYDON,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_4_CROSS_EVOS
    HOENN_DEX_RHYPERIOR,
#endif
    HOENN_DEX_SNORUNT,
    HOENN_DEX_GLALIE,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_4_CROSS_EVOS
    HOENN_DEX_FROSLASS,
#endif
    HOENN_DEX_SPHEAL,
    HOENN_DEX_SEALEO,
    HOENN_DEX_WALREIN,
    HOENN_DEX_CLAMPERL,
    HOENN_DEX_HUNTAIL,
    HOENN_DEX_GOREBYSS,
    HOENN_DEX_RELICANTH,
    HOENN_DEX_CORSOLA,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GALARIAN_FORMS
    HOENN_DEX_CURSOLA,
#endif
    HOENN_DEX_CHINCHOU,
    HOENN_DEX_LANTURN,
    HOENN_DEX_LUVDISC,
    HOENN_DEX_HORSEA,
    HOENN_DEX_SEADRA,
    HOENN_DEX_KINGDRA,
    HOENN_DEX_BAGON,
    HOENN_DEX_SHELGON,
    HOENN_DEX_SALAMENCE,
    HOENN_DEX_BELDUM,
    HOENN_DEX_METANG,
    HOENN_DEX_METAGROSS,
    HOENN_DEX_REGIROCK,
    HOENN_DEX_REGICE,
    HOENN_DEX_REGISTEEL,
    HOENN_DEX_LATIAS,
    HOENN_DEX_LATIOS,
    HOENN_DEX_KYOGRE,
    HOENN_DEX_GROUDON,
    HOENN_DEX_RAYQUAZA,
    HOENN_DEX_JIRACHI,
    HOENN_DEX_DEOXYS,
};


// Kanto Pokedex order
enum KantoDexOrder
{
    KANTO_DEX_NONE,
    // Kanto
    KANTO_DEX_BULBASAUR,
    KANTO_DEX_IVYSAUR,
    KANTO_DEX_VENUSAUR,
    KANTO_DEX_CHARMANDER,
    KANTO_DEX_CHARMELEON,
    KANTO_DEX_CHARIZARD,
    KANTO_DEX_SQUIRTLE,
    KANTO_DEX_WARTORTLE,
    KANTO_DEX_BLASTOISE,
    KANTO_DEX_CATERPIE,
    KANTO_DEX_METAPOD,
    KANTO_DEX_BUTTERFREE,
    KANTO_DEX_WEEDLE,
    KANTO_DEX_KAKUNA,
    KANTO_DEX_BEEDRILL,
    KANTO_DEX_PIDGEY,
    KANTO_DEX_PIDGEOTTO,
    KANTO_DEX_PIDGEOT,
    KANTO_DEX_RATTATA,
    KANTO_DEX_RATICATE,
    KANTO_DEX_SPEAROW,
    KANTO_DEX_FEAROW,
    KANTO_DEX_EKANS,
    KANTO_DEX_ARBOK,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_2_CROSS_EVOS
    KANTO_DEX_PICHU,
#endif
    KANTO_DEX_PIKACHU,
    KANTO_DEX_RAICHU,
    KANTO_DEX_SANDSHREW,
    KANTO_DEX_SANDSLASH,
    KANTO_DEX_NIDORAN_F,
    KANTO_DEX_NIDORINA,
    KANTO_DEX_NIDOQUEEN,
    KANTO_DEX_NIDORAN_M,
    KANTO_DEX_NIDORINO,
    KANTO_DEX_NIDOKING,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_2_CROSS_EVOS
    KANTO_DEX_CLEFFA,
#endif
    KANTO_DEX_CLEFAIRY,
    KANTO_DEX_CLEFABLE,
    KANTO_DEX_VULPIX,
    KANTO_DEX_NINETALES,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_2_CROSS_EVOS
    KANTO_DEX_IGGLYBUFF,
#endif
    KANTO_DEX_JIGGLYPUFF,
    KANTO_DEX_WIGGLYTUFF,
    KANTO_DEX_ZUBAT,
    KANTO_DEX_GOLBAT,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_2_CROSS_EVOS
    KANTO_DEX_CROBAT,
#endif
    KANTO_DEX_ODDISH,
    KANTO_DEX_GLOOM,
    KANTO_DEX_VILEPLUME,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_2_CROSS_EVOS
    KANTO_DEX_BELLOSSOM,
#endif
    KANTO_DEX_PARAS,
    KANTO_DEX_PARASECT,
    KANTO_DEX_VENONAT,
    KANTO_DEX_VENOMOTH,
    KANTO_DEX_DIGLETT,
    KANTO_DEX_DUGTRIO,
    KANTO_DEX_MEOWTH,
    KANTO_DEX_PERSIAN,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GALARIAN_FORMS
    KANTO_DEX_PERRSERKER,
#endif
    KANTO_DEX_PSYDUCK,
    KANTO_DEX_GOLDUCK,
    KANTO_DEX_MANKEY,
    KANTO_DEX_PRIMEAPE,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_9_CROSS_EVOS
    KANTO_DEX_ANNIHILAPE,
#endif
    KANTO_DEX_GROWLITHE,
    KANTO_DEX_ARCANINE,
    KANTO_DEX_POLIWAG,
    KANTO_DEX_POLIWHIRL,
    KANTO_DEX_POLIWRATH,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_2_CROSS_EVOS
    KANTO_DEX_POLITOED,
#endif
    KANTO_DEX_ABRA,
    KANTO_DEX_KADABRA,
    KANTO_DEX_ALAKAZAM,
    KANTO_DEX_MACHOP,
    KANTO_DEX_MACHOKE,
    KANTO_DEX_MACHAMP,
    KANTO_DEX_BELLSPROUT,
    KANTO_DEX_WEEPINBELL,
    KANTO_DEX_VICTREEBEL,
    KANTO_DEX_TENTACOOL,
    KANTO_DEX_TENTACRUEL,
    KANTO_DEX_GEODUDE,
    KANTO_DEX_GRAVELER,
    KANTO_DEX_GOLEM,
    KANTO_DEX_PONYTA,
    KANTO_DEX_RAPIDASH,
    KANTO_DEX_SLOWPOKE,
    KANTO_DEX_SLOWBRO,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_2_CROSS_EVOS
    KANTO_DEX_SLOWKING,
#endif
    KANTO_DEX_MAGNEMITE,
    KANTO_DEX_MAGNETON,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_4_CROSS_EVOS
    KANTO_DEX_MAGNEZONE,
#endif
    KANTO_DEX_FARFETCHD,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GALARIAN_FORMS
    KANTO_DEX_SIRFETCHD,
#endif
    KANTO_DEX_DODUO,
    KANTO_DEX_DODRIO,
    KANTO_DEX_SEEL,
    KANTO_DEX_DEWGONG,
    KANTO_DEX_GRIMER,
    KANTO_DEX_MUK,
    KANTO_DEX_SHELLDER,
    KANTO_DEX_CLOYSTER,
    KANTO_DEX_GASTLY,
    KANTO_DEX_HAUNTER,
    KANTO_DEX_GENGAR,
    KANTO_DEX_ONIX,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_2_CROSS_EVOS
    KANTO_DEX_STEELIX,
#endif
    KANTO_DEX_DROWZEE,
    KANTO_DEX_HYPNO,
    KANTO_DEX_KRABBY,
    KANTO_DEX_KINGLER,
    KANTO_DEX_VOLTORB,
    KANTO_DEX_ELECTRODE,
    KANTO_DEX_EXEGGCUTE,
    KANTO_DEX_EXEGGUTOR,
    KANTO_DEX_CUBONE,
    KANTO_DEX_MAROWAK,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_2_CROSS_EVOS
    KANTO_DEX_TYROGUE,
#endif
    KANTO_DEX_HITMONLEE,
    KANTO_DEX_HITMONCHAN,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_2_CROSS_EVOS
    KANTO_DEX_HITMONTOP,
#endif
    KANTO_DEX_LICKITUNG,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_4_CROSS_EVOS
    KANTO_DEX_LICKILICKY,
#endif
    KANTO_DEX_KOFFING,
    KANTO_DEX_WEEZING,
    KANTO_DEX_RHYHORN,
    KANTO_DEX_RHYDON,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_4_CROSS_EVOS
    KANTO_DEX_RHYPERIOR,
    KANTO_DEX_HAPPINY,
#endif
    KANTO_DEX_CHANSEY,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_2_CROSS_EVOS
    KANTO_DEX_BLISSEY,
#endif
    KANTO_DEX_TANGELA,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_4_CROSS_EVOS
    KANTO_DEX_TANGROWTH,
#endif
    KANTO_DEX_KANGASKHAN,
    KANTO_DEX_HORSEA,
    KANTO_DEX_SEADRA,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_2_CROSS_EVOS
    KANTO_DEX_KINGDRA,
#endif
    KANTO_DEX_GOLDEEN,
    KANTO_DEX_SEAKING,
    KANTO_DEX_STARYU,
    KANTO_DEX_STARMIE,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_4_CROSS_EVOS
    KANTO_DEX_MIME_JR,
#endif
    KANTO_DEX_MR_MIME,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GALARIAN_FORMS
    KANTO_DEX_MR_RIME,
#endif
    KANTO_DEX_SCYTHER,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_2_CROSS_EVOS
    KANTO_DEX_SCIZOR,
#endif
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_8_CROSS_EVOS
    KANTO_DEX_KLEAVOR,
#endif
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_2_CROSS_EVOS
    KANTO_DEX_SMOOCHUM,
#endif
    KANTO_DEX_JYNX,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_2_CROSS_EVOS
    KANTO_DEX_ELEKID,
#endif
    KANTO_DEX_ELECTABUZZ,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_4_CROSS_EVOS
    KANTO_DEX_ELECTIVIRE,
#endif
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_2_CROSS_EVOS
    KANTO_DEX_MAGBY,
#endif
    KANTO_DEX_MAGMAR,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_4_CROSS_EVOS
    KANTO_DEX_MAGMORTAR,
#endif
    KANTO_DEX_PINSIR,
    KANTO_DEX_TAUROS,
    KANTO_DEX_MAGIKARP,
    KANTO_DEX_GYARADOS,
    KANTO_DEX_LAPRAS,
    KANTO_DEX_DITTO,
    KANTO_DEX_EEVEE,
    KANTO_DEX_VAPOREON,
    KANTO_DEX_JOLTEON,
    KANTO_DEX_FLAREON,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_2_CROSS_EVOS
    KANTO_DEX_ESPEON,
    KANTO_DEX_UMBREON,
#endif
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_4_CROSS_EVOS
    KANTO_DEX_LEAFEON,
    KANTO_DEX_GLACEON,
#endif
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_6_CROSS_EVOS
    KANTO_DEX_SYLVEON,
#endif
    KANTO_DEX_PORYGON,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_2_CROSS_EVOS
    KANTO_DEX_PORYGON2,
#endif
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_4_CROSS_EVOS
    KANTO_DEX_PORYGON_Z,
#endif
    KANTO_DEX_OMANYTE,
    KANTO_DEX_OMASTAR,
    KANTO_DEX_KABUTO,
    KANTO_DEX_KABUTOPS,
    KANTO_DEX_AERODACTYL,
#if P_NEW_EVOS_IN_REGIONAL_DEX && P_GEN_4_CROSS_EVOS
    KANTO_DEX_MUNCHLAX,
#endif
    KANTO_DEX_SNORLAX,
    KANTO_DEX_ARTICUNO,
    KANTO_DEX_ZAPDOS,
    KANTO_DEX_MOLTRES,
    KANTO_DEX_DRATINI,
    KANTO_DEX_DRAGONAIR,
    KANTO_DEX_DRAGONITE,
    KANTO_DEX_MEWTWO,
    KANTO_DEX_MEW,
};

#define KANTO_DEX_COUNT (KANTO_DEX_MEW + 1)
#define HOENN_DEX_COUNT (HOENN_DEX_DEOXYS + 1)

#define REGIONAL_DEX_COUNT (IS_FRLG ? KANTO_DEX_COUNT : HOENN_DEX_COUNT)

#define DECAGRAMS_IN_POUND             4536
#define CM_PER_INCH                    2.54
#define CM_PER_INCH_FACTOR             (CM_PER_INCH * 100)
#define INCHES_IN_FOOT                 12
#define INCHES_IN_ONE_AND_HALF_FOOT    (INCHES_IN_FOOT * 1.5)
#define INCHES_IN_FOOT_FACTOR          (INCHES_IN_FOOT * 10)

#define WEIGHT_HEIGHT_STR_LEN          16
#define WEIGHT_HEIGHT_STR_MEM          (WEIGHT_HEIGHT_STR_LEN * sizeof(u8))

#define DEX_HEADER_X                   96
#define DEX_Y_TOP                      57
#define DEX_Y_BOTTOM                   73
#define DEX_MEASUREMENT_X              129

#define DEX_HGSS_HEADER_X_PADDING      59
#define DEX_HGSS_Y_TOP_PADDING         7
#define DEX_HGSS_Y_BOTTOM_PADDING      4
#define DEX_HGSS_MEASUREMENT_X_PADDING 51

enum
{
    DEX_MODE_HOENN,
    DEX_MODE_NATIONAL
};

enum
{
    FLAG_GET_SEEN,
    FLAG_GET_CAUGHT,
    FLAG_SET_SEEN,
    FLAG_SET_CAUGHT
};

#endif // GUARD_CONSTANTS_POKEDEX_H
