OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "When a Pokémon battle starts, the one\n"
	.string "at the left of the list goes out first.\p"
	.string "So, when you get more Pokémon in your\n"
	.string "party, try switching around the order\p"
	.string "of your Pokémon.\p"
	.string "It could give you an advantage.\p"
	.string "Riko always insists on going first.\n"
	.string "Penny prefers a cozy spot in back.\p"
	.string "Bijuu waits until everyone is watching,\n"
	.string "then copies the most interesting move.$"

