PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "Traveling is wonderful!\p"
	.string "When I was young, I roamed the seas\n"
	.string "and the mountains with a very serious\n"
	.string "Meowth who copied every pose I made!\p"
	.string "I still wonder if it was mocking me.$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "Sigh…\p"
	.string "I wish I could go on an adventure\n"
	.string "with a fluffy Pomeranian…\p"
	.string "Though Riko would expect snacks,\n"
	.string "Penny would worry about the weather,\p"
	.string "and Bijuu would copy the locals.\p"
	.string "It must be fabulous to travel!$"

